// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multiadminservice.proto

package multiadmin

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiAdminService_GetCell_FullMethodName                    = "/multiadmin.MultiAdminService/GetCell"
	MultiAdminService_GetDatabase_FullMethodName                = "/multiadmin.MultiAdminService/GetDatabase"
	MultiAdminService_GetCellNames_FullMethodName               = "/multiadmin.MultiAdminService/GetCellNames"
	MultiAdminService_GetDatabaseNames_FullMethodName           = "/multiadmin.MultiAdminService/GetDatabaseNames"
	MultiAdminService_GetGateways_FullMethodName                = "/multiadmin.MultiAdminService/GetGateways"
	MultiAdminService_GetPoolers_FullMethodName                 = "/multiadmin.MultiAdminService/GetPoolers"
	MultiAdminService_GetOrchs_FullMethodName                   = "/multiadmin.MultiAdminService/GetOrchs"
	MultiAdminService_Backup_FullMethodName                     = "/multiadmin.MultiAdminService/Backup"
	MultiAdminService_RestoreFromBackup_FullMethodName          = "/multiadmin.MultiAdminService/RestoreFromBackup"
	MultiAdminService_GetBackupJobStatus_FullMethodName         = "/multiadmin.MultiAdminService/GetBackupJobStatus"
	MultiAdminService_GetBackups_FullMethodName                 = "/multiadmin.MultiAdminService/GetBackups"
	MultiAdminService_ExpireBackups_FullMethodName              = "/multiadmin.MultiAdminService/ExpireBackups"
	MultiAdminService_GetPoolerStatus_FullMethodName            = "/multiadmin.MultiAdminService/GetPoolerStatus"
	MultiAdminService_SetPostgresRestartsEnabled_FullMethodName = "/multiadmin.MultiAdminService/SetPostgresRestartsEnabled"
	MultiAdminService_GetGatewayQueries_FullMethodName          = "/multiadmin.MultiAdminService/GetGatewayQueries"
	MultiAdminService_GetGatewayConsolidator_FullMethodName     = "/multiadmin.MultiAdminService/GetGatewayConsolidator"
	MultiAdminService_ApplyCertifiedRuleChange_FullMethodName   = "/multiadmin.MultiAdminService/ApplyCertifiedRuleChange"
)

// MultiAdminServiceClient is the client API for MultiAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiAdminService provides administrative gRPC APIs for querying cluster metadata
type MultiAdminServiceClient interface {
	// GetCell retrieves information about a specific cell
	GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*GetCellResponse, error)
	// GetDatabase retrieves information about a specific database
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	// GetCellNames retrieves all cell names in the cluster
	GetCellNames(ctx context.Context, in *GetCellNamesRequest, opts ...grpc.CallOption) (*GetCellNamesResponse, error)
	// GetDatabaseNames retrieves all database names in the cluster
	GetDatabaseNames(ctx context.Context, in *GetDatabaseNamesRequest, opts ...grpc.CallOption) (*GetDatabaseNamesResponse, error)
	// GetGateways retrieves gateways filtered by cells
	GetGateways(ctx context.Context, in *GetGatewaysRequest, opts ...grpc.CallOption) (*GetGatewaysResponse, error)
	// GetPoolers retrieves poolers filtered by cells and/or database
	GetPoolers(ctx context.Context, in *GetPoolersRequest, opts ...grpc.CallOption) (*GetPoolersResponse, error)
	// GetOrchs retrieves orchestrators filtered by cells
	GetOrchs(ctx context.Context, in *GetOrchsRequest, opts ...grpc.CallOption) (*GetOrchsResponse, error)
	// Backup starts an async backup of a specific shard
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	// RestoreFromBackup starts an async restore of a specific shard from a backup
	RestoreFromBackup(ctx context.Context, in *RestoreFromBackupRequest, opts ...grpc.CallOption) (*RestoreFromBackupResponse, error)
	// GetBackupJobStatus checks the status of a backup or restore job
	GetBackupJobStatus(ctx context.Context, in *GetBackupJobStatusRequest, opts ...grpc.CallOption) (*GetBackupJobStatusResponse, error)
	// GetBackups lists backup artifacts with optional filtering
	GetBackups(ctx context.Context, in *GetBackupsRequest, opts ...grpc.CallOption) (*GetBackupsResponse, error)
	// ExpireBackups removes old backups according to retention policy
	ExpireBackups(ctx context.Context, in *ExpireBackupsRequest, opts ...grpc.CallOption) (*ExpireBackupsResponse, error)
	// GetPoolerStatus retrieves the unified status of a specific pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.Status RPC.
	GetPoolerStatus(ctx context.Context, in *GetPoolerStatusRequest, opts ...grpc.CallOption) (*GetPoolerStatusResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts on a pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.SetPostgresRestartsEnabled RPC.
	SetPostgresRestartsEnabled(ctx context.Context, in *SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*SetPostgresRestartsEnabledResponse, error)
	// GetGatewayQueries retrieves the per-fingerprint query registry of a
	// specific multigateway. This proxies the request to the target gateway's
	// MultiGatewayManager.GetQueryRegistry RPC.
	GetGatewayQueries(ctx context.Context, in *GetGatewayQueriesRequest, opts ...grpc.CallOption) (*GetGatewayQueriesResponse, error)
	// GetGatewayConsolidator retrieves the prepared-statement consolidator
	// snapshot of a specific multigateway. This proxies the request to the
	// target gateway's MultiGatewayManager.GetConsolidatorStats RPC.
	GetGatewayConsolidator(ctx context.Context, in *GetGatewayConsolidatorRequest, opts ...grpc.CallOption) (*GetGatewayConsolidatorResponse, error)
	// ApplyCertifiedRuleChange installs a new shard rule using an externally
	// certified revocation. Handles both initial leader appointment (term 0)
	// and stuck-quorum recovery (term > 0).
	//
	// The cert is either supplied explicitly by the caller or, if
	// unsafe_derive_cert is set, derived by multiadmin from a Status probe of
	// the proposed cohort. Multiadmin then forwards the request to the shard's
	// multiorch.
	ApplyCertifiedRuleChange(ctx context.Context, in *ApplyCertifiedRuleChangeRequest, opts ...grpc.CallOption) (*ApplyCertifiedRuleChangeResponse, error)
}

type multiAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiAdminServiceClient(cc grpc.ClientConnInterface) MultiAdminServiceClient {
	_ = "STUB: not implemented"
	return *new(MultiAdminServiceClient)
}

func (c *multiAdminServiceClient) GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*GetCellResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetCellNames(ctx context.Context, in *GetCellNamesRequest, opts ...grpc.CallOption) (*GetCellNamesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetDatabaseNames(ctx context.Context, in *GetDatabaseNamesRequest, opts ...grpc.CallOption) (*GetDatabaseNamesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetGateways(ctx context.Context, in *GetGatewaysRequest, opts ...grpc.CallOption) (*GetGatewaysResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetPoolers(ctx context.Context, in *GetPoolersRequest, opts ...grpc.CallOption) (*GetPoolersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetOrchs(ctx context.Context, in *GetOrchsRequest, opts ...grpc.CallOption) (*GetOrchsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) RestoreFromBackup(ctx context.Context, in *RestoreFromBackupRequest, opts ...grpc.CallOption) (*RestoreFromBackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetBackupJobStatus(ctx context.Context, in *GetBackupJobStatusRequest, opts ...grpc.CallOption) (*GetBackupJobStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetBackups(ctx context.Context, in *GetBackupsRequest, opts ...grpc.CallOption) (*GetBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) ExpireBackups(ctx context.Context, in *ExpireBackupsRequest, opts ...grpc.CallOption) (*ExpireBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetPoolerStatus(ctx context.Context, in *GetPoolerStatusRequest, opts ...grpc.CallOption) (*GetPoolerStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) SetPostgresRestartsEnabled(ctx context.Context, in *SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*SetPostgresRestartsEnabledResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetGatewayQueries(ctx context.Context, in *GetGatewayQueriesRequest, opts ...grpc.CallOption) (*GetGatewayQueriesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) GetGatewayConsolidator(ctx context.Context, in *GetGatewayConsolidatorRequest, opts ...grpc.CallOption) (*GetGatewayConsolidatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiAdminServiceClient) ApplyCertifiedRuleChange(ctx context.Context, in *ApplyCertifiedRuleChangeRequest, opts ...grpc.CallOption) (*ApplyCertifiedRuleChangeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MultiAdminServiceServer is the server API for MultiAdminService service.
// All implementations must embed UnimplementedMultiAdminServiceServer
// for forward compatibility.
//
// MultiAdminService provides administrative gRPC APIs for querying cluster metadata
type MultiAdminServiceServer interface {
	// GetCell retrieves information about a specific cell
	GetCell(context.Context, *GetCellRequest) (*GetCellResponse, error)
	// GetDatabase retrieves information about a specific database
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	// GetCellNames retrieves all cell names in the cluster
	GetCellNames(context.Context, *GetCellNamesRequest) (*GetCellNamesResponse, error)
	// GetDatabaseNames retrieves all database names in the cluster
	GetDatabaseNames(context.Context, *GetDatabaseNamesRequest) (*GetDatabaseNamesResponse, error)
	// GetGateways retrieves gateways filtered by cells
	GetGateways(context.Context, *GetGatewaysRequest) (*GetGatewaysResponse, error)
	// GetPoolers retrieves poolers filtered by cells and/or database
	GetPoolers(context.Context, *GetPoolersRequest) (*GetPoolersResponse, error)
	// GetOrchs retrieves orchestrators filtered by cells
	GetOrchs(context.Context, *GetOrchsRequest) (*GetOrchsResponse, error)
	// Backup starts an async backup of a specific shard
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	// RestoreFromBackup starts an async restore of a specific shard from a backup
	RestoreFromBackup(context.Context, *RestoreFromBackupRequest) (*RestoreFromBackupResponse, error)
	// GetBackupJobStatus checks the status of a backup or restore job
	GetBackupJobStatus(context.Context, *GetBackupJobStatusRequest) (*GetBackupJobStatusResponse, error)
	// GetBackups lists backup artifacts with optional filtering
	GetBackups(context.Context, *GetBackupsRequest) (*GetBackupsResponse, error)
	// ExpireBackups removes old backups according to retention policy
	ExpireBackups(context.Context, *ExpireBackupsRequest) (*ExpireBackupsResponse, error)
	// GetPoolerStatus retrieves the unified status of a specific pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.Status RPC.
	GetPoolerStatus(context.Context, *GetPoolerStatusRequest) (*GetPoolerStatusResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts on a pooler.
	// This proxies the request to the target pooler's MultiPoolerManager.SetPostgresRestartsEnabled RPC.
	SetPostgresRestartsEnabled(context.Context, *SetPostgresRestartsEnabledRequest) (*SetPostgresRestartsEnabledResponse, error)
	// GetGatewayQueries retrieves the per-fingerprint query registry of a
	// specific multigateway. This proxies the request to the target gateway's
	// MultiGatewayManager.GetQueryRegistry RPC.
	GetGatewayQueries(context.Context, *GetGatewayQueriesRequest) (*GetGatewayQueriesResponse, error)
	// GetGatewayConsolidator retrieves the prepared-statement consolidator
	// snapshot of a specific multigateway. This proxies the request to the
	// target gateway's MultiGatewayManager.GetConsolidatorStats RPC.
	GetGatewayConsolidator(context.Context, *GetGatewayConsolidatorRequest) (*GetGatewayConsolidatorResponse, error)
	// ApplyCertifiedRuleChange installs a new shard rule using an externally
	// certified revocation. Handles both initial leader appointment (term 0)
	// and stuck-quorum recovery (term > 0).
	//
	// The cert is either supplied explicitly by the caller or, if
	// unsafe_derive_cert is set, derived by multiadmin from a Status probe of
	// the proposed cohort. Multiadmin then forwards the request to the shard's
	// multiorch.
	ApplyCertifiedRuleChange(context.Context, *ApplyCertifiedRuleChangeRequest) (*ApplyCertifiedRuleChangeResponse, error)
	mustEmbedUnimplementedMultiAdminServiceServer()
}

// UnimplementedMultiAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiAdminServiceServer struct{}

func (UnimplementedMultiAdminServiceServer) GetCell(context.Context, *GetCellRequest) (*GetCellResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetCellNames(context.Context, *GetCellNamesRequest) (*GetCellNamesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetDatabaseNames(context.Context, *GetDatabaseNamesRequest) (*GetDatabaseNamesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetGateways(context.Context, *GetGatewaysRequest) (*GetGatewaysResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetPoolers(context.Context, *GetPoolersRequest) (*GetPoolersResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetOrchs(context.Context, *GetOrchsRequest) (*GetOrchsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) RestoreFromBackup(context.Context, *RestoreFromBackupRequest) (*RestoreFromBackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetBackupJobStatus(context.Context, *GetBackupJobStatusRequest) (*GetBackupJobStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetBackups(context.Context, *GetBackupsRequest) (*GetBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) ExpireBackups(context.Context, *ExpireBackupsRequest) (*ExpireBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetPoolerStatus(context.Context, *GetPoolerStatusRequest) (*GetPoolerStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) SetPostgresRestartsEnabled(context.Context, *SetPostgresRestartsEnabledRequest) (*SetPostgresRestartsEnabledResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetGatewayQueries(context.Context, *GetGatewayQueriesRequest) (*GetGatewayQueriesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) GetGatewayConsolidator(context.Context, *GetGatewayConsolidatorRequest) (*GetGatewayConsolidatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) ApplyCertifiedRuleChange(context.Context, *ApplyCertifiedRuleChangeRequest) (*ApplyCertifiedRuleChangeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiAdminServiceServer) mustEmbedUnimplementedMultiAdminServiceServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedMultiAdminServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"
	return

	// UnsafeMultiAdminServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to MultiAdminServiceServer will
	// result in compilation errors.
}

type UnsafeMultiAdminServiceServer interface {
	mustEmbedUnimplementedMultiAdminServiceServer()
}

func RegisterMultiAdminServiceServer(s grpc.ServiceRegistrar, srv MultiAdminServiceServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedMultiAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _MultiAdminService_GetCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetCellNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetDatabaseNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetPoolers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetOrchs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_RestoreFromBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetBackupJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_ExpireBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetPoolerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_SetPostgresRestartsEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetGatewayQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_GetGatewayConsolidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiAdminService_ApplyCertifiedRuleChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MultiAdminService_ServiceDesc is the grpc.ServiceDesc for MultiAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiadmin.MultiAdminService",
	HandlerType: (*MultiAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCell",
			Handler:    _MultiAdminService_GetCell_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _MultiAdminService_GetDatabase_Handler,
		},
		{
			MethodName: "GetCellNames",
			Handler:    _MultiAdminService_GetCellNames_Handler,
		},
		{
			MethodName: "GetDatabaseNames",
			Handler:    _MultiAdminService_GetDatabaseNames_Handler,
		},
		{
			MethodName: "GetGateways",
			Handler:    _MultiAdminService_GetGateways_Handler,
		},
		{
			MethodName: "GetPoolers",
			Handler:    _MultiAdminService_GetPoolers_Handler,
		},
		{
			MethodName: "GetOrchs",
			Handler:    _MultiAdminService_GetOrchs_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _MultiAdminService_Backup_Handler,
		},
		{
			MethodName: "RestoreFromBackup",
			Handler:    _MultiAdminService_RestoreFromBackup_Handler,
		},
		{
			MethodName: "GetBackupJobStatus",
			Handler:    _MultiAdminService_GetBackupJobStatus_Handler,
		},
		{
			MethodName: "GetBackups",
			Handler:    _MultiAdminService_GetBackups_Handler,
		},
		{
			MethodName: "ExpireBackups",
			Handler:    _MultiAdminService_ExpireBackups_Handler,
		},
		{
			MethodName: "GetPoolerStatus",
			Handler:    _MultiAdminService_GetPoolerStatus_Handler,
		},
		{
			MethodName: "SetPostgresRestartsEnabled",
			Handler:    _MultiAdminService_SetPostgresRestartsEnabled_Handler,
		},
		{
			MethodName: "GetGatewayQueries",
			Handler:    _MultiAdminService_GetGatewayQueries_Handler,
		},
		{
			MethodName: "GetGatewayConsolidator",
			Handler:    _MultiAdminService_GetGatewayConsolidator_Handler,
		},
		{
			MethodName: "ApplyCertifiedRuleChange",
			Handler:    _MultiAdminService_ApplyCertifiedRuleChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiadminservice.proto",
}
