// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: multipoolerservice.proto

/*
Package multipoolerservice is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package multipoolerservice

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_MultiPoolerService_ExecuteQuery_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerService_ExecuteQuery_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_StreamExecute_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (MultiPoolerService_StreamExecuteClient, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(MultiPoolerService_StreamExecuteClient), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_PortalStreamExecute_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (MultiPoolerService_PortalStreamExecuteClient, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(MultiPoolerService_PortalStreamExecuteClient), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_Describe_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerService_Describe_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_GetAuthCredentials_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerService_GetAuthCredentials_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_CopyBidiExecute_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (MultiPoolerService_CopyBidiExecuteClient, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(MultiPoolerService_CopyBidiExecuteClient), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_ConcludeTransaction_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerService_ConcludeTransaction_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_DiscardTempTables_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerService_DiscardTempTables_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_ReleaseReservedConnection_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerService_ReleaseReservedConnection_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_StreamPoolerHealth_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (MultiPoolerService_StreamPoolerHealthClient, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(MultiPoolerService_StreamPoolerHealthClient), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerService_StreamNotifications_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerServiceClient, req *http.Request, pathParams map[string]string) (MultiPoolerService_StreamNotificationsClient, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(MultiPoolerService_StreamNotificationsClient), *new(runtime.ServerMetadata), nil
}

// RegisterMultiPoolerServiceHandlerServer registers the http handlers for service MultiPoolerService to "mux".
// UnaryRPC     :call MultiPoolerServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMultiPoolerServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterMultiPoolerServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server MultiPoolerServiceServer) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiPoolerServiceHandlerFromEndpoint is same as RegisterMultiPoolerServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMultiPoolerServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiPoolerServiceHandler registers the http handlers for service MultiPoolerService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMultiPoolerServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiPoolerServiceHandlerClient registers the http handlers for service MultiPoolerService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MultiPoolerServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MultiPoolerServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MultiPoolerServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterMultiPoolerServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client MultiPoolerServiceClient) error {
	_ = "STUB: not implemented"
	return nil
}

var (
	pattern_MultiPoolerService_ExecuteQuery_0              = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "ExecuteQuery"}, ""))
	pattern_MultiPoolerService_StreamExecute_0             = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "StreamExecute"}, ""))
	pattern_MultiPoolerService_PortalStreamExecute_0       = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "PortalStreamExecute"}, ""))
	pattern_MultiPoolerService_Describe_0                  = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "Describe"}, ""))
	pattern_MultiPoolerService_GetAuthCredentials_0        = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "GetAuthCredentials"}, ""))
	pattern_MultiPoolerService_CopyBidiExecute_0           = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "CopyBidiExecute"}, ""))
	pattern_MultiPoolerService_ConcludeTransaction_0       = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "ConcludeTransaction"}, ""))
	pattern_MultiPoolerService_DiscardTempTables_0         = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "DiscardTempTables"}, ""))
	pattern_MultiPoolerService_ReleaseReservedConnection_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "ReleaseReservedConnection"}, ""))
	pattern_MultiPoolerService_StreamPoolerHealth_0        = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "StreamPoolerHealth"}, ""))
	pattern_MultiPoolerService_StreamNotifications_0       = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolerservice.MultiPoolerService", "StreamNotifications"}, ""))
)

var (
	forward_MultiPoolerService_ExecuteQuery_0              = runtime.ForwardResponseMessage
	forward_MultiPoolerService_StreamExecute_0             = runtime.ForwardResponseStream
	forward_MultiPoolerService_PortalStreamExecute_0       = runtime.ForwardResponseStream
	forward_MultiPoolerService_Describe_0                  = runtime.ForwardResponseMessage
	forward_MultiPoolerService_GetAuthCredentials_0        = runtime.ForwardResponseMessage
	forward_MultiPoolerService_CopyBidiExecute_0           = runtime.ForwardResponseStream
	forward_MultiPoolerService_ConcludeTransaction_0       = runtime.ForwardResponseMessage
	forward_MultiPoolerService_DiscardTempTables_0         = runtime.ForwardResponseMessage
	forward_MultiPoolerService_ReleaseReservedConnection_0 = runtime.ForwardResponseMessage
	forward_MultiPoolerService_StreamPoolerHealth_0        = runtime.ForwardResponseStream
	forward_MultiPoolerService_StreamNotifications_0       = runtime.ForwardResponseStream
)
