// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pgctldservice.proto

package pgctldservice

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server status enumeration
type ServerStatus int32

const (
	ServerStatus_UNKNOWN         ServerStatus = 0
	ServerStatus_STOPPED         ServerStatus = 1
	ServerStatus_STARTING        ServerStatus = 2
	ServerStatus_RUNNING         ServerStatus = 3
	ServerStatus_STOPPING        ServerStatus = 4
	ServerStatus_NOT_INITIALIZED ServerStatus = 5
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "STOPPED",
		2: "STARTING",
		3: "RUNNING",
		4: "STOPPING",
		5: "NOT_INITIALIZED",
	}
	ServerStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"STOPPED":         1,
		"STARTING":        2,
		"RUNNING":         3,
		"STOPPING":        4,
		"NOT_INITIALIZED": 5,
	}
)

func (x ServerStatus) Enum() *ServerStatus { _ = "STUB: not implemented"; return nil }

func (x ServerStatus) String() string { _ = "STUB: not implemented"; return "" }

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (ServerStatus) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Start PostgreSQL server
type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Override the default port
	Port int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Additional postgres command line arguments
	ExtraArgs     []string `protobuf:"bytes,2,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *StartRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*StartRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StartRequest) GetPort() int32 { _ = "STUB: not implemented"; return 0 }

func (x *StartRequest) GetExtraArgs() []string { _ = "STUB: not implemented"; return nil }

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process ID of started PostgreSQL server
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *StartResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*StartResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StartResponse) GetPid() int32 { _ = "STUB: not implemented"; return 0 }

func (x *StartResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// Stop PostgreSQL server
type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shutdown mode: smart, fast, immediate
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Timeout
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *StopRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*StopRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StopRequest) GetMode() string { _ = "STUB: not implemented"; return "" }

func (x *StopRequest) GetTimeout() *durationpb.Duration { _ = "STUB: not implemented"; return nil }

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *StopResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*StopResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StopResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// Restart PostgreSQL server
type RestartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Shutdown mode for stop phase: smart, fast, immediate
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Timeout for stop phase
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Override default port for start phase
	Port      int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ExtraArgs []string `protobuf:"bytes,4,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	// If true, creates standby.signal before restart (for demotion to standby)
	AsStandby     bool `protobuf:"varint,5,opt,name=as_standby,json=asStandby,proto3" json:"as_standby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *RestartRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*RestartRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RestartRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RestartRequest.ProtoReflect.Descriptor instead.
func (*RestartRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RestartRequest) GetMode() string { _ = "STUB: not implemented"; return "" }

func (x *RestartRequest) GetTimeout() *durationpb.Duration { _ = "STUB: not implemented"; return nil }

func (x *RestartRequest) GetPort() int32 { _ = "STUB: not implemented"; return 0 }

func (x *RestartRequest) GetExtraArgs() []string { _ = "STUB: not implemented"; return nil }

func (x *RestartRequest) GetAsStandby() bool { _ = "STUB: not implemented"; return false }

type RestartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process ID of restarted PostgreSQL server
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *RestartResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*RestartResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RestartResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RestartResponse.ProtoReflect.Descriptor instead.
func (*RestartResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RestartResponse) GetPid() int32 { _ = "STUB: not implemented"; return 0 }

func (x *RestartResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// Reload PostgreSQL configuration
type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ReloadConfigRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ReloadConfigRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ReloadConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *ReloadConfigResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*ReloadConfigResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ReloadConfigResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// Get PostgreSQL server status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *StatusRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*StatusRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server status
	Status ServerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pgctldservice.ServerStatus" json:"status,omitempty"`
	// Process ID (if running)
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Server version (if available)
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Uptime (if running)
	Uptime *durationpb.Duration `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Data directory path
	DataDir string `protobuf:"bytes,5,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	// Port number
	Port int32 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	// Host address
	Host string `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	// Is server ready to accept connections
	Ready bool `protobuf:"varint,8,opt,name=ready,proto3" json:"ready,omitempty"`
	// Additional status information
	Message string `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	// pgBackRest TLS server status
	PgbackrestStatus *PgBackRestStatus `protobuf:"bytes,10,opt,name=pgbackrest_status,json=pgbackrestStatus,proto3" json:"pgbackrest_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *StatusResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*StatusResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StatusResponse) GetStatus() ServerStatus {
	_ = "STUB: not implemented"
	return *new(ServerStatus)
}

func (x *StatusResponse) GetPid() int32 { _ = "STUB: not implemented"; return 0 }

func (x *StatusResponse) GetVersion() string { _ = "STUB: not implemented"; return "" }

func (x *StatusResponse) GetUptime() *durationpb.Duration { _ = "STUB: not implemented"; return nil }

func (x *StatusResponse) GetDataDir() string { _ = "STUB: not implemented"; return "" }

func (x *StatusResponse) GetPort() int32 { _ = "STUB: not implemented"; return 0 }

func (x *StatusResponse) GetHost() string { _ = "STUB: not implemented"; return "" }

func (x *StatusResponse) GetReady() bool { _ = "STUB: not implemented"; return false }

func (x *StatusResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

func (x *StatusResponse) GetPgbackrestStatus() *PgBackRestStatus {
	_ = "STUB: not implemented"
	return nil
}

// pgBackRest TLS server status
type PgBackRestStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether pgBackRest TLS server is currently running
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// Error message if startup failed or last crash reason
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Number of times pgBackRest has been restarted due to crashes
	RestartCount int32 `protobuf:"varint,3,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// Last successful startup timestamp
	LastStarted   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_started,json=lastStarted,proto3" json:"last_started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgBackRestStatus) Reset() { _ = "STUB: not implemented"; return }

func (x *PgBackRestStatus) String() string { _ = "STUB: not implemented"; return "" }

func (*PgBackRestStatus) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PgBackRestStatus) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PgBackRestStatus.ProtoReflect.Descriptor instead.
func (*PgBackRestStatus) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PgBackRestStatus) GetRunning() bool { _ = "STUB: not implemented"; return false }

func (x *PgBackRestStatus) GetErrorMessage() string { _ = "STUB: not implemented"; return "" }

func (x *PgBackRestStatus) GetRestartCount() int32 { _ = "STUB: not implemented"; return 0 }

func (x *PgBackRestStatus) GetLastStarted() *timestamppb.Timestamp {
	_ = "STUB: not implemented"
	return nil
}

// Get server version information
type VersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Override default connection parameters
	Host          string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	User          string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *VersionRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*VersionRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *VersionRequest) GetHost() string { _ = "STUB: not implemented"; return "" }

func (x *VersionRequest) GetPort() int32 { _ = "STUB: not implemented"; return 0 }

func (x *VersionRequest) GetDatabase() string { _ = "STUB: not implemented"; return "" }

func (x *VersionRequest) GetUser() string { _ = "STUB: not implemented"; return "" }

type VersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PostgreSQL version string
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *VersionResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*VersionResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *VersionResponse) GetVersion() string { _ = "STUB: not implemented"; return "" }

func (x *VersionResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// Initialize data directory
type InitDataDirRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication method for local connections
	AuthLocal string `protobuf:"bytes,1,opt,name=auth_local,json=authLocal,proto3" json:"auth_local,omitempty"`
	// Authentication method for host connections
	AuthHost string `protobuf:"bytes,2,opt,name=auth_host,json=authHost,proto3" json:"auth_host,omitempty"`
	// Additional initdb arguments
	ExtraArgs     []string `protobuf:"bytes,3,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDataDirRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *InitDataDirRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*InitDataDirRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *InitDataDirRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use InitDataDirRequest.ProtoReflect.Descriptor instead.
func (*InitDataDirRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *InitDataDirRequest) GetAuthLocal() string { _ = "STUB: not implemented"; return "" }

func (x *InitDataDirRequest) GetAuthHost() string { _ = "STUB: not implemented"; return "" }

func (x *InitDataDirRequest) GetExtraArgs() []string { _ = "STUB: not implemented"; return nil }

type InitDataDirResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDataDirResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *InitDataDirResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*InitDataDirResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *InitDataDirResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use InitDataDirResponse.ProtoReflect.Descriptor instead.
func (*InitDataDirResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *InitDataDirResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// PgRewind rewinds a PostgreSQL data directory to an earlier point in the timeline
type PgRewindRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source server hostname
	SourceHost string `protobuf:"bytes,1,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`
	// Source server port
	SourcePort int32 `protobuf:"varint,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// Perform a dry run without making changes (--dry-run)
	DryRun bool `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Additional pg_rewind command line arguments
	ExtraArgs []string `protobuf:"bytes,4,rep,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`
	// Application name for replication connection (used with -R flag)
	// This identifies the standby in pg_stat_replication and synchronous_standby_names
	ApplicationName string `protobuf:"bytes,5,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PgRewindRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *PgRewindRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*PgRewindRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PgRewindRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PgRewindRequest.ProtoReflect.Descriptor instead.
func (*PgRewindRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PgRewindRequest) GetSourceHost() string { _ = "STUB: not implemented"; return "" }

func (x *PgRewindRequest) GetSourcePort() int32 { _ = "STUB: not implemented"; return 0 }

func (x *PgRewindRequest) GetDryRun() bool { _ = "STUB: not implemented"; return false }

func (x *PgRewindRequest) GetExtraArgs() []string { _ = "STUB: not implemented"; return nil }

func (x *PgRewindRequest) GetApplicationName() string { _ = "STUB: not implemented"; return "" }

type PgRewindResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status message
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Output        string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgRewindResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *PgRewindResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*PgRewindResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PgRewindResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PgRewindResponse.ProtoReflect.Descriptor instead.
func (*PgRewindResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PgRewindResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

func (x *PgRewindResponse) GetOutput() string { _ = "STUB: not implemented"; return "" }

var File_pgctldservice_proto protoreflect.FileDescriptor

const file_pgctldservice_proto_rawDesc = "" +
	"\n" +
	"\x13pgctldservice.proto\x12\rpgctldservice\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\fStartRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x02 \x03(\tR\textraArgs\";\n" +
	"\rStartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\vStopRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xab\x01\n" +
	"\x0eRestartRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x04 \x03(\tR\textraArgs\x12\x1d\n" +
	"\n" +
	"as_standby\x18\x05 \x01(\bR\tasStandby\"=\n" +
	"\x0fRestartResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13ReloadConfigRequest\"0\n" +
	"\x14ReloadConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rStatusRequest\"\xe5\x02\n" +
	"\x0eStatusResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.pgctldservice.ServerStatusR\x06status\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x121\n" +
	"\x06uptime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12\x19\n" +
	"\bdata_dir\x18\x05 \x01(\tR\adataDir\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x14\n" +
	"\x05ready\x18\b \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12L\n" +
	"\x11pgbackrest_status\x18\n" +
	" \x01(\v2\x1f.pgctldservice.PgBackRestStatusR\x10pgbackrestStatus\"\xb5\x01\n" +
	"\x10PgBackRestStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12#\n" +
	"\rrestart_count\x18\x03 \x01(\x05R\frestartCount\x12=\n" +
	"\flast_started\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastStarted\"h\n" +
	"\x0eVersionRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"E\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\x12InitDataDirRequest\x12\x1d\n" +
	"\n" +
	"auth_local\x18\x01 \x01(\tR\tauthLocal\x12\x1b\n" +
	"\tauth_host\x18\x02 \x01(\tR\bauthHost\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x03 \x03(\tR\textraArgs\"/\n" +
	"\x13InitDataDirResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb6\x01\n" +
	"\x0fPgRewindRequest\x12\x1f\n" +
	"\vsource_host\x18\x01 \x01(\tR\n" +
	"sourceHost\x12\x1f\n" +
	"\vsource_port\x18\x02 \x01(\x05R\n" +
	"sourcePort\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x04 \x03(\tR\textraArgs\x12)\n" +
	"\x10application_name\x18\x05 \x01(\tR\x0fapplicationName\"D\n" +
	"\x10PgRewindResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output*f\n" +
	"\fServerStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\f\n" +
	"\bSTOPPING\x10\x04\x12\x13\n" +
	"\x0fNOT_INITIALIZED\x10\x052\xe4\x04\n" +
	"\x06PgCtld\x12B\n" +
	"\x05Start\x12\x1b.pgctldservice.StartRequest\x1a\x1c.pgctldservice.StartResponse\x12?\n" +
	"\x04Stop\x12\x1a.pgctldservice.StopRequest\x1a\x1b.pgctldservice.StopResponse\x12H\n" +
	"\aRestart\x12\x1d.pgctldservice.RestartRequest\x1a\x1e.pgctldservice.RestartResponse\x12W\n" +
	"\fReloadConfig\x12\".pgctldservice.ReloadConfigRequest\x1a#.pgctldservice.ReloadConfigResponse\x12E\n" +
	"\x06Status\x12\x1c.pgctldservice.StatusRequest\x1a\x1d.pgctldservice.StatusResponse\x12H\n" +
	"\aVersion\x12\x1d.pgctldservice.VersionRequest\x1a\x1e.pgctldservice.VersionResponse\x12T\n" +
	"\vInitDataDir\x12!.pgctldservice.InitDataDirRequest\x1a\".pgctldservice.InitDataDirResponse\x12K\n" +
	"\bPgRewind\x12\x1e.pgctldservice.PgRewindRequest\x1a\x1f.pgctldservice.PgRewindResponseB4Z2github.com/multigres/multigres/go/pb/pgctldserviceb\x06proto3"

var (
	file_pgctldservice_proto_rawDescOnce sync.Once
	file_pgctldservice_proto_rawDescData []byte
)

func file_pgctldservice_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_pgctldservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pgctldservice_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pgctldservice_proto_goTypes = []any{
	(ServerStatus)(0),             // 0: pgctldservice.ServerStatus
	(*StartRequest)(nil),          // 1: pgctldservice.StartRequest
	(*StartResponse)(nil),         // 2: pgctldservice.StartResponse
	(*StopRequest)(nil),           // 3: pgctldservice.StopRequest
	(*StopResponse)(nil),          // 4: pgctldservice.StopResponse
	(*RestartRequest)(nil),        // 5: pgctldservice.RestartRequest
	(*RestartResponse)(nil),       // 6: pgctldservice.RestartResponse
	(*ReloadConfigRequest)(nil),   // 7: pgctldservice.ReloadConfigRequest
	(*ReloadConfigResponse)(nil),  // 8: pgctldservice.ReloadConfigResponse
	(*StatusRequest)(nil),         // 9: pgctldservice.StatusRequest
	(*StatusResponse)(nil),        // 10: pgctldservice.StatusResponse
	(*PgBackRestStatus)(nil),      // 11: pgctldservice.PgBackRestStatus
	(*VersionRequest)(nil),        // 12: pgctldservice.VersionRequest
	(*VersionResponse)(nil),       // 13: pgctldservice.VersionResponse
	(*InitDataDirRequest)(nil),    // 14: pgctldservice.InitDataDirRequest
	(*InitDataDirResponse)(nil),   // 15: pgctldservice.InitDataDirResponse
	(*PgRewindRequest)(nil),       // 16: pgctldservice.PgRewindRequest
	(*PgRewindResponse)(nil),      // 17: pgctldservice.PgRewindResponse
	(*durationpb.Duration)(nil),   // 18: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_pgctldservice_proto_depIdxs = []int32{
	18, // 0: pgctldservice.StopRequest.timeout:type_name -> google.protobuf.Duration
	18, // 1: pgctldservice.RestartRequest.timeout:type_name -> google.protobuf.Duration
	0,  // 2: pgctldservice.StatusResponse.status:type_name -> pgctldservice.ServerStatus
	18, // 3: pgctldservice.StatusResponse.uptime:type_name -> google.protobuf.Duration
	11, // 4: pgctldservice.StatusResponse.pgbackrest_status:type_name -> pgctldservice.PgBackRestStatus
	19, // 5: pgctldservice.PgBackRestStatus.last_started:type_name -> google.protobuf.Timestamp
	1,  // 6: pgctldservice.PgCtld.Start:input_type -> pgctldservice.StartRequest
	3,  // 7: pgctldservice.PgCtld.Stop:input_type -> pgctldservice.StopRequest
	5,  // 8: pgctldservice.PgCtld.Restart:input_type -> pgctldservice.RestartRequest
	7,  // 9: pgctldservice.PgCtld.ReloadConfig:input_type -> pgctldservice.ReloadConfigRequest
	9,  // 10: pgctldservice.PgCtld.Status:input_type -> pgctldservice.StatusRequest
	12, // 11: pgctldservice.PgCtld.Version:input_type -> pgctldservice.VersionRequest
	14, // 12: pgctldservice.PgCtld.InitDataDir:input_type -> pgctldservice.InitDataDirRequest
	16, // 13: pgctldservice.PgCtld.PgRewind:input_type -> pgctldservice.PgRewindRequest
	2,  // 14: pgctldservice.PgCtld.Start:output_type -> pgctldservice.StartResponse
	4,  // 15: pgctldservice.PgCtld.Stop:output_type -> pgctldservice.StopResponse
	6,  // 16: pgctldservice.PgCtld.Restart:output_type -> pgctldservice.RestartResponse
	8,  // 17: pgctldservice.PgCtld.ReloadConfig:output_type -> pgctldservice.ReloadConfigResponse
	10, // 18: pgctldservice.PgCtld.Status:output_type -> pgctldservice.StatusResponse
	13, // 19: pgctldservice.PgCtld.Version:output_type -> pgctldservice.VersionResponse
	15, // 20: pgctldservice.PgCtld.InitDataDir:output_type -> pgctldservice.InitDataDirResponse
	17, // 21: pgctldservice.PgCtld.PgRewind:output_type -> pgctldservice.PgRewindResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init()                          { file_pgctldservice_proto_init() }
func file_pgctldservice_proto_init() { _ = "STUB: not implemented"; return }
