// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: multigatewaymanagerservice.proto

/*
Package multigatewaymanager is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package multigatewaymanager

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_MultiGatewayManager_GetQueryRegistry_0(ctx context.Context, marshaler runtime.Marshaler, client MultiGatewayManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiGatewayManager_GetQueryRegistry_0(ctx context.Context, marshaler runtime.Marshaler, server MultiGatewayManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiGatewayManager_GetConsolidatorStats_0(ctx context.Context, marshaler runtime.Marshaler, client MultiGatewayManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiGatewayManager_GetConsolidatorStats_0(ctx context.Context, marshaler runtime.Marshaler, server MultiGatewayManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

// RegisterMultiGatewayManagerHandlerServer registers the http handlers for service MultiGatewayManager to "mux".
// UnaryRPC     :call MultiGatewayManagerServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMultiGatewayManagerHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterMultiGatewayManagerHandlerServer(ctx context.Context, mux *runtime.ServeMux, server MultiGatewayManagerServer) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiGatewayManagerHandlerFromEndpoint is same as RegisterMultiGatewayManagerHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMultiGatewayManagerHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiGatewayManagerHandler registers the http handlers for service MultiGatewayManager to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMultiGatewayManagerHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiGatewayManagerHandlerClient registers the http handlers for service MultiGatewayManager
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MultiGatewayManagerClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MultiGatewayManagerClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MultiGatewayManagerClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterMultiGatewayManagerHandlerClient(ctx context.Context, mux *runtime.ServeMux, client MultiGatewayManagerClient) error {
	_ = "STUB: not implemented"
	return nil
}

var (
	pattern_MultiGatewayManager_GetQueryRegistry_0     = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multigatewaymanager.MultiGatewayManager", "GetQueryRegistry"}, ""))
	pattern_MultiGatewayManager_GetConsolidatorStats_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multigatewaymanager.MultiGatewayManager", "GetConsolidatorStats"}, ""))
)

var (
	forward_MultiGatewayManager_GetQueryRegistry_0     = runtime.ForwardResponseMessage
	forward_MultiGatewayManager_GetConsolidatorStats_0 = runtime.ForwardResponseMessage
)
