// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package ast

// Code generated by asthelpergen. DO NOT EDIT.
// Function Generation Source: InterfaceMethod
func (a *application) rewriteNode(parent Node, node Node, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// this should never happen

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfA_ArrayExpr(parent Node, node *A_ArrayExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfA_Const(parent Node, node *A_Const, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfA_Expr(parent Node, node *A_Expr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfA_Indices(parent Node, node *A_Indices, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfA_Indirection(parent Node, node *A_Indirection, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfA_Star(parent Node, node *A_Star, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAccessPriv(parent Node, node *AccessPriv, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAggref(parent Node, node *Aggref, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlias(parent Node, node *Alias, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterCollationStmt(parent Node, node *AlterCollationStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterCompositeTypeStmt(parent Node, node *AlterCompositeTypeStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterDatabaseRefreshCollStmt(parent Node, node *AlterDatabaseRefreshCollStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterDatabaseSetStmt(parent Node, node *AlterDatabaseSetStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterDatabaseStmt(parent Node, node *AlterDatabaseStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterDefaultPrivilegesStmt(parent Node, node *AlterDefaultPrivilegesStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterDomainStmt(parent Node, node *AlterDomainStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterEnumStmt(parent Node, node *AlterEnumStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterEventTrigStmt(parent Node, node *AlterEventTrigStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterExtensionContentsStmt(parent Node, node *AlterExtensionContentsStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterExtensionStmt(parent Node, node *AlterExtensionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterFdwStmt(parent Node, node *AlterFdwStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterForeignServerStmt(parent Node, node *AlterForeignServerStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterFunctionStmt(parent Node, node *AlterFunctionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterObjectDependsStmt(parent Node, node *AlterObjectDependsStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterObjectSchemaStmt(parent Node, node *AlterObjectSchemaStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterOpFamilyStmt(parent Node, node *AlterOpFamilyStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterOperatorStmt(parent Node, node *AlterOperatorStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterOwnerStmt(parent Node, node *AlterOwnerStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterPolicyStmt(parent Node, node *AlterPolicyStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterPublicationStmt(parent Node, node *AlterPublicationStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterReplicationSlotCmd(parent Node, node *AlterReplicationSlotCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterRoleSetStmt(parent Node, node *AlterRoleSetStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterRoleStmt(parent Node, node *AlterRoleStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterSeqStmt(parent Node, node *AlterSeqStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterStatsStmt(parent Node, node *AlterStatsStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterSubscriptionStmt(parent Node, node *AlterSubscriptionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterSystemStmt(parent Node, node *AlterSystemStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTSConfigurationStmt(parent Node, node *AlterTSConfigurationStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTSDictionaryStmt(parent Node, node *AlterTSDictionaryStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTableCmd(parent Node, node *AlterTableCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTableMoveAllStmt(parent Node, node *AlterTableMoveAllStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTableSpaceStmt(parent Node, node *AlterTableSpaceStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTableStmt(parent Node, node *AlterTableStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterTypeStmt(parent Node, node *AlterTypeStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlterUserMappingStmt(parent Node, node *AlterUserMappingStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfAlternativeSubPlan(parent Node, node *AlternativeSubPlan, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfArrayCoerceExpr(parent Node, node *ArrayCoerceExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfArrayExpr(parent Node, node *ArrayExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfBaseExpr(parent Node, node *BaseExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfBaseNode(parent Node, node *BaseNode, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfBitString(parent Node, node *BitString, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfBoolExpr(parent Node, node *BoolExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfBoolean(parent Node, node *Boolean, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfBooleanTest(parent Node, node *BooleanTest, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCTECycleClause(parent Node, node *CTECycleClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCTESearchClause(parent Node, node *CTESearchClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCallStmt(parent Node, node *CallStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCaseExpr(parent Node, node *CaseExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCaseTestExpr(parent Node, node *CaseTestExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCaseWhen(parent Node, node *CaseWhen, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCheckPointStmt(parent Node, node *CheckPointStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfClosePortalStmt(parent Node, node *ClosePortalStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfClusterStmt(parent Node, node *ClusterStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCoalesceExpr(parent Node, node *CoalesceExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCoerceToDomain(parent Node, node *CoerceToDomain, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCoerceToDomainValue(parent Node, node *CoerceToDomainValue, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCoerceViaIO(parent Node, node *CoerceViaIO, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCollateClause(parent Node, node *CollateClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCollateExpr(parent Node, node *CollateExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfColumnDef(parent Node, node *ColumnDef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfColumnRef(parent Node, node *ColumnRef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCommentStmt(parent Node, node *CommentStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCommonTableExpr(parent Node, node *CommonTableExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCompositeTypeStmt(parent Node, node *CompositeTypeStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfConst(parent Node, node *Const, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfConstraint(parent Node, node *Constraint, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfConstraintsSetStmt(parent Node, node *ConstraintsSetStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfConvertRowtypeExpr(parent Node, node *ConvertRowtypeExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCopyStmt(parent Node, node *CopyStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateAmStmt(parent Node, node *CreateAmStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateAssertionStmt(parent Node, node *CreateAssertionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateCastStmt(parent Node, node *CreateCastStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateConversionStmt(parent Node, node *CreateConversionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateDomainStmt(parent Node, node *CreateDomainStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateEnumStmt(parent Node, node *CreateEnumStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateEventTrigStmt(parent Node, node *CreateEventTrigStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateExtensionStmt(parent Node, node *CreateExtensionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateFdwStmt(parent Node, node *CreateFdwStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateForeignServerStmt(parent Node, node *CreateForeignServerStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateForeignTableStmt(parent Node, node *CreateForeignTableStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateFunctionStmt(parent Node, node *CreateFunctionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateOpClassItem(parent Node, node *CreateOpClassItem, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateOpClassStmt(parent Node, node *CreateOpClassStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateOpFamilyStmt(parent Node, node *CreateOpFamilyStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreatePLangStmt(parent Node, node *CreatePLangStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreatePolicyStmt(parent Node, node *CreatePolicyStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreatePublicationStmt(parent Node, node *CreatePublicationStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateRangeStmt(parent Node, node *CreateRangeStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateReplicationSlotCmd(parent Node, node *CreateReplicationSlotCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateRoleStmt(parent Node, node *CreateRoleStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateSchemaStmt(parent Node, node *CreateSchemaStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateSeqStmt(parent Node, node *CreateSeqStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateStatsStmt(parent Node, node *CreateStatsStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateStmt(parent Node, node *CreateStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateSubscriptionStmt(parent Node, node *CreateSubscriptionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateTableAsStmt(parent Node, node *CreateTableAsStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateTableSpaceStmt(parent Node, node *CreateTableSpaceStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateTransformStmt(parent Node, node *CreateTransformStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateTriggerStmt(parent Node, node *CreateTriggerStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreateUserMappingStmt(parent Node, node *CreateUserMappingStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCreatedbStmt(parent Node, node *CreatedbStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfCurrentOfExpr(parent Node, node *CurrentOfExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDeallocateStmt(parent Node, node *DeallocateStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDeclareCursorStmt(parent Node, node *DeclareCursorStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDefElem(parent Node, node *DefElem, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDefineStmt(parent Node, node *DefineStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDeleteStmt(parent Node, node *DeleteStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDiscardStmt(parent Node, node *DiscardStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDoStmt(parent Node, node *DoStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropOwnedStmt(parent Node, node *DropOwnedStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropReplicationSlotCmd(parent Node, node *DropReplicationSlotCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropRoleStmt(parent Node, node *DropRoleStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropStmt(parent Node, node *DropStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropTableSpaceStmt(parent Node, node *DropTableSpaceStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropUserMappingStmt(parent Node, node *DropUserMappingStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfDropdbStmt(parent Node, node *DropdbStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfExecuteStmt(parent Node, node *ExecuteStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfExplainStmt(parent Node, node *ExplainStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: InterfaceMethod
func (a *application) rewriteExpr(parent Node, node Expr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// this should never happen

// Function Generation Source: InterfaceMethod
func (a *application) rewriteExpression(parent Node, node Expression, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// this should never happen

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFetchStmt(parent Node, node *FetchStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFieldSelect(parent Node, node *FieldSelect, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFieldStore(parent Node, node *FieldStore, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFloat(parent Node, node *Float, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFromExpr(parent Node, node *FromExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFuncCall(parent Node, node *FuncCall, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFuncExpr(parent Node, node *FuncExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfFunctionParameter(parent Node, node *FunctionParameter, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfGrantRoleStmt(parent Node, node *GrantRoleStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfGrantStmt(parent Node, node *GrantStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfGroupingFunc(parent Node, node *GroupingFunc, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfGroupingSet(parent Node, node *GroupingSet, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfIdentifier(parent Node, node *Identifier, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfIdentifySystemCmd(parent Node, node *IdentifySystemCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfImportForeignSchemaStmt(parent Node, node *ImportForeignSchemaStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfIndexElem(parent Node, node *IndexElem, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfIndexStmt(parent Node, node *IndexStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfInferClause(parent Node, node *InferClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfInferenceElem(parent Node, node *InferenceElem, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfInsertStmt(parent Node, node *InsertStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfInteger(parent Node, node *Integer, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfIntoClause(parent Node, node *IntoClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJoinExpr(parent Node, node *JoinExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonAggConstructor(parent Node, node *JsonAggConstructor, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonArgument(parent Node, node *JsonArgument, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonArrayAgg(parent Node, node *JsonArrayAgg, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonArrayConstructor(parent Node, node *JsonArrayConstructor, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonArrayQueryConstructor(parent Node, node *JsonArrayQueryConstructor, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonBehavior(parent Node, node *JsonBehavior, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonConstructorExpr(parent Node, node *JsonConstructorExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonExpr(parent Node, node *JsonExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonFormat(parent Node, node *JsonFormat, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonFuncExpr(parent Node, node *JsonFuncExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonIsPredicate(parent Node, node *JsonIsPredicate, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonKeyValue(parent Node, node *JsonKeyValue, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonObjectAgg(parent Node, node *JsonObjectAgg, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonObjectConstructor(parent Node, node *JsonObjectConstructor, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonOutput(parent Node, node *JsonOutput, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonParseExpr(parent Node, node *JsonParseExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonReturning(parent Node, node *JsonReturning, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonScalarExpr(parent Node, node *JsonScalarExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonSerializeExpr(parent Node, node *JsonSerializeExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTable(parent Node, node *JsonTable, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTableColumn(parent Node, node *JsonTableColumn, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTablePath(parent Node, node *JsonTablePath, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTablePathScan(parent Node, node *JsonTablePathScan, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTablePathSpec(parent Node, node *JsonTablePathSpec, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTablePlan(parent Node, node *JsonTablePlan, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonTableSiblingJoin(parent Node, node *JsonTableSiblingJoin, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfJsonValueExpr(parent Node, node *JsonValueExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfKeyAction(parent Node, node *KeyAction, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfKeyActions(parent Node, node *KeyActions, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfListenStmt(parent Node, node *ListenStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfLoadStmt(parent Node, node *LoadStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfLockStmt(parent Node, node *LockStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfLockingClause(parent Node, node *LockingClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfMergeAction(parent Node, node *MergeAction, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfMergeStmt(parent Node, node *MergeStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfMergeSupportFunc(parent Node, node *MergeSupportFunc, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfMergeWhenClause(parent Node, node *MergeWhenClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfMinMaxExpr(parent Node, node *MinMaxExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfMultiAssignRef(parent Node, node *MultiAssignRef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfNamedArgExpr(parent Node, node *NamedArgExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfNextValueExpr(parent Node, node *NextValueExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfNodeList(parent Node, node *NodeList, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfNotifyStmt(parent Node, node *NotifyStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfNull(parent Node, node *Null, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfNullTest(parent Node, node *NullTest, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfObjectWithArgs(parent Node, node *ObjectWithArgs, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfOnConflictClause(parent Node, node *OnConflictClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfOnConflictExpr(parent Node, node *OnConflictExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfOpExpr(parent Node, node *OpExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPLAssignStmt(parent Node, node *PLAssignStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfParam(parent Node, node *Param, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfParamRef(parent Node, node *ParamRef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfParenExpr(parent Node, node *ParenExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPartitionBoundSpec(parent Node, node *PartitionBoundSpec, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPartitionCmd(parent Node, node *PartitionCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPartitionElem(parent Node, node *PartitionElem, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPartitionRangeDatum(parent Node, node *PartitionRangeDatum, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPartitionSpec(parent Node, node *PartitionSpec, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPrepareStmt(parent Node, node *PrepareStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPublicationObjSpec(parent Node, node *PublicationObjSpec, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfPublicationTable(parent Node, node *PublicationTable, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfQuery(parent Node, node *Query, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRTEPermissionInfo(parent Node, node *RTEPermissionInfo, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeFunction(parent Node, node *RangeFunction, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeSubselect(parent Node, node *RangeSubselect, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeTableFunc(parent Node, node *RangeTableFunc, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeTableFuncCol(parent Node, node *RangeTableFuncCol, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeTableSample(parent Node, node *RangeTableSample, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeTblEntry(parent Node, node *RangeTblEntry, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeTblFunction(parent Node, node *RangeTblFunction, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeTblRef(parent Node, node *RangeTblRef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRangeVar(parent Node, node *RangeVar, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRawStmt(parent Node, node *RawStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfReadReplicationSlotCmd(parent Node, node *ReadReplicationSlotCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfReassignOwnedStmt(parent Node, node *ReassignOwnedStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRefreshMatViewStmt(parent Node, node *RefreshMatViewStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfReindexStmt(parent Node, node *ReindexStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRelabelType(parent Node, node *RelabelType, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRenameStmt(parent Node, node *RenameStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfReplicaIdentityStmt(parent Node, node *ReplicaIdentityStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfResTarget(parent Node, node *ResTarget, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfReturnStmt(parent Node, node *ReturnStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRoleSpec(parent Node, node *RoleSpec, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: StructMethod
func (a *application) rewriteRootNode(parent Node, node RootNode, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRowCompareExpr(parent Node, node *RowCompareExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRowExpr(parent Node, node *RowExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRowMarkClause(parent Node, node *RowMarkClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRuleStmt(parent Node, node *RuleStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSQLValueFunction(parent Node, node *SQLValueFunction, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfScalarArrayOpExpr(parent Node, node *ScalarArrayOpExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSecLabelStmt(parent Node, node *SecLabelStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSelectStmt(parent Node, node *SelectStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSetOperationStmt(parent Node, node *SetOperationStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSetToDefault(parent Node, node *SetToDefault, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSinglePartitionSpec(parent Node, node *SinglePartitionSpec, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSortBy(parent Node, node *SortBy, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSortGroupClause(parent Node, node *SortGroupClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfStartReplicationCmd(parent Node, node *StartReplicationCmd, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfStatsElem(parent Node, node *StatsElem, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: InterfaceMethod
func (a *application) rewriteStmt(parent Node, node Stmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// this should never happen

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfString(parent Node, node *String, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSubLink(parent Node, node *SubLink, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSubPlan(parent Node, node *SubPlan, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfSubscriptingRef(parent Node, node *SubscriptingRef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTableFunc(parent Node, node *TableFunc, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTableLikeClause(parent Node, node *TableLikeClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTableSampleClause(parent Node, node *TableSampleClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTargetEntry(parent Node, node *TargetEntry, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTransactionStmt(parent Node, node *TransactionStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTriggerTransition(parent Node, node *TriggerTransition, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTruncateStmt(parent Node, node *TruncateStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTypeCast(parent Node, node *TypeCast, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfTypeName(parent Node, node *TypeName, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfUnlistenStmt(parent Node, node *UnlistenStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfUpdateStmt(parent Node, node *UpdateStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfVacuumRelation(parent Node, node *VacuumRelation, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfVacuumStmt(parent Node, node *VacuumStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: InterfaceMethod
func (a *application) rewriteValue(parent Node, node Value, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// this should never happen

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfVar(parent Node, node *Var, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfVariableSetStmt(parent Node, node *VariableSetStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfVariableShowStmt(parent Node, node *VariableShowStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfViewStmt(parent Node, node *ViewStmt, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfWindowClause(parent Node, node *WindowClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfWindowDef(parent Node, node *WindowDef, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfWindowFunc(parent Node, node *WindowFunc, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfWindowFuncRunCondition(parent Node, node *WindowFuncRunCondition, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfWithCheckOption(parent Node, node *WithCheckOption, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfWithClause(parent Node, node *WithClause, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfXmlExpr(parent Node, node *XmlExpr, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfXmlSerialize(parent Node, node *XmlSerialize, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}

// Function Generation Source: PtrToStructMethod
func (a *application) rewriteRefOfRootNode(parent Node, node *RootNode, replacer replacerFunc) bool {
	_ = "STUB: not implemented"
	return false
}
