// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package ast

// Code generated by asthelpergen. DO NOT EDIT.
// CloneNode creates a deep clone of the input.
func CloneNode(in Node) Node { _ = "STUB: not implemented"; return *new(Node) }

// this should never happen

// CloneRefOfA_ArrayExpr creates a deep clone of the input.
func CloneRefOfA_ArrayExpr(n *A_ArrayExpr) *A_ArrayExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfA_Const creates a deep clone of the input.
func CloneRefOfA_Const(n *A_Const) *A_Const { _ = "STUB: not implemented"; return nil }

// CloneRefOfA_Expr creates a deep clone of the input.
func CloneRefOfA_Expr(n *A_Expr) *A_Expr { _ = "STUB: not implemented"; return nil }

// CloneRefOfA_Indices creates a deep clone of the input.
func CloneRefOfA_Indices(n *A_Indices) *A_Indices { _ = "STUB: not implemented"; return nil }

// CloneRefOfA_Indirection creates a deep clone of the input.
func CloneRefOfA_Indirection(n *A_Indirection) *A_Indirection {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfA_Star creates a deep clone of the input.
func CloneRefOfA_Star(n *A_Star) *A_Star { _ = "STUB: not implemented"; return nil }

// CloneRefOfAccessPriv creates a deep clone of the input.
func CloneRefOfAccessPriv(n *AccessPriv) *AccessPriv { _ = "STUB: not implemented"; return nil }

// CloneRefOfAggref creates a deep clone of the input.
func CloneRefOfAggref(n *Aggref) *Aggref { _ = "STUB: not implemented"; return nil }

// CloneRefOfAlias creates a deep clone of the input.
func CloneRefOfAlias(n *Alias) *Alias { _ = "STUB: not implemented"; return nil }

// CloneRefOfAlterCollationStmt creates a deep clone of the input.
func CloneRefOfAlterCollationStmt(n *AlterCollationStmt) *AlterCollationStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterCompositeTypeStmt creates a deep clone of the input.
func CloneRefOfAlterCompositeTypeStmt(n *AlterCompositeTypeStmt) *AlterCompositeTypeStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterDatabaseRefreshCollStmt creates a deep clone of the input.
func CloneRefOfAlterDatabaseRefreshCollStmt(n *AlterDatabaseRefreshCollStmt) *AlterDatabaseRefreshCollStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterDatabaseSetStmt creates a deep clone of the input.
func CloneRefOfAlterDatabaseSetStmt(n *AlterDatabaseSetStmt) *AlterDatabaseSetStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterDatabaseStmt creates a deep clone of the input.
func CloneRefOfAlterDatabaseStmt(n *AlterDatabaseStmt) *AlterDatabaseStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterDefaultPrivilegesStmt creates a deep clone of the input.
func CloneRefOfAlterDefaultPrivilegesStmt(n *AlterDefaultPrivilegesStmt) *AlterDefaultPrivilegesStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterDomainStmt creates a deep clone of the input.
func CloneRefOfAlterDomainStmt(n *AlterDomainStmt) *AlterDomainStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterEnumStmt creates a deep clone of the input.
func CloneRefOfAlterEnumStmt(n *AlterEnumStmt) *AlterEnumStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterEventTrigStmt creates a deep clone of the input.
func CloneRefOfAlterEventTrigStmt(n *AlterEventTrigStmt) *AlterEventTrigStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterExtensionContentsStmt creates a deep clone of the input.
func CloneRefOfAlterExtensionContentsStmt(n *AlterExtensionContentsStmt) *AlterExtensionContentsStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterExtensionStmt creates a deep clone of the input.
func CloneRefOfAlterExtensionStmt(n *AlterExtensionStmt) *AlterExtensionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterFdwStmt creates a deep clone of the input.
func CloneRefOfAlterFdwStmt(n *AlterFdwStmt) *AlterFdwStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfAlterForeignServerStmt creates a deep clone of the input.
func CloneRefOfAlterForeignServerStmt(n *AlterForeignServerStmt) *AlterForeignServerStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterFunctionStmt creates a deep clone of the input.
func CloneRefOfAlterFunctionStmt(n *AlterFunctionStmt) *AlterFunctionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterObjectDependsStmt creates a deep clone of the input.
func CloneRefOfAlterObjectDependsStmt(n *AlterObjectDependsStmt) *AlterObjectDependsStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterObjectSchemaStmt creates a deep clone of the input.
func CloneRefOfAlterObjectSchemaStmt(n *AlterObjectSchemaStmt) *AlterObjectSchemaStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterOpFamilyStmt creates a deep clone of the input.
func CloneRefOfAlterOpFamilyStmt(n *AlterOpFamilyStmt) *AlterOpFamilyStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterOperatorStmt creates a deep clone of the input.
func CloneRefOfAlterOperatorStmt(n *AlterOperatorStmt) *AlterOperatorStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterOwnerStmt creates a deep clone of the input.
func CloneRefOfAlterOwnerStmt(n *AlterOwnerStmt) *AlterOwnerStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterPolicyStmt creates a deep clone of the input.
func CloneRefOfAlterPolicyStmt(n *AlterPolicyStmt) *AlterPolicyStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterPublicationStmt creates a deep clone of the input.
func CloneRefOfAlterPublicationStmt(n *AlterPublicationStmt) *AlterPublicationStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterReplicationSlotCmd creates a deep clone of the input.
func CloneRefOfAlterReplicationSlotCmd(n *AlterReplicationSlotCmd) *AlterReplicationSlotCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterRoleSetStmt creates a deep clone of the input.
func CloneRefOfAlterRoleSetStmt(n *AlterRoleSetStmt) *AlterRoleSetStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterRoleStmt creates a deep clone of the input.
func CloneRefOfAlterRoleStmt(n *AlterRoleStmt) *AlterRoleStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterSeqStmt creates a deep clone of the input.
func CloneRefOfAlterSeqStmt(n *AlterSeqStmt) *AlterSeqStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfAlterStatsStmt creates a deep clone of the input.
func CloneRefOfAlterStatsStmt(n *AlterStatsStmt) *AlterStatsStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterSubscriptionStmt creates a deep clone of the input.
func CloneRefOfAlterSubscriptionStmt(n *AlterSubscriptionStmt) *AlterSubscriptionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterSystemStmt creates a deep clone of the input.
func CloneRefOfAlterSystemStmt(n *AlterSystemStmt) *AlterSystemStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTSConfigurationStmt creates a deep clone of the input.
func CloneRefOfAlterTSConfigurationStmt(n *AlterTSConfigurationStmt) *AlterTSConfigurationStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTSDictionaryStmt creates a deep clone of the input.
func CloneRefOfAlterTSDictionaryStmt(n *AlterTSDictionaryStmt) *AlterTSDictionaryStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTableCmd creates a deep clone of the input.
func CloneRefOfAlterTableCmd(n *AlterTableCmd) *AlterTableCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTableMoveAllStmt creates a deep clone of the input.
func CloneRefOfAlterTableMoveAllStmt(n *AlterTableMoveAllStmt) *AlterTableMoveAllStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTableSpaceStmt creates a deep clone of the input.
func CloneRefOfAlterTableSpaceStmt(n *AlterTableSpaceStmt) *AlterTableSpaceStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTableStmt creates a deep clone of the input.
func CloneRefOfAlterTableStmt(n *AlterTableStmt) *AlterTableStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterTypeStmt creates a deep clone of the input.
func CloneRefOfAlterTypeStmt(n *AlterTypeStmt) *AlterTypeStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlterUserMappingStmt creates a deep clone of the input.
func CloneRefOfAlterUserMappingStmt(n *AlterUserMappingStmt) *AlterUserMappingStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfAlternativeSubPlan creates a deep clone of the input.
func CloneRefOfAlternativeSubPlan(n *AlternativeSubPlan) *AlternativeSubPlan {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfArrayCoerceExpr creates a deep clone of the input.
func CloneRefOfArrayCoerceExpr(n *ArrayCoerceExpr) *ArrayCoerceExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfArrayExpr creates a deep clone of the input.
func CloneRefOfArrayExpr(n *ArrayExpr) *ArrayExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfBaseExpr creates a deep clone of the input.
func CloneRefOfBaseExpr(n *BaseExpr) *BaseExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfBaseNode creates a deep clone of the input.
func CloneRefOfBaseNode(n *BaseNode) *BaseNode { _ = "STUB: not implemented"; return nil }

// CloneRefOfBitString creates a deep clone of the input.
func CloneRefOfBitString(n *BitString) *BitString { _ = "STUB: not implemented"; return nil }

// CloneRefOfBoolExpr creates a deep clone of the input.
func CloneRefOfBoolExpr(n *BoolExpr) *BoolExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfBoolean creates a deep clone of the input.
func CloneRefOfBoolean(n *Boolean) *Boolean { _ = "STUB: not implemented"; return nil }

// CloneRefOfBooleanTest creates a deep clone of the input.
func CloneRefOfBooleanTest(n *BooleanTest) *BooleanTest { _ = "STUB: not implemented"; return nil }

// CloneRefOfCTECycleClause creates a deep clone of the input.
func CloneRefOfCTECycleClause(n *CTECycleClause) *CTECycleClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCTESearchClause creates a deep clone of the input.
func CloneRefOfCTESearchClause(n *CTESearchClause) *CTESearchClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCallStmt creates a deep clone of the input.
func CloneRefOfCallStmt(n *CallStmt) *CallStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCaseExpr creates a deep clone of the input.
func CloneRefOfCaseExpr(n *CaseExpr) *CaseExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfCaseTestExpr creates a deep clone of the input.
func CloneRefOfCaseTestExpr(n *CaseTestExpr) *CaseTestExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfCaseWhen creates a deep clone of the input.
func CloneRefOfCaseWhen(n *CaseWhen) *CaseWhen { _ = "STUB: not implemented"; return nil }

// CloneRefOfCheckPointStmt creates a deep clone of the input.
func CloneRefOfCheckPointStmt(n *CheckPointStmt) *CheckPointStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfClosePortalStmt creates a deep clone of the input.
func CloneRefOfClosePortalStmt(n *ClosePortalStmt) *ClosePortalStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfClusterStmt creates a deep clone of the input.
func CloneRefOfClusterStmt(n *ClusterStmt) *ClusterStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCoalesceExpr creates a deep clone of the input.
func CloneRefOfCoalesceExpr(n *CoalesceExpr) *CoalesceExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfCoerceToDomain creates a deep clone of the input.
func CloneRefOfCoerceToDomain(n *CoerceToDomain) *CoerceToDomain {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCoerceToDomainValue creates a deep clone of the input.
func CloneRefOfCoerceToDomainValue(n *CoerceToDomainValue) *CoerceToDomainValue {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCoerceViaIO creates a deep clone of the input.
func CloneRefOfCoerceViaIO(n *CoerceViaIO) *CoerceViaIO { _ = "STUB: not implemented"; return nil }

// CloneRefOfCollateClause creates a deep clone of the input.
func CloneRefOfCollateClause(n *CollateClause) *CollateClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCollateExpr creates a deep clone of the input.
func CloneRefOfCollateExpr(n *CollateExpr) *CollateExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfColumnDef creates a deep clone of the input.
func CloneRefOfColumnDef(n *ColumnDef) *ColumnDef { _ = "STUB: not implemented"; return nil }

// CloneRefOfColumnRef creates a deep clone of the input.
func CloneRefOfColumnRef(n *ColumnRef) *ColumnRef { _ = "STUB: not implemented"; return nil }

// CloneRefOfCommentStmt creates a deep clone of the input.
func CloneRefOfCommentStmt(n *CommentStmt) *CommentStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCommonTableExpr creates a deep clone of the input.
func CloneRefOfCommonTableExpr(n *CommonTableExpr) *CommonTableExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCompositeTypeStmt creates a deep clone of the input.
func CloneRefOfCompositeTypeStmt(n *CompositeTypeStmt) *CompositeTypeStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfConst creates a deep clone of the input.
func CloneRefOfConst(n *Const) *Const { _ = "STUB: not implemented"; return nil }

// CloneRefOfConstraint creates a deep clone of the input.
func CloneRefOfConstraint(n *Constraint) *Constraint { _ = "STUB: not implemented"; return nil }

// CloneRefOfConstraintsSetStmt creates a deep clone of the input.
func CloneRefOfConstraintsSetStmt(n *ConstraintsSetStmt) *ConstraintsSetStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfConvertRowtypeExpr creates a deep clone of the input.
func CloneRefOfConvertRowtypeExpr(n *ConvertRowtypeExpr) *ConvertRowtypeExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCopyStmt creates a deep clone of the input.
func CloneRefOfCopyStmt(n *CopyStmt) *CopyStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCreateAmStmt creates a deep clone of the input.
func CloneRefOfCreateAmStmt(n *CreateAmStmt) *CreateAmStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCreateAssertionStmt creates a deep clone of the input.
func CloneRefOfCreateAssertionStmt(n *CreateAssertionStmt) *CreateAssertionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateCastStmt creates a deep clone of the input.
func CloneRefOfCreateCastStmt(n *CreateCastStmt) *CreateCastStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateConversionStmt creates a deep clone of the input.
func CloneRefOfCreateConversionStmt(n *CreateConversionStmt) *CreateConversionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateDomainStmt creates a deep clone of the input.
func CloneRefOfCreateDomainStmt(n *CreateDomainStmt) *CreateDomainStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateEnumStmt creates a deep clone of the input.
func CloneRefOfCreateEnumStmt(n *CreateEnumStmt) *CreateEnumStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateEventTrigStmt creates a deep clone of the input.
func CloneRefOfCreateEventTrigStmt(n *CreateEventTrigStmt) *CreateEventTrigStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateExtensionStmt creates a deep clone of the input.
func CloneRefOfCreateExtensionStmt(n *CreateExtensionStmt) *CreateExtensionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateFdwStmt creates a deep clone of the input.
func CloneRefOfCreateFdwStmt(n *CreateFdwStmt) *CreateFdwStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateForeignServerStmt creates a deep clone of the input.
func CloneRefOfCreateForeignServerStmt(n *CreateForeignServerStmt) *CreateForeignServerStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateForeignTableStmt creates a deep clone of the input.
func CloneRefOfCreateForeignTableStmt(n *CreateForeignTableStmt) *CreateForeignTableStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateFunctionStmt creates a deep clone of the input.
func CloneRefOfCreateFunctionStmt(n *CreateFunctionStmt) *CreateFunctionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateOpClassItem creates a deep clone of the input.
func CloneRefOfCreateOpClassItem(n *CreateOpClassItem) *CreateOpClassItem {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateOpClassStmt creates a deep clone of the input.
func CloneRefOfCreateOpClassStmt(n *CreateOpClassStmt) *CreateOpClassStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateOpFamilyStmt creates a deep clone of the input.
func CloneRefOfCreateOpFamilyStmt(n *CreateOpFamilyStmt) *CreateOpFamilyStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreatePLangStmt creates a deep clone of the input.
func CloneRefOfCreatePLangStmt(n *CreatePLangStmt) *CreatePLangStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreatePolicyStmt creates a deep clone of the input.
func CloneRefOfCreatePolicyStmt(n *CreatePolicyStmt) *CreatePolicyStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreatePublicationStmt creates a deep clone of the input.
func CloneRefOfCreatePublicationStmt(n *CreatePublicationStmt) *CreatePublicationStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateRangeStmt creates a deep clone of the input.
func CloneRefOfCreateRangeStmt(n *CreateRangeStmt) *CreateRangeStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateReplicationSlotCmd creates a deep clone of the input.
func CloneRefOfCreateReplicationSlotCmd(n *CreateReplicationSlotCmd) *CreateReplicationSlotCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateRoleStmt creates a deep clone of the input.
func CloneRefOfCreateRoleStmt(n *CreateRoleStmt) *CreateRoleStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateSchemaStmt creates a deep clone of the input.
func CloneRefOfCreateSchemaStmt(n *CreateSchemaStmt) *CreateSchemaStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateSeqStmt creates a deep clone of the input.
func CloneRefOfCreateSeqStmt(n *CreateSeqStmt) *CreateSeqStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateStatsStmt creates a deep clone of the input.
func CloneRefOfCreateStatsStmt(n *CreateStatsStmt) *CreateStatsStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateStmt creates a deep clone of the input.
func CloneRefOfCreateStmt(n *CreateStmt) *CreateStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCreateSubscriptionStmt creates a deep clone of the input.
func CloneRefOfCreateSubscriptionStmt(n *CreateSubscriptionStmt) *CreateSubscriptionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateTableAsStmt creates a deep clone of the input.
func CloneRefOfCreateTableAsStmt(n *CreateTableAsStmt) *CreateTableAsStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateTableSpaceStmt creates a deep clone of the input.
func CloneRefOfCreateTableSpaceStmt(n *CreateTableSpaceStmt) *CreateTableSpaceStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateTransformStmt creates a deep clone of the input.
func CloneRefOfCreateTransformStmt(n *CreateTransformStmt) *CreateTransformStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateTriggerStmt creates a deep clone of the input.
func CloneRefOfCreateTriggerStmt(n *CreateTriggerStmt) *CreateTriggerStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreateUserMappingStmt creates a deep clone of the input.
func CloneRefOfCreateUserMappingStmt(n *CreateUserMappingStmt) *CreateUserMappingStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfCreatedbStmt creates a deep clone of the input.
func CloneRefOfCreatedbStmt(n *CreatedbStmt) *CreatedbStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfCurrentOfExpr creates a deep clone of the input.
func CloneRefOfCurrentOfExpr(n *CurrentOfExpr) *CurrentOfExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDeallocateStmt creates a deep clone of the input.
func CloneRefOfDeallocateStmt(n *DeallocateStmt) *DeallocateStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDeclareCursorStmt creates a deep clone of the input.
func CloneRefOfDeclareCursorStmt(n *DeclareCursorStmt) *DeclareCursorStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDefElem creates a deep clone of the input.
func CloneRefOfDefElem(n *DefElem) *DefElem { _ = "STUB: not implemented"; return nil }

// CloneRefOfDefineStmt creates a deep clone of the input.
func CloneRefOfDefineStmt(n *DefineStmt) *DefineStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfDeleteStmt creates a deep clone of the input.
func CloneRefOfDeleteStmt(n *DeleteStmt) *DeleteStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfDiscardStmt creates a deep clone of the input.
func CloneRefOfDiscardStmt(n *DiscardStmt) *DiscardStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfDoStmt creates a deep clone of the input.
func CloneRefOfDoStmt(n *DoStmt) *DoStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfDropOwnedStmt creates a deep clone of the input.
func CloneRefOfDropOwnedStmt(n *DropOwnedStmt) *DropOwnedStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDropReplicationSlotCmd creates a deep clone of the input.
func CloneRefOfDropReplicationSlotCmd(n *DropReplicationSlotCmd) *DropReplicationSlotCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDropRoleStmt creates a deep clone of the input.
func CloneRefOfDropRoleStmt(n *DropRoleStmt) *DropRoleStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfDropStmt creates a deep clone of the input.
func CloneRefOfDropStmt(n *DropStmt) *DropStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfDropTableSpaceStmt creates a deep clone of the input.
func CloneRefOfDropTableSpaceStmt(n *DropTableSpaceStmt) *DropTableSpaceStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDropUserMappingStmt creates a deep clone of the input.
func CloneRefOfDropUserMappingStmt(n *DropUserMappingStmt) *DropUserMappingStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfDropdbStmt creates a deep clone of the input.
func CloneRefOfDropdbStmt(n *DropdbStmt) *DropdbStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfExecuteStmt creates a deep clone of the input.
func CloneRefOfExecuteStmt(n *ExecuteStmt) *ExecuteStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfExplainStmt creates a deep clone of the input.
func CloneRefOfExplainStmt(n *ExplainStmt) *ExplainStmt { _ = "STUB: not implemented"; return nil }

// CloneExpr creates a deep clone of the input.
func CloneExpr(in Expr) Expr { _ = "STUB: not implemented"; return *new(Expr) }

// this should never happen

// CloneExpression creates a deep clone of the input.
func CloneExpression(in Expression) Expression { _ = "STUB: not implemented"; return *new(Expression) }

// this should never happen

// CloneRefOfFetchStmt creates a deep clone of the input.
func CloneRefOfFetchStmt(n *FetchStmt) *FetchStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfFieldSelect creates a deep clone of the input.
func CloneRefOfFieldSelect(n *FieldSelect) *FieldSelect { _ = "STUB: not implemented"; return nil }

// CloneRefOfFieldStore creates a deep clone of the input.
func CloneRefOfFieldStore(n *FieldStore) *FieldStore { _ = "STUB: not implemented"; return nil }

// CloneRefOfFloat creates a deep clone of the input.
func CloneRefOfFloat(n *Float) *Float { _ = "STUB: not implemented"; return nil }

// CloneRefOfFromExpr creates a deep clone of the input.
func CloneRefOfFromExpr(n *FromExpr) *FromExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfFuncCall creates a deep clone of the input.
func CloneRefOfFuncCall(n *FuncCall) *FuncCall { _ = "STUB: not implemented"; return nil }

// CloneRefOfFuncExpr creates a deep clone of the input.
func CloneRefOfFuncExpr(n *FuncExpr) *FuncExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfFunctionParameter creates a deep clone of the input.
func CloneRefOfFunctionParameter(n *FunctionParameter) *FunctionParameter {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfGrantRoleStmt creates a deep clone of the input.
func CloneRefOfGrantRoleStmt(n *GrantRoleStmt) *GrantRoleStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfGrantStmt creates a deep clone of the input.
func CloneRefOfGrantStmt(n *GrantStmt) *GrantStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfGroupingFunc creates a deep clone of the input.
func CloneRefOfGroupingFunc(n *GroupingFunc) *GroupingFunc { _ = "STUB: not implemented"; return nil }

// CloneRefOfGroupingSet creates a deep clone of the input.
func CloneRefOfGroupingSet(n *GroupingSet) *GroupingSet { _ = "STUB: not implemented"; return nil }

// CloneRefOfIdentifier creates a deep clone of the input.
func CloneRefOfIdentifier(n *Identifier) *Identifier { _ = "STUB: not implemented"; return nil }

// CloneRefOfIdentifySystemCmd creates a deep clone of the input.
func CloneRefOfIdentifySystemCmd(n *IdentifySystemCmd) *IdentifySystemCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfImportForeignSchemaStmt creates a deep clone of the input.
func CloneRefOfImportForeignSchemaStmt(n *ImportForeignSchemaStmt) *ImportForeignSchemaStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfIndexElem creates a deep clone of the input.
func CloneRefOfIndexElem(n *IndexElem) *IndexElem { _ = "STUB: not implemented"; return nil }

// CloneRefOfIndexStmt creates a deep clone of the input.
func CloneRefOfIndexStmt(n *IndexStmt) *IndexStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfInferClause creates a deep clone of the input.
func CloneRefOfInferClause(n *InferClause) *InferClause { _ = "STUB: not implemented"; return nil }

// CloneRefOfInferenceElem creates a deep clone of the input.
func CloneRefOfInferenceElem(n *InferenceElem) *InferenceElem {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfInsertStmt creates a deep clone of the input.
func CloneRefOfInsertStmt(n *InsertStmt) *InsertStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfInteger creates a deep clone of the input.
func CloneRefOfInteger(n *Integer) *Integer { _ = "STUB: not implemented"; return nil }

// CloneRefOfIntoClause creates a deep clone of the input.
func CloneRefOfIntoClause(n *IntoClause) *IntoClause { _ = "STUB: not implemented"; return nil }

// CloneRefOfJoinExpr creates a deep clone of the input.
func CloneRefOfJoinExpr(n *JoinExpr) *JoinExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonAggConstructor creates a deep clone of the input.
func CloneRefOfJsonAggConstructor(n *JsonAggConstructor) *JsonAggConstructor {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonArgument creates a deep clone of the input.
func CloneRefOfJsonArgument(n *JsonArgument) *JsonArgument { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonArrayAgg creates a deep clone of the input.
func CloneRefOfJsonArrayAgg(n *JsonArrayAgg) *JsonArrayAgg { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonArrayConstructor creates a deep clone of the input.
func CloneRefOfJsonArrayConstructor(n *JsonArrayConstructor) *JsonArrayConstructor {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonArrayQueryConstructor creates a deep clone of the input.
func CloneRefOfJsonArrayQueryConstructor(n *JsonArrayQueryConstructor) *JsonArrayQueryConstructor {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonBehavior creates a deep clone of the input.
func CloneRefOfJsonBehavior(n *JsonBehavior) *JsonBehavior { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonConstructorExpr creates a deep clone of the input.
func CloneRefOfJsonConstructorExpr(n *JsonConstructorExpr) *JsonConstructorExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonExpr creates a deep clone of the input.
func CloneRefOfJsonExpr(n *JsonExpr) *JsonExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonFormat creates a deep clone of the input.
func CloneRefOfJsonFormat(n *JsonFormat) *JsonFormat { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonFuncExpr creates a deep clone of the input.
func CloneRefOfJsonFuncExpr(n *JsonFuncExpr) *JsonFuncExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonIsPredicate creates a deep clone of the input.
func CloneRefOfJsonIsPredicate(n *JsonIsPredicate) *JsonIsPredicate {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonKeyValue creates a deep clone of the input.
func CloneRefOfJsonKeyValue(n *JsonKeyValue) *JsonKeyValue { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonObjectAgg creates a deep clone of the input.
func CloneRefOfJsonObjectAgg(n *JsonObjectAgg) *JsonObjectAgg {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonObjectConstructor creates a deep clone of the input.
func CloneRefOfJsonObjectConstructor(n *JsonObjectConstructor) *JsonObjectConstructor {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonOutput creates a deep clone of the input.
func CloneRefOfJsonOutput(n *JsonOutput) *JsonOutput { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonParseExpr creates a deep clone of the input.
func CloneRefOfJsonParseExpr(n *JsonParseExpr) *JsonParseExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonReturning creates a deep clone of the input.
func CloneRefOfJsonReturning(n *JsonReturning) *JsonReturning {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonScalarExpr creates a deep clone of the input.
func CloneRefOfJsonScalarExpr(n *JsonScalarExpr) *JsonScalarExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonSerializeExpr creates a deep clone of the input.
func CloneRefOfJsonSerializeExpr(n *JsonSerializeExpr) *JsonSerializeExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonTable creates a deep clone of the input.
func CloneRefOfJsonTable(n *JsonTable) *JsonTable { _ = "STUB: not implemented"; return nil }

// CloneRefOfJsonTableColumn creates a deep clone of the input.
func CloneRefOfJsonTableColumn(n *JsonTableColumn) *JsonTableColumn {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonTablePath creates a deep clone of the input.
func CloneRefOfJsonTablePath(n *JsonTablePath) *JsonTablePath {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonTablePathScan creates a deep clone of the input.
func CloneRefOfJsonTablePathScan(n *JsonTablePathScan) *JsonTablePathScan {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonTablePathSpec creates a deep clone of the input.
func CloneRefOfJsonTablePathSpec(n *JsonTablePathSpec) *JsonTablePathSpec {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonTablePlan creates a deep clone of the input.
func CloneRefOfJsonTablePlan(n *JsonTablePlan) *JsonTablePlan {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonTableSiblingJoin creates a deep clone of the input.
func CloneRefOfJsonTableSiblingJoin(n *JsonTableSiblingJoin) *JsonTableSiblingJoin {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfJsonValueExpr creates a deep clone of the input.
func CloneRefOfJsonValueExpr(n *JsonValueExpr) *JsonValueExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfKeyAction creates a deep clone of the input.
func CloneRefOfKeyAction(n *KeyAction) *KeyAction { _ = "STUB: not implemented"; return nil }

// CloneRefOfKeyActions creates a deep clone of the input.
func CloneRefOfKeyActions(n *KeyActions) *KeyActions { _ = "STUB: not implemented"; return nil }

// CloneRefOfListenStmt creates a deep clone of the input.
func CloneRefOfListenStmt(n *ListenStmt) *ListenStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfLoadStmt creates a deep clone of the input.
func CloneRefOfLoadStmt(n *LoadStmt) *LoadStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfLockStmt creates a deep clone of the input.
func CloneRefOfLockStmt(n *LockStmt) *LockStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfLockingClause creates a deep clone of the input.
func CloneRefOfLockingClause(n *LockingClause) *LockingClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfMergeAction creates a deep clone of the input.
func CloneRefOfMergeAction(n *MergeAction) *MergeAction { _ = "STUB: not implemented"; return nil }

// CloneRefOfMergeStmt creates a deep clone of the input.
func CloneRefOfMergeStmt(n *MergeStmt) *MergeStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfMergeSupportFunc creates a deep clone of the input.
func CloneRefOfMergeSupportFunc(n *MergeSupportFunc) *MergeSupportFunc {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfMergeWhenClause creates a deep clone of the input.
func CloneRefOfMergeWhenClause(n *MergeWhenClause) *MergeWhenClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfMinMaxExpr creates a deep clone of the input.
func CloneRefOfMinMaxExpr(n *MinMaxExpr) *MinMaxExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfMultiAssignRef creates a deep clone of the input.
func CloneRefOfMultiAssignRef(n *MultiAssignRef) *MultiAssignRef {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfNamedArgExpr creates a deep clone of the input.
func CloneRefOfNamedArgExpr(n *NamedArgExpr) *NamedArgExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfNextValueExpr creates a deep clone of the input.
func CloneRefOfNextValueExpr(n *NextValueExpr) *NextValueExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfNodeList creates a deep clone of the input.
func CloneRefOfNodeList(n *NodeList) *NodeList { _ = "STUB: not implemented"; return nil }

// CloneRefOfNotifyStmt creates a deep clone of the input.
func CloneRefOfNotifyStmt(n *NotifyStmt) *NotifyStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfNull creates a deep clone of the input.
func CloneRefOfNull(n *Null) *Null { _ = "STUB: not implemented"; return nil }

// CloneRefOfNullTest creates a deep clone of the input.
func CloneRefOfNullTest(n *NullTest) *NullTest { _ = "STUB: not implemented"; return nil }

// CloneRefOfObjectWithArgs creates a deep clone of the input.
func CloneRefOfObjectWithArgs(n *ObjectWithArgs) *ObjectWithArgs {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfOnConflictClause creates a deep clone of the input.
func CloneRefOfOnConflictClause(n *OnConflictClause) *OnConflictClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfOnConflictExpr creates a deep clone of the input.
func CloneRefOfOnConflictExpr(n *OnConflictExpr) *OnConflictExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfOpExpr creates a deep clone of the input.
func CloneRefOfOpExpr(n *OpExpr) *OpExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfPLAssignStmt creates a deep clone of the input.
func CloneRefOfPLAssignStmt(n *PLAssignStmt) *PLAssignStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfParam creates a deep clone of the input.
func CloneRefOfParam(n *Param) *Param { _ = "STUB: not implemented"; return nil }

// CloneRefOfParamRef creates a deep clone of the input.
func CloneRefOfParamRef(n *ParamRef) *ParamRef { _ = "STUB: not implemented"; return nil }

// CloneRefOfParenExpr creates a deep clone of the input.
func CloneRefOfParenExpr(n *ParenExpr) *ParenExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfPartitionBoundSpec creates a deep clone of the input.
func CloneRefOfPartitionBoundSpec(n *PartitionBoundSpec) *PartitionBoundSpec {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfPartitionCmd creates a deep clone of the input.
func CloneRefOfPartitionCmd(n *PartitionCmd) *PartitionCmd { _ = "STUB: not implemented"; return nil }

// CloneRefOfPartitionElem creates a deep clone of the input.
func CloneRefOfPartitionElem(n *PartitionElem) *PartitionElem {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfPartitionRangeDatum creates a deep clone of the input.
func CloneRefOfPartitionRangeDatum(n *PartitionRangeDatum) *PartitionRangeDatum {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfPartitionSpec creates a deep clone of the input.
func CloneRefOfPartitionSpec(n *PartitionSpec) *PartitionSpec {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfPrepareStmt creates a deep clone of the input.
func CloneRefOfPrepareStmt(n *PrepareStmt) *PrepareStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfPublicationObjSpec creates a deep clone of the input.
func CloneRefOfPublicationObjSpec(n *PublicationObjSpec) *PublicationObjSpec {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfPublicationTable creates a deep clone of the input.
func CloneRefOfPublicationTable(n *PublicationTable) *PublicationTable {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfQuery creates a deep clone of the input.
func CloneRefOfQuery(n *Query) *Query { _ = "STUB: not implemented"; return nil }

// CloneRefOfRTEPermissionInfo creates a deep clone of the input.
func CloneRefOfRTEPermissionInfo(n *RTEPermissionInfo) *RTEPermissionInfo {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeFunction creates a deep clone of the input.
func CloneRefOfRangeFunction(n *RangeFunction) *RangeFunction {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeSubselect creates a deep clone of the input.
func CloneRefOfRangeSubselect(n *RangeSubselect) *RangeSubselect {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeTableFunc creates a deep clone of the input.
func CloneRefOfRangeTableFunc(n *RangeTableFunc) *RangeTableFunc {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeTableFuncCol creates a deep clone of the input.
func CloneRefOfRangeTableFuncCol(n *RangeTableFuncCol) *RangeTableFuncCol {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeTableSample creates a deep clone of the input.
func CloneRefOfRangeTableSample(n *RangeTableSample) *RangeTableSample {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeTblEntry creates a deep clone of the input.
func CloneRefOfRangeTblEntry(n *RangeTblEntry) *RangeTblEntry {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeTblFunction creates a deep clone of the input.
func CloneRefOfRangeTblFunction(n *RangeTblFunction) *RangeTblFunction {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRangeTblRef creates a deep clone of the input.
func CloneRefOfRangeTblRef(n *RangeTblRef) *RangeTblRef { _ = "STUB: not implemented"; return nil }

// CloneRefOfRangeVar creates a deep clone of the input.
func CloneRefOfRangeVar(n *RangeVar) *RangeVar { _ = "STUB: not implemented"; return nil }

// CloneRefOfRawStmt creates a deep clone of the input.
func CloneRefOfRawStmt(n *RawStmt) *RawStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfReadReplicationSlotCmd creates a deep clone of the input.
func CloneRefOfReadReplicationSlotCmd(n *ReadReplicationSlotCmd) *ReadReplicationSlotCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfReassignOwnedStmt creates a deep clone of the input.
func CloneRefOfReassignOwnedStmt(n *ReassignOwnedStmt) *ReassignOwnedStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRefreshMatViewStmt creates a deep clone of the input.
func CloneRefOfRefreshMatViewStmt(n *RefreshMatViewStmt) *RefreshMatViewStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfReindexStmt creates a deep clone of the input.
func CloneRefOfReindexStmt(n *ReindexStmt) *ReindexStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfRelabelType creates a deep clone of the input.
func CloneRefOfRelabelType(n *RelabelType) *RelabelType { _ = "STUB: not implemented"; return nil }

// CloneRefOfRenameStmt creates a deep clone of the input.
func CloneRefOfRenameStmt(n *RenameStmt) *RenameStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfReplicaIdentityStmt creates a deep clone of the input.
func CloneRefOfReplicaIdentityStmt(n *ReplicaIdentityStmt) *ReplicaIdentityStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfResTarget creates a deep clone of the input.
func CloneRefOfResTarget(n *ResTarget) *ResTarget { _ = "STUB: not implemented"; return nil }

// CloneRefOfReturnStmt creates a deep clone of the input.
func CloneRefOfReturnStmt(n *ReturnStmt) *ReturnStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfRoleSpec creates a deep clone of the input.
func CloneRefOfRoleSpec(n *RoleSpec) *RoleSpec { _ = "STUB: not implemented"; return nil }

// CloneRootNode creates a deep clone of the input.
func CloneRootNode(n RootNode) RootNode { _ = "STUB: not implemented"; return *new(RootNode) }

// CloneRefOfRowCompareExpr creates a deep clone of the input.
func CloneRefOfRowCompareExpr(n *RowCompareExpr) *RowCompareExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRowExpr creates a deep clone of the input.
func CloneRefOfRowExpr(n *RowExpr) *RowExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfRowMarkClause creates a deep clone of the input.
func CloneRefOfRowMarkClause(n *RowMarkClause) *RowMarkClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfRuleStmt creates a deep clone of the input.
func CloneRefOfRuleStmt(n *RuleStmt) *RuleStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfSQLValueFunction creates a deep clone of the input.
func CloneRefOfSQLValueFunction(n *SQLValueFunction) *SQLValueFunction {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfScalarArrayOpExpr creates a deep clone of the input.
func CloneRefOfScalarArrayOpExpr(n *ScalarArrayOpExpr) *ScalarArrayOpExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfSecLabelStmt creates a deep clone of the input.
func CloneRefOfSecLabelStmt(n *SecLabelStmt) *SecLabelStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfSelectStmt creates a deep clone of the input.
func CloneRefOfSelectStmt(n *SelectStmt) *SelectStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfSetOperationStmt creates a deep clone of the input.
func CloneRefOfSetOperationStmt(n *SetOperationStmt) *SetOperationStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfSetToDefault creates a deep clone of the input.
func CloneRefOfSetToDefault(n *SetToDefault) *SetToDefault { _ = "STUB: not implemented"; return nil }

// CloneRefOfSinglePartitionSpec creates a deep clone of the input.
func CloneRefOfSinglePartitionSpec(n *SinglePartitionSpec) *SinglePartitionSpec {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfSortBy creates a deep clone of the input.
func CloneRefOfSortBy(n *SortBy) *SortBy { _ = "STUB: not implemented"; return nil }

// CloneRefOfSortGroupClause creates a deep clone of the input.
func CloneRefOfSortGroupClause(n *SortGroupClause) *SortGroupClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfStartReplicationCmd creates a deep clone of the input.
func CloneRefOfStartReplicationCmd(n *StartReplicationCmd) *StartReplicationCmd {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfStatsElem creates a deep clone of the input.
func CloneRefOfStatsElem(n *StatsElem) *StatsElem { _ = "STUB: not implemented"; return nil }

// CloneStmt creates a deep clone of the input.
func CloneStmt(in Stmt) Stmt { _ = "STUB: not implemented"; return *new(Stmt) }

// this should never happen

// CloneRefOfString creates a deep clone of the input.
func CloneRefOfString(n *String) *String { _ = "STUB: not implemented"; return nil }

// CloneRefOfSubLink creates a deep clone of the input.
func CloneRefOfSubLink(n *SubLink) *SubLink { _ = "STUB: not implemented"; return nil }

// CloneRefOfSubPlan creates a deep clone of the input.
func CloneRefOfSubPlan(n *SubPlan) *SubPlan { _ = "STUB: not implemented"; return nil }

// CloneRefOfSubscriptingRef creates a deep clone of the input.
func CloneRefOfSubscriptingRef(n *SubscriptingRef) *SubscriptingRef {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfTableFunc creates a deep clone of the input.
func CloneRefOfTableFunc(n *TableFunc) *TableFunc { _ = "STUB: not implemented"; return nil }

// CloneRefOfTableLikeClause creates a deep clone of the input.
func CloneRefOfTableLikeClause(n *TableLikeClause) *TableLikeClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfTableSampleClause creates a deep clone of the input.
func CloneRefOfTableSampleClause(n *TableSampleClause) *TableSampleClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfTargetEntry creates a deep clone of the input.
func CloneRefOfTargetEntry(n *TargetEntry) *TargetEntry { _ = "STUB: not implemented"; return nil }

// CloneRefOfTransactionStmt creates a deep clone of the input.
func CloneRefOfTransactionStmt(n *TransactionStmt) *TransactionStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfTriggerTransition creates a deep clone of the input.
func CloneRefOfTriggerTransition(n *TriggerTransition) *TriggerTransition {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfTruncateStmt creates a deep clone of the input.
func CloneRefOfTruncateStmt(n *TruncateStmt) *TruncateStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfTypeCast creates a deep clone of the input.
func CloneRefOfTypeCast(n *TypeCast) *TypeCast { _ = "STUB: not implemented"; return nil }

// CloneRefOfTypeName creates a deep clone of the input.
func CloneRefOfTypeName(n *TypeName) *TypeName { _ = "STUB: not implemented"; return nil }

// CloneRefOfUnlistenStmt creates a deep clone of the input.
func CloneRefOfUnlistenStmt(n *UnlistenStmt) *UnlistenStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfUpdateStmt creates a deep clone of the input.
func CloneRefOfUpdateStmt(n *UpdateStmt) *UpdateStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfVacuumRelation creates a deep clone of the input.
func CloneRefOfVacuumRelation(n *VacuumRelation) *VacuumRelation {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfVacuumStmt creates a deep clone of the input.
func CloneRefOfVacuumStmt(n *VacuumStmt) *VacuumStmt { _ = "STUB: not implemented"; return nil }

// CloneValue creates a deep clone of the input.
func CloneValue(in Value) Value { _ = "STUB: not implemented"; return *new(Value) }

// this should never happen

// CloneRefOfVar creates a deep clone of the input.
func CloneRefOfVar(n *Var) *Var { _ = "STUB: not implemented"; return nil }

// CloneRefOfVariableSetStmt creates a deep clone of the input.
func CloneRefOfVariableSetStmt(n *VariableSetStmt) *VariableSetStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfVariableShowStmt creates a deep clone of the input.
func CloneRefOfVariableShowStmt(n *VariableShowStmt) *VariableShowStmt {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfViewStmt creates a deep clone of the input.
func CloneRefOfViewStmt(n *ViewStmt) *ViewStmt { _ = "STUB: not implemented"; return nil }

// CloneRefOfWindowClause creates a deep clone of the input.
func CloneRefOfWindowClause(n *WindowClause) *WindowClause { _ = "STUB: not implemented"; return nil }

// CloneRefOfWindowDef creates a deep clone of the input.
func CloneRefOfWindowDef(n *WindowDef) *WindowDef { _ = "STUB: not implemented"; return nil }

// CloneRefOfWindowFunc creates a deep clone of the input.
func CloneRefOfWindowFunc(n *WindowFunc) *WindowFunc { _ = "STUB: not implemented"; return nil }

// CloneRefOfWindowFuncRunCondition creates a deep clone of the input.
func CloneRefOfWindowFuncRunCondition(n *WindowFuncRunCondition) *WindowFuncRunCondition {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfWithCheckOption creates a deep clone of the input.
func CloneRefOfWithCheckOption(n *WithCheckOption) *WithCheckOption {
	_ = "STUB: not implemented"
	return nil
}

// CloneRefOfWithClause creates a deep clone of the input.
func CloneRefOfWithClause(n *WithClause) *WithClause { _ = "STUB: not implemented"; return nil }

// CloneRefOfXmlExpr creates a deep clone of the input.
func CloneRefOfXmlExpr(n *XmlExpr) *XmlExpr { _ = "STUB: not implemented"; return nil }

// CloneRefOfXmlSerialize creates a deep clone of the input.
func CloneRefOfXmlSerialize(n *XmlSerialize) *XmlSerialize { _ = "STUB: not implemented"; return nil }

// CloneBaseNode creates a deep clone of the input.
func CloneBaseNode(n BaseNode) BaseNode { _ = "STUB: not implemented"; return *new(BaseNode) }

// CloneBaseExpr creates a deep clone of the input.
func CloneBaseExpr(n BaseExpr) BaseExpr { _ = "STUB: not implemented"; return *new(BaseExpr) }

// CloneSliceOfOid creates a deep clone of the input.
func CloneSliceOfOid(n []Oid) []Oid { _ = "STUB: not implemented"; return nil }

// CloneSliceOfRefOfDefElem creates a deep clone of the input.
func CloneSliceOfRefOfDefElem(n []*DefElem) []*DefElem { _ = "STUB: not implemented"; return nil }

// CloneSliceOfExpression creates a deep clone of the input.
func CloneSliceOfExpression(n []Expression) []Expression { _ = "STUB: not implemented"; return nil }

// CloneSliceOfInt32 creates a deep clone of the input.
func CloneSliceOfInt32(n []int32) []int32 { _ = "STUB: not implemented"; return nil }

// CloneSliceOfRefOfConstraint creates a deep clone of the input.
func CloneSliceOfRefOfConstraint(n []*Constraint) []*Constraint {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfAttrNumber creates a deep clone of the input.
func CloneSliceOfAttrNumber(n []AttrNumber) []AttrNumber { _ = "STUB: not implemented"; return nil }

// CloneSliceOfString creates a deep clone of the input.
func CloneSliceOfString(n []string) []string { _ = "STUB: not implemented"; return nil }

// CloneSliceOfRefOfTargetEntry creates a deep clone of the input.
func CloneSliceOfRefOfTargetEntry(n []*TargetEntry) []*TargetEntry {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfRefOfResTarget creates a deep clone of the input.
func CloneSliceOfRefOfResTarget(n []*ResTarget) []*ResTarget { _ = "STUB: not implemented"; return nil }

// CloneSliceOfNode creates a deep clone of the input.
func CloneSliceOfNode(n []Node) []Node { _ = "STUB: not implemented"; return nil }

// CloneSliceOfRefOfCommonTableExpr creates a deep clone of the input.
func CloneSliceOfRefOfCommonTableExpr(n []*CommonTableExpr) []*CommonTableExpr {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfRefOfRangeTblEntry creates a deep clone of the input.
func CloneSliceOfRefOfRangeTblEntry(n []*RangeTblEntry) []*RangeTblEntry {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfRefOfSortGroupClause creates a deep clone of the input.
func CloneSliceOfRefOfSortGroupClause(n []*SortGroupClause) []*SortGroupClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfRefOfWindowClause creates a deep clone of the input.
func CloneSliceOfRefOfWindowClause(n []*WindowClause) []*WindowClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfRefOfRowMarkClause creates a deep clone of the input.
func CloneSliceOfRefOfRowMarkClause(n []*RowMarkClause) []*RowMarkClause {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfInt creates a deep clone of the input.
func CloneSliceOfInt(n []int) []int { _ = "STUB: not implemented"; return nil }

// CloneSliceOfRefOfRangeTblFunction creates a deep clone of the input.
func CloneSliceOfRefOfRangeTblFunction(n []*RangeTblFunction) []*RangeTblFunction {
	_ = "STUB: not implemented"
	return nil
}

// CloneSliceOfRefOfNodeList creates a deep clone of the input.
func CloneSliceOfRefOfNodeList(n []*NodeList) []*NodeList { _ = "STUB: not implemented"; return nil }

// CloneRefOfRootNode creates a deep clone of the input.
func CloneRefOfRootNode(n *RootNode) *RootNode { _ = "STUB: not implemented"; return nil }

// CloneSliceOfBool creates a deep clone of the input.
func CloneSliceOfBool(n []bool) []bool { _ = "STUB: not implemented"; return nil }
