// PostgreSQL Database Management System
// (also known as Postgres, formerly known as Postgres95)
//
//	Portions Copyright (c) 2025, Supabase, Inc
//
//	Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//
//	Portions Copyright (c) 1994, The Regents of the University of California
//
// Permission to use, copy, modify, and distribute this software and its
// documentation for any purpose, without fee, and without a written agreement
// is hereby granted, provided that the above copyright notice and this
// paragraph and the following two paragraphs appear in all copies.
//
// IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
// DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
// LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
// DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
// ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
// PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
package ast

// ==============================================================================
// DDL FRAMEWORK - PostgreSQL parsenodes.h DDL implementation
// Ported from postgres/src/include/nodes/parsenodes.h
// ==============================================================================

// Supporting enums and types for DDL statements

// ObjectType represents the type of database object - ported from postgres/src/include/nodes/parsenodes.h:2256-2310
type ObjectType int

const (
	OBJECT_ACCESS_METHOD ObjectType = iota
	OBJECT_AGGREGATE
	OBJECT_AMOP
	OBJECT_AMPROC
	OBJECT_ATTRIBUTE // type's attribute, when distinct from column
	OBJECT_CAST
	OBJECT_COLUMN
	OBJECT_COLLATION
	OBJECT_CONVERSION
	OBJECT_DATABASE
	OBJECT_DEFAULT
	OBJECT_DEFACL
	OBJECT_DOMAIN
	OBJECT_DOMCONSTRAINT
	OBJECT_EVENT_TRIGGER
	OBJECT_EXTENSION
	OBJECT_FDW
	OBJECT_FOREIGN_SERVER
	OBJECT_FOREIGN_TABLE
	OBJECT_FUNCTION
	OBJECT_INDEX
	OBJECT_LANGUAGE
	OBJECT_LARGEOBJECT
	OBJECT_MATVIEW
	OBJECT_OPCLASS
	OBJECT_OPERATOR
	OBJECT_OPFAMILY
	OBJECT_PARAMETER_ACL
	OBJECT_POLICY
	OBJECT_PROCEDURE
	OBJECT_PUBLICATION
	OBJECT_PUBLICATION_NAMESPACE
	OBJECT_PUBLICATION_REL
	OBJECT_ROLE
	OBJECT_ROUTINE
	OBJECT_RULE
	OBJECT_SCHEMA
	OBJECT_SEQUENCE
	OBJECT_SUBSCRIPTION
	OBJECT_STATISTIC_EXT
	OBJECT_TABCONSTRAINT
	OBJECT_TABLE
	OBJECT_TABLESPACE
	OBJECT_TRANSFORM
	OBJECT_TRIGGER
	OBJECT_TSCONFIGURATION
	OBJECT_TSDICTIONARY
	OBJECT_TSPARSER
	OBJECT_TSTEMPLATE
	OBJECT_TYPE
	OBJECT_USER_MAPPING
	OBJECT_VIEW
)

func (o ObjectType) String() string { _ = "STUB: not implemented"; return "" }

// DropBehavior represents CASCADE/RESTRICT behavior - ported from postgres/src/include/nodes/parsenodes.h:2329-2333
type DropBehavior int

const (
	DropRestrict DropBehavior = iota // drop fails if any dependent objects
	DropCascade                      // remove dependent objects too
)

func (d DropBehavior) String() string { _ = "STUB: not implemented"; return "" }

// ConstrType represents types of constraints - ported from postgres/src/include/nodes/parsenodes.h:2697-2714
type ConstrType int

const (
	CONSTR_NULL ConstrType = iota // not standard SQL, but expected
	CONSTR_NOTNULL
	CONSTR_DEFAULT
	CONSTR_IDENTITY
	CONSTR_GENERATED
	CONSTR_CHECK
	CONSTR_PRIMARY
	CONSTR_UNIQUE
	CONSTR_EXCLUSION
	CONSTR_FOREIGN
	CONSTR_ATTR_DEFERRABLE // attributes for previous constraint node
	CONSTR_ATTR_NOT_DEFERRABLE
	CONSTR_ATTR_DEFERRED
	CONSTR_ATTR_IMMEDIATE
)

// Identity generation constants - ported from postgres/src/include/catalog/pg_attribute.h:233-234
const (
	ATTRIBUTE_IDENTITY_ALWAYS     byte = 'a' // GENERATED ALWAYS AS IDENTITY
	ATTRIBUTE_IDENTITY_BY_DEFAULT byte = 'd' // GENERATED BY DEFAULT AS IDENTITY
)

// Constraint Attribute Specification (CAS) bitmask constants
// Ported from postgres/src/include/parser/parse_node.h:46-52
const (
	CAS_NOT_DEFERRABLE      int = 0x01
	CAS_DEFERRABLE          int = 0x02
	CAS_INITIALLY_IMMEDIATE int = 0x04
	CAS_INITIALLY_DEFERRED  int = 0x08
	CAS_NOT_VALID           int = 0x10
	CAS_NO_INHERIT          int = 0x20
)

// Foreign Key Constraint Match Types
// Ported from postgres/src/include/nodes/parsenodes.h:2665-2667
const (
	FKCONSTR_MATCH_FULL    byte = 'f' // MATCH FULL
	FKCONSTR_MATCH_PARTIAL byte = 'p' // MATCH PARTIAL
	FKCONSTR_MATCH_SIMPLE  byte = 's' // MATCH SIMPLE (default)
)

// Replica Identity Types
// Ported from postgres/src/include/catalog/pg_class.h
const (
	REPLICA_IDENTITY_DEFAULT rune = 'd' // Use primary key
	REPLICA_IDENTITY_NOTHING rune = 'n' // No replica identity
	REPLICA_IDENTITY_FULL    rune = 'f' // Full row is replica identity
	REPLICA_IDENTITY_INDEX   rune = 'i' // Use specific index
)

// Foreign Key Constraint Action Types
// Ported from postgres/src/include/nodes/parsenodes.h:2670-2674
const (
	FKCONSTR_ACTION_NOACTION   byte = 'a' // NO ACTION
	FKCONSTR_ACTION_RESTRICT   byte = 'r' // RESTRICT
	FKCONSTR_ACTION_CASCADE    byte = 'c' // CASCADE
	FKCONSTR_ACTION_SETNULL    byte = 'n' // SET NULL
	FKCONSTR_ACTION_SETDEFAULT byte = 'd' // SET DEFAULT
)

// KeyAction represents a foreign key action with optional column list
// Ported from postgres/src/backend/parser/gram.y:142-146
type KeyAction struct {
	BaseNode
	Action byte      // FKCONSTR_ACTION_* constant
	Cols   *NodeList // optional column list for SET NULL/SET DEFAULT
}

// KeyActions represents both update and delete actions for foreign keys
// Ported from postgres/src/backend/parser/gram.y:148-152
type KeyActions struct {
	BaseNode
	UpdateAction *KeyAction
	DeleteAction *KeyAction
}

// SqlString returns the SQL representation of KeyAction
func (ka *KeyAction) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add column list if present (only valid for SET NULL and SET DEFAULT)

func (c ConstrType) String() string { _ = "STUB: not implemented"; return "" }

// ViewCheckOption represents WITH CHECK OPTION - ported from postgres/src/include/nodes/parsenodes.h:3773-3777
type ViewCheckOption int

const (
	NO_CHECK_OPTION ViewCheckOption = iota
	LOCAL_CHECK_OPTION
	CASCADED_CHECK_OPTION
)

func (v ViewCheckOption) String() string { _ = "STUB: not implemented"; return "" }

// AlterTableType represents types of ALTER TABLE operations - ported from postgres/src/include/nodes/parsenodes.h:2348-2417
type AlterTableType int

const (
	AT_AddColumn                 AlterTableType = iota // add column
	AT_AddColumnToView                                 // implicitly via CREATE OR REPLACE VIEW
	AT_ColumnDefault                                   // alter column default
	AT_CookedColumnDefault                             // add a pre-cooked column default
	AT_DropNotNull                                     // alter column drop not null
	AT_SetNotNull                                      // alter column set not null
	AT_SetExpression                                   // alter column set expression
	AT_DropExpression                                  // alter column drop expression
	AT_CheckNotNull                                    // check column is already not null
	AT_SetStatistics                                   // alter column set statistics
	AT_SetOptions                                      // alter column set (options)
	AT_ResetOptions                                    // alter column reset (options)
	AT_SetStorage                                      // alter column set storage
	AT_SetCompression                                  // alter column set compression
	AT_DropColumn                                      // drop column
	AT_AddIndex                                        // add index
	AT_ReAddIndex                                      // internal to commands/tablecmds.c
	AT_AddConstraint                                   // add constraint
	AT_AddConstraintRecurse                            // internal to commands/tablecmds.c
	AT_ReAddConstraint                                 // internal to commands/tablecmds.c
	AT_ReAddDomainConstraint                           // internal to commands/tablecmds.c
	AT_AlterConstraint                                 // alter constraint
	AT_ValidateConstraint                              // validate constraint
	AT_AddIndexConstraint                              // add constraint using existing index
	AT_DropConstraint                                  // drop constraint
	AT_ReAddComment                                    // internal to commands/tablecmds.c
	AT_AlterColumnType                                 // alter column type
	AT_AlterColumnGenericOptions                       // alter column OPTIONS (...)
	AT_ChangeOwner                                     // change owner
	AT_ClusterOn                                       // CLUSTER ON
	AT_DropCluster                                     // SET WITHOUT CLUSTER
	AT_SetLogged                                       // SET LOGGED
	AT_SetUnLogged                                     // SET UNLOGGED
	AT_DropOids                                        // SET WITHOUT OIDS
	AT_SetAccessMethod                                 // SET ACCESS METHOD
	AT_SetTableSpace                                   // SET TABLESPACE
	AT_SetRelOptions                                   // SET (...)
	AT_ResetRelOptions                                 // RESET (...)
	AT_ReplaceRelOptions                               // replace reloption list in its entirety
	AT_EnableTrig                                      // ENABLE TRIGGER name
	AT_EnableAlwaysTrig                                // ENABLE ALWAYS TRIGGER name
	AT_EnableReplicaTrig                               // ENABLE REPLICA TRIGGER name
	AT_DisableTrig                                     // DISABLE TRIGGER name
	AT_EnableTrigAll                                   // ENABLE TRIGGER ALL
	AT_DisableTrigAll                                  // DISABLE TRIGGER ALL
	AT_EnableTrigUser                                  // ENABLE TRIGGER USER
	AT_DisableTrigUser                                 // DISABLE TRIGGER USER
	AT_EnableRule                                      // ENABLE RULE name
	AT_EnableAlwaysRule                                // ENABLE ALWAYS RULE name
	AT_EnableReplicaRule                               // ENABLE REPLICA RULE name
	AT_DisableRule                                     // DISABLE RULE name
	AT_AddInherit                                      // INHERIT parent
	AT_DropInherit                                     // NO INHERIT parent
	AT_AddOf                                           // OF <type_name>
	AT_DropOf                                          // NOT OF
	AT_ReplicaIdentity                                 // REPLICA IDENTITY
	AT_EnableRowSecurity                               // ENABLE ROW SECURITY
	AT_DisableRowSecurity                              // DISABLE ROW SECURITY
	AT_ForceRowSecurity                                // FORCE ROW SECURITY
	AT_NoForceRowSecurity                              // NO FORCE ROW SECURITY
	AT_GenericOptions                                  // OPTIONS (...)
	AT_AttachPartition                                 // ATTACH PARTITION
	AT_DetachPartition                                 // DETACH PARTITION
	AT_DetachPartitionFinalize                         // DETACH PARTITION ... FINALIZE
	AT_AddIdentity                                     // ADD IDENTITY
	AT_SetIdentity                                     // SET identity column options
	AT_DropIdentity                                    // DROP IDENTITY
	AT_ReAddStatistics                                 // internal to commands/tablecmds.c
)

func (a AlterTableType) String() string { _ = "STUB: not implemented"; return "" }

// DefElemAction represents actions for DefElem - ported from postgres/src/include/nodes/parsenodes.h:803-809
type DefElemAction int

const (
	DEFELEM_UNSPEC DefElemAction = iota // no action given
	DEFELEM_SET                         // SET
	DEFELEM_ADD                         // ADD
	DEFELEM_DROP                        // DROP
)

func (d DefElemAction) String() string { _ = "STUB: not implemented"; return "" }

// SortByDir represents sort direction - ported from postgres/src/include/nodes/parsenodes.h:57-62
type SortByDir int

const (
	SORTBY_DEFAULT SortByDir = iota
	SORTBY_ASC
	SORTBY_DESC
	SORTBY_USING // not used in indexes
)

func (s SortByDir) String() string { _ = "STUB: not implemented"; return "" }

// SortByNulls represents null ordering - ported from postgres/src/include/nodes/parsenodes.h:64-69
type SortByNulls int

const (
	SORTBY_NULLS_DEFAULT SortByNulls = iota
	SORTBY_NULLS_FIRST
	SORTBY_NULLS_LAST
)

func (s SortByNulls) String() string { _ = "STUB: not implemented"; return "" }

// RoleSpecType represents types of role specifications - ported from postgres/src/include/nodes/parsenodes.h:383-389
type RoleSpecType int

const (
	ROLESPEC_CSTRING      RoleSpecType = iota // role name is stored as a C string
	ROLESPEC_CURRENT_ROLE                     // role spec is CURRENT_ROLE
	ROLESPEC_CURRENT_USER                     // role spec is CURRENT_USER
	ROLESPEC_SESSION_USER                     // role spec is SESSION_USER
	ROLESPEC_PUBLIC                           // role name is "public"
)

func (r RoleSpecType) String() string { _ = "STUB: not implemented"; return "" }

// RoleSpec represents a role specification.
// Ported from postgres/src/include/nodes/parsenodes.h:401
type RoleSpec struct {
	BaseNode
	Roletype RoleSpecType // Type of this rolespec - postgres/src/include/nodes/parsenodes.h:403
	Rolename string       // filled only for ROLESPEC_CSTRING - postgres/src/include/nodes/parsenodes.h:404
}

// NewRoleSpec creates a new RoleSpec node.
func NewRoleSpec(roletype RoleSpecType, rolename string) *RoleSpec {
	_ = "STUB: not implemented"
	return nil
}

func (r *RoleSpec) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of the role specification
func (r *RoleSpec) SqlString() string { _ = "STUB: not implemented"; return "" }

// ==============================================================================
// CORE DDL SUPPORTING STRUCTURES
// ==============================================================================

// TypeName represents a type name specification.
// This is a placeholder implementation - full TypeName from parsenodes.h will be implemented later
type TypeName struct {
	BaseNode
	Names       *NodeList // qualified name (list of String)
	TypeOid     Oid       // type's OID (filled in by transformTypeName)
	Setof       bool      // is a set?
	PctType     bool      // %TYPE specified?
	Typmods     *NodeList // type modifier expression(s)
	Typemod     int32     // prespecified type modifier
	ArrayBounds *NodeList // array bounds
}

// stringsToNodeList converts a slice of strings to a NodeList of String nodes
func stringsToNodeList(names []string) *NodeList { _ = "STUB: not implemented"; return nil }

// nodeListToStrings converts a NodeList of String nodes back to a slice of strings
func nodeListToStrings(nodeList *NodeList) []string { _ = "STUB: not implemented"; return nil }

// GetNames returns the Names as a slice of strings for testing purposes
func (t *TypeName) GetNames() []string { _ = "STUB: not implemented"; return nil }

// GetKeys returns the Keys as a slice of strings for testing purposes
func (c *Constraint) GetKeys() []string { _ = "STUB: not implemented"; return nil }

// GetIncluding returns the Including as a slice of strings for testing purposes
func (c *Constraint) GetIncluding() []string { _ = "STUB: not implemented"; return nil }

// GetFkAttrs returns the FkAttrs as a slice of strings for testing purposes
func (c *Constraint) GetFkAttrs() []string { _ = "STUB: not implemented"; return nil }

// GetPkAttrs returns the PkAttrs as a slice of strings for testing purposes
func (c *Constraint) GetPkAttrs() []string { _ = "STUB: not implemented"; return nil }

// GetFkDelSetCols returns the FkDelSetCols as a slice of strings for testing purposes
func (c *Constraint) GetFkDelSetCols() []string { _ = "STUB: not implemented"; return nil }

// NewTypeName creates a new TypeName node.
func NewTypeName(names []string) *TypeName { _ = "STUB: not implemented"; return nil }

func (t *TypeName) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of the TypeName
// normalizeTypeName converts PostgreSQL internal type names to standard SQL type names
func normalizeTypeName(nameParts []string) string { _ = "STUB: not implemented"; return "" }

// For qualified names, handle schema qualification

// Strip pg_catalog or public schema for built-in types only

// For other qualified names, quote each part individually if needed

// For single names, normalize if it's a built-in type

// isBuiltInType checks if a type name is a built-in PostgreSQL type
func isBuiltInType(typeName string) bool { _ = "STUB: not implemented"; return false }

func normalizeSingleTypeName(typeName string) string {
	_ = "STUB: not implemented"
	// Map PostgreSQL internal names to standard SQL names
	return ""
}

// pg_catalog."char" is a one-byte ad-hoc type distinct from bpchar/CHAR;
// preserve the quoting so it does not collapse to bpchar(1) on the wire.

// intervalMaskToString converts an interval mask to its string representation
func intervalMaskToString(mask int) string { _ = "STUB: not implemented"; return "" }

// Special marker for precision-only intervals

func (t *TypeName) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add SETOF prefix if present

// Collect name parts from the NodeList

// `col%TYPE` references the type of an existing column. The qualified name is
// kept verbatim (not alias-normalized) with the %TYPE suffix.

// Use normalizeTypeName to handle both single and qualified names

// Add type modifiers if present

// Special handling for INTERVAL types

// Skip the INTERVAL_FULL_RANGE (first modifier) and only include the precision (second modifier)

// Convert interval mask to text representation

// For specific units like "minute to second", use that instead of numeric

// Add precision if present as second parameter

// Skip the normal modifier processing since we handled it above

// Fallback to regular handling for unrecognized masks

// Regular handling if first modifier is not an Integer

// Regular handling for non-INTERVAL types

// Add array bounds if present

// CollateClause represents a COLLATE clause.
// This is a placeholder implementation - full CollateClause from parsenodes.h will be implemented later
type CollateClause struct {
	BaseNode
	Arg      Node      // input expression
	Collname *NodeList // possibly-qualified collation name
}

// NewCollateClause creates a new CollateClause node.
func NewCollateClause(collname *NodeList) *CollateClause { _ = "STUB: not implemented"; return nil }

func (c *CollateClause) String() string { _ = "STUB: not implemented"; return "" }

// Get the last element (unqualified name)

// SqlString generates SQL representation of a COLLATE clause
func (c *CollateClause) SqlString() string {
	_ = "STUB: not implemented"

	// Add the expression if present
	return ""
}

// Add COLLATE and collation name

// Use QuoteIdentifier to properly handle identifier quoting

// ==============================================================================

// DefElem represents a generic name/value pair for options.
// Ported from postgres/src/include/nodes/parsenodes.h:811
type DefElem struct {
	BaseNode
	Defnamespace string        // NULL if unqualified name - postgres/src/include/nodes/parsenodes.h:813
	Defname      string        // postgres/src/include/nodes/parsenodes.h:814
	Arg          Node          // typically Integer, Float, String, or TypeName - postgres/src/include/nodes/parsenodes.h:815
	Defaction    DefElemAction // unspecified action, or SET/ADD/DROP - postgres/src/include/nodes/parsenodes.h:816
}

// NewDefElem creates a new DefElem node.
func NewDefElem(defname string, arg Node) *DefElem { _ = "STUB: not implemented"; return nil }

// NewDefElemExtended creates a new DefElem node with a qualified name.
func NewDefElemExtended(defnamespace, defname string, arg Node, action DefElemAction) *DefElem {
	_ = "STUB: not implemented"
	return nil
}

func (d *DefElem) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of DefElem
func (d *DefElem) SqlString() string { _ = "STUB: not implemented"; return "" }

// A namespace qualifies the option (e.g. the toast.* storage parameters);
// dropping it would collide with the un-namespaced option of the same name.

// SqlStringForFunction returns the SQL representation of DefElem for function options
// This handles the special formatting needed for ALTER FUNCTION statements
func (d *DefElem) SqlStringForFunction() string { _ = "STUB: not implemented"; return "" }

// For SUPPORT, we want the unquoted function name

// Handle qualified names like schema.func_name

// Handle SET/RESET operations via FunctionSetResetClause

// For other options, fall back to the standard format

// Fallback for cases where Arg is nil or doesn't match expected type

// Constraint represents a constraint definition.
// Ported from postgres/src/include/nodes/parsenodes.h:2728
type Constraint struct {
	BaseNode
	Contype            ConstrType // see above - postgres/src/include/nodes/parsenodes.h:2731
	Conname            string     // Constraint name, or NULL if unnamed - postgres/src/include/nodes/parsenodes.h:2732
	Deferrable         bool       // DEFERRABLE? - postgres/src/include/nodes/parsenodes.h:2733
	Initdeferred       bool       // INITIALLY DEFERRED? - postgres/src/include/nodes/parsenodes.h:2734
	SkipValidation     bool       // skip validation of existing rows? - postgres/src/include/nodes/parsenodes.h:2735
	InitiallyValid     bool       // mark the new constraint as valid? - postgres/src/include/nodes/parsenodes.h:2736
	IsNoInherit        bool       // is constraint non-inheritable? - postgres/src/include/nodes/parsenodes.h:2737
	RawExpr            Node       // CHECK or DEFAULT expression, as untransformed parse tree - postgres/src/include/nodes/parsenodes.h:2738
	CookedExpr         string     // CHECK or DEFAULT expression, as nodeToString representation - postgres/src/include/nodes/parsenodes.h:2740
	GeneratedWhen      byte       // ALWAYS or BY DEFAULT - postgres/src/include/nodes/parsenodes.h:2742
	Inhcount           int        // initial inheritance count to apply - postgres/src/include/nodes/parsenodes.h:2743
	NullsNotDistinct   bool       // null treatment for UNIQUE constraints - postgres/src/include/nodes/parsenodes.h:2744
	Keys               *NodeList  // String nodes naming referenced key column(s) - postgres/src/include/nodes/parsenodes.h:2746
	Including          *NodeList  // String nodes naming referenced nonkey column(s) - postgres/src/include/nodes/parsenodes.h:2747
	Exclusions         *NodeList  // list of (IndexElem, operator name) pairs - postgres/src/include/nodes/parsenodes.h:2748
	Options            *NodeList  // options from WITH clause - postgres/src/include/nodes/parsenodes.h:2749
	Indexname          string     // existing index to use; otherwise NULL - postgres/src/include/nodes/parsenodes.h:2750
	Indexspace         string     // index tablespace; NULL for default - postgres/src/include/nodes/parsenodes.h:2751
	ResetDefaultTblspc bool       // reset default_tablespace prior to creating the index - postgres/src/include/nodes/parsenodes.h:2752
	AccessMethod       string     // access method to use for the index - postgres/src/include/nodes/parsenodes.h:2753
	WhereClause        Node       // partial index predicate - postgres/src/include/nodes/parsenodes.h:2754
	Pktable            *RangeVar  // Primary key table for FOREIGN KEY - postgres/src/include/nodes/parsenodes.h:2755
	FkAttrs            *NodeList  // Attributes of foreign key - postgres/src/include/nodes/parsenodes.h:2756
	PkAttrs            *NodeList  // Corresponding attrs in PK table - postgres/src/include/nodes/parsenodes.h:2757
	FkMatchtype        byte       // FULL, PARTIAL, SIMPLE - postgres/src/include/nodes/parsenodes.h:2758
	FkUpdAction        byte       // ON UPDATE action - postgres/src/include/nodes/parsenodes.h:2759
	FkDelAction        byte       // ON DELETE action - postgres/src/include/nodes/parsenodes.h:2760
	FkDelSetCols       *NodeList  // ON DELETE SET NULL/DEFAULT (column_list) - postgres/src/include/nodes/parsenodes.h:2761
	OldConpfeqop       []Oid      // pg_constraint.conpfeqop of my former self - postgres/src/include/nodes/parsenodes.h:2762
	OldPktableOid      Oid        // pg_class.oid of my former self - postgres/src/include/nodes/parsenodes.h:2763
}

// NewConstraint creates a new Constraint node.
func NewConstraint(contype ConstrType) *Constraint { _ = "STUB: not implemented"; return nil }

// Constraints are valid by default unless explicitly marked NOT VALID

func (c *Constraint) String() string { _ = "STUB: not implemented"; return "" }

// indexConstraintTail renders the trailing clauses shared by PRIMARY KEY and
// UNIQUE table constraints: INCLUDE non-key columns, an adopted index or index
// tablespace, and deferrability.
func (c *Constraint) indexConstraintTail() string { _ = "STUB: not implemented"; return "" }

// SqlString generates SQL representation of a constraint
func (c *Constraint) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add sequence options if present

// Check if it's a boolean and handle accordingly

// Almost always ALWAYS, but preserve BY DEFAULT if that is what was
// parsed (round-trip; PG itself rejects BY DEFAULT for STORED columns).

// NULLS DISTINCT is the default; only the NOT form needs rendering.

// Add NO INHERIT if specified

// Add NOT VALID if specified (InitiallyValid = false means NOT VALID)

// For column-level constraints, don't include "FOREIGN KEY"
// For table-level constraints, include it

// Add MATCH clause if explicitly specified (non-zero and not default SIMPLE)

// Add foreign key actions (only if explicitly set and not default NO ACTION)

// Add DEFERRABLE and INITIALLY DEFERRED attributes

// Add NOT VALID if specified (InitiallyValid = false means NOT VALID)

// Add access method if specified

// Add exclusion elements (column WITH operator pairs)

// Each exclusion is a pair: (IndexElem, operator name)

// Get the operator

// Add INCLUDE non-key columns if specified

// Add WHERE clause if specified

// Add deferrability

// Constraint attributes parsed as standalone nodes for column constraints
// (PostgreSQL merges these into the preceding constraint during analysis;
// at raw-parse time they are separate Constraint nodes).

// ==============================================================================
// ALTER TABLE STATEMENTS
// ==============================================================================

// AlterTableStmt represents an ALTER TABLE statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2339
type AlterTableStmt struct {
	BaseNode
	Relation  *RangeVar  // table to work on - postgres/src/include/nodes/parsenodes.h:2341
	Cmds      *NodeList  // list of subcommands - postgres/src/include/nodes/parsenodes.h:2342
	Objtype   ObjectType // type of object - postgres/src/include/nodes/parsenodes.h:2344
	MissingOk bool       // skip error if table missing - postgres/src/include/nodes/parsenodes.h:2345
}

// NewAlterTableStmt creates a new AlterTableStmt node.
func NewAlterTableStmt(relation *RangeVar, cmds *NodeList) *AlterTableStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterTableStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterTableStmt) String() string { _ = "STUB: not implemented"; return "" }

// ReplicaIdentityStmt represents a REPLICA IDENTITY statement.
// Ported from postgres/src/include/nodes/parsenodes.h
type ReplicaIdentityStmt struct {
	BaseNode
	IdentityType rune   // replica identity type ('d', 'n', 'f', 'i')
	Name         string // index name for REPLICA_IDENTITY_INDEX, or empty
}

// NewReplicaIdentityStmt creates a new ReplicaIdentityStmt node.
func NewReplicaIdentityStmt(identityType rune, name string) *ReplicaIdentityStmt {
	_ = "STUB: not implemented"
	return nil
}

func (r *ReplicaIdentityStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (r *ReplicaIdentityStmt) String() string { _ = "STUB: not implemented"; return "" }

func (r *ReplicaIdentityStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// AlterTableMoveAllStmt represents moving all tables/indexes/views from one tablespace to another.
// Ported from postgres/src/include/nodes/parsenodes.h:2348-2356
type AlterTableMoveAllStmt struct {
	BaseNode
	OrigTablespacename string     // original tablespace name
	Objtype            ObjectType // Object type to move
	Roles              *NodeList  // List of roles to move objects of
	NewTablespacename  string     // new tablespace name
	Nowait             bool       // do not wait for locks
}

// NewAlterTableMoveAllStmt creates a new AlterTableMoveAllStmt node.
func NewAlterTableMoveAllStmt(origTablespace string, objtype ObjectType, newTablespace string) *AlterTableMoveAllStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterTableMoveAllStmt) node() { _ = "STUB: not implemented"; return }
func (a *AlterTableMoveAllStmt) stmt() { _ = "STUB: not implemented"; return }

func (a *AlterTableMoveAllStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterTableMoveAllStmt) String() string { _ = "STUB: not implemented"; return "" }

func (a *AlterTableMoveAllStmt) SqlString() string {
	_ = "STUB: not implemented"

	// Start with ALTER
	return ""
}

// Add object type

// Add ALL IN TABLESPACE

// Add OWNED BY if roles specified

// Add SET TABLESPACE

// Add NOWAIT if specified

func (a *AlterTableStmt) SqlString() string {
	_ = "STUB: not implemented"

	// Start with ALTER
	return ""
}

// Add object type

// Add IF EXISTS if specified

// Add relation name

// Add commands

// For composite types, use ATTRIBUTE instead of COLUMN

// AlterTableCmd represents one subcommand of an ALTER TABLE.
// Ported from postgres/src/include/nodes/parsenodes.h:2426
type AlterTableCmd struct {
	BaseNode
	Subtype   AlterTableType // Type of table alteration to apply - postgres/src/include/nodes/parsenodes.h:2429
	Name      string         // column, constraint, or trigger to act on - postgres/src/include/nodes/parsenodes.h:2430
	Num       int16          // attribute number for columns referenced by number - postgres/src/include/nodes/parsenodes.h:2432
	Newowner  *RoleSpec      // postgres/src/include/nodes/parsenodes.h:2434
	Def       Node           // definition of new column, index, constraint, or parent table - postgres/src/include/nodes/parsenodes.h:2435
	Behavior  DropBehavior   // RESTRICT or CASCADE for DROP cases - postgres/src/include/nodes/parsenodes.h:2437
	MissingOk bool           // skip error if missing? - postgres/src/include/nodes/parsenodes.h:2438
	Recurse   bool           // exec-time recursion - postgres/src/include/nodes/parsenodes.h:2439
}

// NewAlterTableCmd creates a new AlterTableCmd node.
func NewAlterTableCmd(subtype AlterTableType, name string, def Node) *AlterTableCmd {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterTableCmd) String() string { _ = "STUB: not implemented"; return "" }

func (a *AlterTableCmd) SqlString() string { _ = "STUB: not implemented"; return "" }

// For ALTER COLUMN TYPE, we need to handle the type and USING clause specially

// Add USING clause if specified (stored in RawDefault for ALTER COLUMN TYPE)

// Add collation if specified

// The constraint SqlString already includes CONSTRAINT keyword and name

// For storage modes, we want an identifier, not a quoted string literal

// For compression methods, we want an identifier, not a quoted string literal

// a.Def should be a PartitionCmd containing the partition name and bound spec

// a.Def should be a PartitionCmd containing the partition name

// a.Def should be a PartitionCmd containing the partition name

// Handle identity constraint specially for ADD case

// Build the identity specification with proper formatting for ADD

// Add sequence options in parentheses (without SET keywords)

// Fallback to regular SqlString for non-identity constraints

// Handle identity specifications - could be a Constraint or DefElems

// Each option is self-contained: "SET GENERATED ...", a "SET
// <seqopt>", or a bare "RESTART". Earlier code prepended a global
// SET and a "GENERATED BY DEFAULT" even when neither was present,
// which corrupted e.g. "SET INCREMENT BY 2".

// Fallback to default SqlString

// Add DEFERRABLE and INITIALLY DEFERRED attributes

// When Name is empty, it means DEFAULT was explicitly specified

// Handle DefElem with ADD/SET/DROP actions for column options

// Fallback to regular format - defaction might be DEFELEM_UNSPEC or something else

// Handle NodeList of DefElems

// Fallback - assume ADD if no action specified

// Handle DefElem with ADD/SET/DROP actions for table-level options

// Fallback - assume ADD if no action specified

// Handle NodeList of DefElems for multiple options

// Fallback - assume ADD if no action specified

// Fallback for unhandled subtypes

// SqlStringForCompositeType returns the SQL string for composite type operations using ATTRIBUTE instead of COLUMN
func (a *AlterTableCmd) SqlStringForCompositeType() string { _ = "STUB: not implemented"; return "" }

// Add CASCADE behavior if specified

// For ALTER ATTRIBUTE, we only want the type part, not the full column definition

// Add collation if specified

// Add CASCADE or RESTRICT behavior if specified

// For other operations, use the regular SqlString method

// ==============================================================================
// INDEX STATEMENTS
// ==============================================================================

// IndexStmt represents a CREATE INDEX statement.
// Ported from postgres/src/include/nodes/parsenodes.h:3348
type IndexStmt struct {
	BaseNode
	Idxname                  string    // name of new index, or NULL for default - postgres/src/include/nodes/parsenodes.h:3350
	Relation                 *RangeVar // relation to build index on - postgres/src/include/nodes/parsenodes.h:3351
	AccessMethod             string    // name of access method (eg. btree) - postgres/src/include/nodes/parsenodes.h:3352
	TableSpace               string    // tablespace, or NULL for default - postgres/src/include/nodes/parsenodes.h:3353
	IndexParams              *NodeList // columns to index: a list of IndexElem - postgres/src/include/nodes/parsenodes.h:3354
	IndexIncludingParams     *NodeList // additional columns to index - postgres/src/include/nodes/parsenodes.h:3355
	Options                  *NodeList // WITH clause options: a list of DefElem - postgres/src/include/nodes/parsenodes.h:3357
	WhereClause              Node      // qualification (partial-index predicate) - postgres/src/include/nodes/parsenodes.h:3358
	ExcludeOpNames           *NodeList // exclusion operator names, or NIL if none - postgres/src/include/nodes/parsenodes.h:3359
	Idxcomment               string    // comment to apply to index, or NULL - postgres/src/include/nodes/parsenodes.h:3360
	IndexOid                 Oid       // OID of an existing index, if any - postgres/src/include/nodes/parsenodes.h:3361
	OldNumber                uint32    // relfilenumber of existing storage, if any - postgres/src/include/nodes/parsenodes.h:3362
	OldCreateSubid           uint32    // rd_createSubid of existing storage, if any - postgres/src/include/nodes/parsenodes.h:3363
	OldFirstRelfilenodeSubid uint32    // rd_firstRelfilenodeSubid of existing storage - postgres/src/include/nodes/parsenodes.h:3364
	Unique                   bool      // is index unique? - postgres/src/include/nodes/parsenodes.h:3365
	NullsNotDistinct         bool      // null treatment in unique index - postgres/src/include/nodes/parsenodes.h:3366
	Primary                  bool      // is index a primary key? - postgres/src/include/nodes/parsenodes.h:3367
	Isconstraint             bool      // is it for a pkey/unique constraint? - postgres/src/include/nodes/parsenodes.h:3368
	Deferrable               bool      // is the constraint DEFERRABLE? - postgres/src/include/nodes/parsenodes.h:3369
	Initdeferred             bool      // is the constraint INITIALLY DEFERRED? - postgres/src/include/nodes/parsenodes.h:3370
	Transformed              bool      // true when transformIndexStmt is finished - postgres/src/include/nodes/parsenodes.h:3371
	Concurrent               bool      // should this be a concurrent index build? - postgres/src/include/nodes/parsenodes.h:3372
	IfNotExists              bool      // just do nothing if index already exists? - postgres/src/include/nodes/parsenodes.h:3373
	ResetDefaultTblspc       bool      // reset default_tablespace prior to creating the index - postgres/src/include/nodes/parsenodes.h:3374
}

// NewIndexStmt creates a new IndexStmt node.
func NewIndexStmt(idxname string, relation *RangeVar, indexParams *NodeList) *IndexStmt {
	_ = "STUB: not implemented"
	return nil
}

// default access method

func (i *IndexStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (i *IndexStmt) String() string { _ = "STUB: not implemented"; return "" }

// IndexElem represents one index element (column or expression).
// Ported from postgres/src/include/nodes/parsenodes.h:780
type IndexElem struct {
	BaseNode
	Name          string      // name of attribute to index, or NULL - postgres/src/include/nodes/parsenodes.h:782
	Expr          Node        // expression to index, or NULL - postgres/src/include/nodes/parsenodes.h:783
	Indexcolname  string      // name for index column; NULL = default - postgres/src/include/nodes/parsenodes.h:784
	Collation     *NodeList   // name of collation; NIL = default - postgres/src/include/nodes/parsenodes.h:785
	Opclass       *NodeList   // name of desired opclass; NIL = default - postgres/src/include/nodes/parsenodes.h:786
	Opclassopts   *NodeList   // opclass-specific options, or NIL - postgres/src/include/nodes/parsenodes.h:787
	Ordering      SortByDir   // ASC/DESC/default - postgres/src/include/nodes/parsenodes.h:788
	NullsOrdering SortByNulls // FIRST/LAST/default - postgres/src/include/nodes/parsenodes.h:789
}

// NewIndexElem creates a new IndexElem node.
func NewIndexElem(name string) *IndexElem { _ = "STUB: not implemented"; return nil }

func (i *IndexElem) String() string { _ = "STUB: not implemented"; return "" }

func (i *IndexElem) SqlString() string {
	_ = "STUB: not implemented"

	// Get the base column name or expression
	return ""
}

// Add collation if specified (before operator class)

// Collation names should be output as identifiers, not string literals

// Quote as identifier if needed

// Add operator class if specified (after collation)

// Format operator class as identifier, not quoted string

// Add operator class options if specified

// Format operator class options with no spaces around '='

// Add ordering (ASC/DESC) if not default

// SORTBY_DEFAULT means no explicit ordering clause

// Add null ordering if not default

// SORTBY_NULLS_DEFAULT means no explicit nulls clause

// ==============================================================================
// VIEW STATEMENTS
// ==============================================================================

// ViewStmt represents a CREATE VIEW statement.
// Ported from postgres/src/include/nodes/parsenodes.h:3740
type ViewStmt struct {
	BaseNode
	View            *RangeVar       // the view to be created - postgres/src/include/nodes/parsenodes.h:3742
	Aliases         *NodeList       // target column names - postgres/src/include/nodes/parsenodes.h:3743
	Query           Node            // the SELECT query (as a raw parse tree) - postgres/src/include/nodes/parsenodes.h:3744
	Replace         bool            // replace an existing view? - postgres/src/include/nodes/parsenodes.h:3745
	Options         *NodeList       // options from WITH clause - postgres/src/include/nodes/parsenodes.h:3746
	WithCheckOption ViewCheckOption // WITH CHECK OPTION - postgres/src/include/nodes/parsenodes.h:3747
}

// NewViewStmt creates a new ViewStmt node.
func NewViewStmt(view *RangeVar, query Node, replace bool) *ViewStmt {
	_ = "STUB: not implemented"
	return nil
}

func (v *ViewStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (v *ViewStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of ViewStmt
func (v *ViewStmt) SqlString() string {
	_ = "STUB: not implemented"

	// CREATE [OR REPLACE] [TEMP] [RECURSIVE] VIEW
	return ""
}

// Add TEMP/TEMPORARY if needed

// TODO: Add RECURSIVE support when we can detect recursive views
// For now, we can't easily determine if a view is recursive from the ViewStmt

// View name

// Column aliases

// WITH options

// AS query

// WITH CHECK OPTION

// No check option

// ==============================================================================
// DOMAIN STATEMENTS
// ==============================================================================

// AlterDomainStmt represents an ALTER DOMAIN statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2461
type AlterDomainStmt struct {
	BaseNode
	Subtype   byte         // T/N/O/C/X for alter type - postgres/src/include/nodes/parsenodes.h:2463
	TypeName  *NodeList    // domain to work on - postgres/src/include/nodes/parsenodes.h:2464
	Name      string       // column or constraint name to act on - postgres/src/include/nodes/parsenodes.h:2465
	Def       Node         // definition of default or constraint - postgres/src/include/nodes/parsenodes.h:2466
	Behavior  DropBehavior // RESTRICT or CASCADE for DROP cases - postgres/src/include/nodes/parsenodes.h:2467
	MissingOk bool         // skip error if missing? - postgres/src/include/nodes/parsenodes.h:2468
}

// NewAlterDomainStmt creates a new AlterDomainStmt node.
func NewAlterDomainStmt(subtype byte, typeName *NodeList) *AlterDomainStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterDomainStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterDomainStmt) String() string { _ = "STUB: not implemented"; return "" }

// last part is the domain name

// SqlString returns the SQL representation of ALTER DOMAIN statement.
func (a *AlterDomainStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add domain name

// Handle different subtype commands

// SET DEFAULT or DROP DEFAULT

// DROP NOT NULL

// SET NOT NULL

// ADD CONSTRAINT

// DROP CONSTRAINT

// VALIDATE CONSTRAINT

// CreateDomainStmt represents a CREATE DOMAIN statement.
// Ported from postgres/src/include/nodes/parsenodes.h:3156
type CreateDomainStmt struct {
	BaseNode
	Domainname  *NodeList      // qualified name (list of String) - postgres/src/include/nodes/parsenodes.h:3158
	TypeName    *TypeName      // the base type - postgres/src/include/nodes/parsenodes.h:3159
	CollClause  *CollateClause // untransformed COLLATE spec, if any - postgres/src/include/nodes/parsenodes.h:3160
	Constraints *NodeList      // constraints (list of Constraint nodes) - postgres/src/include/nodes/parsenodes.h:3161
}

// NewCreateDomainStmt creates a new CreateDomainStmt node.
func NewCreateDomainStmt(domainname *NodeList, typeName *TypeName) *CreateDomainStmt {
	_ = "STUB: not implemented"
	return nil
}

func (c *CreateDomainStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (c *CreateDomainStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of CREATE DOMAIN statement.
func (c *CreateDomainStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add domain name

// Add AS keyword

// Add type name

// Add constraints

// Add collate clause

// ==============================================================================
// SCHEMA STATEMENTS
// ==============================================================================

// CreateSchemaStmt represents a CREATE SCHEMA statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2320
type CreateSchemaStmt struct {
	BaseNode
	Schemaname  string    // the name of the schema to create - postgres/src/include/nodes/parsenodes.h:2322
	Authrole    *RoleSpec // the owner of the created schema - postgres/src/include/nodes/parsenodes.h:2323
	SchemaElts  *NodeList // schema components (list of parsenodes) - postgres/src/include/nodes/parsenodes.h:2324
	IfNotExists bool      // just do nothing if schema already exists? - postgres/src/include/nodes/parsenodes.h:2325
}

// NewCreateSchemaStmt creates a new CreateSchemaStmt node.
func NewCreateSchemaStmt(schemaname string, ifNotExists bool) *CreateSchemaStmt {
	_ = "STUB: not implemented"
	return nil
}

func (c *CreateSchemaStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (c *CreateSchemaStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns SQL representation of the CREATE SCHEMA statement
func (c *CreateSchemaStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add schema name if specified

// Add AUTHORIZATION clause if specified

// Add embedded statements if any

// ==============================================================================
// EXTENSION STATEMENTS
// ==============================================================================

// CreateExtensionStmt represents a CREATE EXTENSION statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2819
type CreateExtensionStmt struct {
	BaseNode
	Extname     string    // extension name - postgres/src/include/nodes/parsenodes.h:2821
	IfNotExists bool      // just do nothing if it already exists? - postgres/src/include/nodes/parsenodes.h:2822
	Options     *NodeList // List of DefElem nodes - postgres/src/include/nodes/parsenodes.h:2823
}

// NewCreateExtensionStmt creates a new CreateExtensionStmt node.
func NewCreateExtensionStmt(extname string, ifNotExists bool, options *NodeList) *CreateExtensionStmt {
	_ = "STUB: not implemented"
	return nil
}

func (c *CreateExtensionStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (c *CreateExtensionStmt) String() string { _ = "STUB: not implemented"; return "" }

// formatExtensionOption formats an extension option DefElem for SQL output
func formatExtensionOption(opt *DefElem) string { _ = "STUB: not implemented"; return "" }

// Schema names are identifiers - use proper identifier quoting

// Fall back to default formatting

// SqlString returns the SQL representation of CreateExtensionStmt
func (c *CreateExtensionStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add options if present

// AlterExtensionStmt represents an ALTER EXTENSION statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2834
type AlterExtensionStmt struct {
	BaseNode
	Extname string    // extension name
	Options *NodeList // list of DefElem nodes
}

// NewAlterExtensionStmt creates a new AlterExtensionStmt node.
func NewAlterExtensionStmt(extname string, options *NodeList) *AlterExtensionStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterExtensionStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterExtensionStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of AlterExtensionStmt
func (a *AlterExtensionStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add options if present

// Special handling for ALTER EXTENSION TO option

// AlterExtensionContentsStmt represents an ALTER EXTENSION ADD/DROP statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2842
type AlterExtensionContentsStmt struct {
	BaseNode
	Extname string // extension name
	Action  bool   // true = ADD, false = DROP
	Objtype int    // object type from ObjectType enum
	Object  Node   // qualified name of the object (can be String, NodeList, TypeName, etc.)
}

// NewAlterExtensionContentsStmt creates a new AlterExtensionContentsStmt node.
func NewAlterExtensionContentsStmt(extname string, action bool, objtype int, object Node) *AlterExtensionContentsStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterExtensionContentsStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterExtensionContentsStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of AlterExtensionContentsStmt
func (a *AlterExtensionContentsStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add object type and handle special formatting cases

// For CAST, the object is a NodeList with two TypeNames

// For OPERATOR CLASS, need to handle "name USING method" format

// First item is method name, rest are class name parts

// For OPERATOR FAMILY, need to handle "name USING method" format

// First item is method name, rest are family name parts

// For other object types, use simple case conversion

// Add object name for simple cases (non-special formatting)

// ==============================================================================
// DDL CONVENIENCE CONSTRUCTORS
// ==============================================================================

// NewPrimaryKeyConstraint creates a PRIMARY KEY constraint.
func NewPrimaryKeyConstraint(conname string, keys []string) *Constraint {
	_ = "STUB: not implemented"
	return nil
}

// NewForeignKeyConstraint creates a FOREIGN KEY constraint.
func NewForeignKeyConstraint(conname string, fkAttrs []string, pktable *RangeVar, pkAttrs []string) *Constraint {
	_ = "STUB: not implemented"
	return nil
}

// NewUniqueConstraint creates a UNIQUE constraint.
func NewUniqueConstraint(conname string, keys []string) *Constraint {
	_ = "STUB: not implemented"
	return nil
}

// NewUniqueConstraintNullsNotDistinct creates a UNIQUE constraint with NULLS NOT DISTINCT.
func NewUniqueConstraintNullsNotDistinct(conname string, keys []string) *Constraint {
	_ = "STUB: not implemented"
	return nil
}

// NewCheckConstraint creates a CHECK constraint.
func NewCheckConstraint(conname string, rawExpr Node) *Constraint {
	_ = "STUB: not implemented"
	return nil
}

// NewNotNullConstraint creates a NOT NULL constraint.
func NewNotNullConstraint(conname string) *Constraint { _ = "STUB: not implemented"; return nil }

// NewAddColumnCmd creates an ALTER TABLE ADD COLUMN command.
func NewAddColumnCmd(columnName string, columnDef Node) *AlterTableCmd {
	_ = "STUB: not implemented"
	return nil
}

// NewDropColumnCmd creates an ALTER TABLE DROP COLUMN command.
func NewDropColumnCmd(columnName string, behavior DropBehavior) *AlterTableCmd {
	_ = "STUB: not implemented"
	return nil
}

// NewAddConstraintCmd creates an ALTER TABLE ADD CONSTRAINT command.
func NewAddConstraintCmd(constraint *Constraint) *AlterTableCmd {
	_ = "STUB: not implemented"
	return nil
}

// NewDropConstraintCmd creates an ALTER TABLE DROP CONSTRAINT command.
func NewDropConstraintCmd(constraintName string, behavior DropBehavior) *AlterTableCmd {
	_ = "STUB: not implemented"
	return nil
}

// NewUniqueIndex creates a unique index statement.
func NewUniqueIndex(idxname string, relation *RangeVar, indexParams *NodeList) *IndexStmt {
	_ = "STUB: not implemented"
	return nil
}

// NewBtreeIndexElem creates a B-tree index element with default ordering.
func NewBtreeIndexElem(columnName string) *IndexElem { _ = "STUB: not implemented"; return nil }

// NewDescIndexElem creates a descending index element.
func NewDescIndexElem(columnName string) *IndexElem { _ = "STUB: not implemented"; return nil }

// NewExpressionIndexElem creates an index element on an expression.
func NewExpressionIndexElem(expr Node) *IndexElem { _ = "STUB: not implemented"; return nil }

// SqlString returns the SQL representation of CREATE INDEX statement
func (i *IndexStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add UNIQUE if specified

// Add CONCURRENTLY if specified

// Add IF NOT EXISTS if specified

// Add index name

// Add ON table

// Add access method if specified

// Add index columns

// Add INCLUDE columns if specified

// Add NULLS NOT DISTINCT if specified

// Add WITH options if specified

// Add tablespace if specified

// Add WHERE clause if specified

// ==============================================================================
// FOREIGN DATA WRAPPER AST NODES
// ==============================================================================

// CreateFdwStmt represents CREATE FOREIGN DATA WRAPPER statement
// Ported from postgres/src/include/nodes/parsenodes.h CreateFdwStmt
type CreateFdwStmt struct {
	BaseNode
	FdwName     string    `json:"fdwname"`      // foreign data wrapper name
	FuncOptions *NodeList `json:"func_options"` // HANDLER/VALIDATOR options
	Options     *NodeList `json:"options"`      // OPTIONS clause
}

// NewCreateFdwStmt creates a new CreateFdwStmt node
func NewCreateFdwStmt(fdwname string, funcOptions, options *NodeList) *CreateFdwStmt {
	_ = "STUB: not implemented"
	return nil
}

func (c *CreateFdwStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (c *CreateFdwStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of CreateFdwStmt
func (c *CreateFdwStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add HANDLER/VALIDATOR options

// Special handling for HANDLER and VALIDATOR

// Handle qualified function names (schema.function)

// Handle qualified function names (schema.function)

// For other options, use the standard format

// Add OPTIONS clause

// For generic options, use PostgreSQL format: key 'value' (no =)

// AlterFdwStmt represents ALTER FOREIGN DATA WRAPPER statement
// Ported from postgres/src/include/nodes/parsenodes.h AlterFdwStmt
type AlterFdwStmt struct {
	BaseNode
	FdwName     string    `json:"fdwname"`      // foreign data wrapper name
	FuncOptions *NodeList `json:"func_options"` // HANDLER/VALIDATOR options
	Options     *NodeList `json:"options"`      // OPTIONS clause
}

// NewAlterFdwStmt creates a new AlterFdwStmt node
func NewAlterFdwStmt(fdwname string, funcOptions, options *NodeList) *AlterFdwStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterFdwStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterFdwStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of AlterFdwStmt
func (a *AlterFdwStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add HANDLER/VALIDATOR options

// Special handling for HANDLER and VALIDATOR

// Handle qualified function names (schema.function)

// NO HANDLER case

// Handle qualified function names (schema.function)

// NO VALIDATOR case

// For other options, use the standard format

// Add OPTIONS clause

// For ALTER options, include the action (ADD/SET/DROP) prefix

// DEFELEM_UNSPEC or other - use without action prefix

// AlterForeignServerStmt represents ALTER SERVER statement
// Ported from postgres/src/include/nodes/parsenodes.h AlterForeignServerStmt
type AlterForeignServerStmt struct {
	BaseNode
	Servername string    `json:"servername"`  // server name
	Version    string    `json:"version"`     // optional server version
	Options    *NodeList `json:"options"`     // OPTIONS clause
	HasVersion bool      `json:"has_version"` // whether version was specified
}

// NewAlterForeignServerStmt creates a new AlterForeignServerStmt node
func NewAlterForeignServerStmt(servername, version string, options *NodeList, hasVersion bool) *AlterForeignServerStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterForeignServerStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterForeignServerStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of AlterForeignServerStmt
func (a *AlterForeignServerStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add OPTIONS clause

// For ALTER options, include the action (ADD/SET/DROP) prefix

// DEFELEM_UNSPEC or other - use without action prefix

// AlterUserMappingStmt represents ALTER USER MAPPING statement
// Ported from postgres/src/include/nodes/parsenodes.h AlterUserMappingStmt
type AlterUserMappingStmt struct {
	BaseNode
	User       *RoleSpec `json:"user"`       // user name or role
	Servername string    `json:"servername"` // server name
	Options    *NodeList `json:"options"`    // OPTIONS clause
}

// NewAlterUserMappingStmt creates a new AlterUserMappingStmt node
func NewAlterUserMappingStmt(user *RoleSpec, servername string, options *NodeList) *AlterUserMappingStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterUserMappingStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterUserMappingStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of AlterUserMappingStmt
func (a *AlterUserMappingStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add OPTIONS clause

// For ALTER options, include the action (ADD/SET/DROP) prefix

// DEFELEM_UNSPEC or other - use without action prefix

// DropUserMappingStmt represents DROP USER MAPPING statement
// Ported from postgres/src/include/nodes/parsenodes.h DropUserMappingStmt
type DropUserMappingStmt struct {
	BaseNode
	User       *RoleSpec `json:"user"`       // user name or role
	Servername string    `json:"servername"` // server name
	MissingOk  bool      `json:"missing_ok"` // IF EXISTS option
}

// NewDropUserMappingStmt creates a new DropUserMappingStmt node
func NewDropUserMappingStmt(user *RoleSpec, servername string, missingOk bool) *DropUserMappingStmt {
	_ = "STUB: not implemented"
	return nil
}

func (d *DropUserMappingStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (d *DropUserMappingStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of DropUserMappingStmt
func (d *DropUserMappingStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Event trigger constants
type TriggerFires int

const (
	TRIGGER_FIRES_ON_ORIGIN TriggerFires = iota
	TRIGGER_FIRES_ON_REPLICA
	TRIGGER_FIRES_ALWAYS
	TRIGGER_DISABLED
)

// ==============================================================================
// EVENT TRIGGER STATEMENTS
// ==============================================================================

// CreateEventTrigStmt represents CREATE EVENT TRIGGER statement
// Ported from postgres/src/include/nodes/parsenodes.h CreateEventTrigStmt
type CreateEventTrigStmt struct {
	BaseNode
	TrigName   string    `json:"trigname"`   // event trigger name
	EventName  string    `json:"eventname"`  // event name (e.g., ddl_command_start)
	FuncName   *NodeList `json:"funcname"`   // function name
	WhenClause *NodeList `json:"whenclause"` // WHEN clause conditions
}

// NewCreateEventTrigStmt creates a new CreateEventTrigStmt node
func NewCreateEventTrigStmt(trigname string, eventname string, funcname *NodeList, whenclause *NodeList) *CreateEventTrigStmt {
	_ = "STUB: not implemented"
	return nil
}

func (c *CreateEventTrigStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (c *CreateEventTrigStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of CreateEventTrigStmt
func (c *CreateEventTrigStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add WHEN clause if present

// Format as "defname IN (value1, value2, ...)"

// AlterEventTrigStmt represents ALTER EVENT TRIGGER statement
// Ported from postgres/src/include/nodes/parsenodes.h AlterEventTrigStmt
type AlterEventTrigStmt struct {
	BaseNode
	TrigName  string       `json:"trigname"`  // event trigger name
	TgEnabled TriggerFires `json:"tgenabled"` // enable/disable state
}

// NewAlterEventTrigStmt creates a new AlterEventTrigStmt node
func NewAlterEventTrigStmt(trigname string, tgenabled TriggerFires) *AlterEventTrigStmt {
	_ = "STUB: not implemented"
	return nil
}

func (a *AlterEventTrigStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (a *AlterEventTrigStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of AlterEventTrigStmt
func (a *AlterEventTrigStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// ==============================================================================
// DATABASE STATEMENTS
// ==============================================================================

// CreatedbStmt represents a CREATE DATABASE statement.
// Ported from postgres/src/include/nodes/parsenodes.h:3787
type CreatedbStmt struct {
	BaseNode
	Dbname  string    // name of database to create - postgres/src/include/nodes/parsenodes.h:3789
	Options *NodeList // list of DefElem nodes - postgres/src/include/nodes/parsenodes.h:3790
}

// NewCreatedbStmt creates a new CreatedbStmt node.
func NewCreatedbStmt(dbname string, options *NodeList) *CreatedbStmt {
	_ = "STUB: not implemented"
	return nil
}

func (c *CreatedbStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (c *CreatedbStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of CreatedbStmt
func (c *CreatedbStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add options if present

// formatDatabaseOption formats database options with proper PostgreSQL keywords
func (c *CreatedbStmt) formatDatabaseOption(opt *DefElem) string {
	_ = "STUB: not implemented"
	// Map option names to their proper PostgreSQL keywords
	return ""
}

// For identifiers that should not be quoted

// These should be unquoted identifiers

// These should remain as quoted strings

// DropdbStmt represents a DROP DATABASE statement.
// Ported from postgres/src/include/nodes/parsenodes.h:3800
type DropdbStmt struct {
	BaseNode
	Dbname    string    // database to drop - postgres/src/include/nodes/parsenodes.h:3803
	MissingOk bool      // skip error if db is missing? - postgres/src/include/nodes/parsenodes.h:3804
	Options   *NodeList // currently only FORCE is supported - postgres/src/include/nodes/parsenodes.h:3805
}

// NewDropdbStmt creates a new DropdbStmt node.
func NewDropdbStmt(dbname string, missingOk bool, options *NodeList) *DropdbStmt {
	_ = "STUB: not implemented"
	return nil
}

func (d *DropdbStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (d *DropdbStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of DropdbStmt
func (d *DropdbStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add options if present (e.g., FORCE)

// DropTableSpaceStmt represents a DROP TABLESPACE statement.
// Ported from postgres/src/include/nodes/parsenodes.h:2790
type DropTableSpaceStmt struct {
	BaseNode
	Tablespacename string // tablespace to drop - postgres/src/include/nodes/parsenodes.h:2792
	MissingOk      bool   // skip error if missing? - postgres/src/include/nodes/parsenodes.h:2793
}

// NewDropTableSpaceStmt creates a new DropTableSpaceStmt node.
func NewDropTableSpaceStmt(tablespacename string, missingOk bool) *DropTableSpaceStmt {
	_ = "STUB: not implemented"
	return nil
}

func (d *DropTableSpaceStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (d *DropTableSpaceStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of DropTableSpaceStmt
func (d *DropTableSpaceStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// ==============================================================================
// OWNERSHIP STATEMENTS
// ==============================================================================

// DropOwnedStmt represents a DROP OWNED statement.
// Ported from postgres/src/include/nodes/parsenodes.h:4075
type DropOwnedStmt struct {
	BaseNode
	Roles    *NodeList    // list of RoleSpec - postgres/src/include/nodes/parsenodes.h:4078
	Behavior DropBehavior // CASCADE or RESTRICT - postgres/src/include/nodes/parsenodes.h:4079
}

// NewDropOwnedStmt creates a new DropOwnedStmt node.
func NewDropOwnedStmt(roles *NodeList, behavior DropBehavior) *DropOwnedStmt {
	_ = "STUB: not implemented"
	return nil
}

func (d *DropOwnedStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (d *DropOwnedStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of DropOwnedStmt
func (d *DropOwnedStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add role list

// Add behavior

// ReassignOwnedStmt represents a REASSIGN OWNED statement.
// Ported from postgres/src/include/nodes/parsenodes.h:4084
type ReassignOwnedStmt struct {
	BaseNode
	Roles   *NodeList // list of RoleSpec - postgres/src/include/nodes/parsenodes.h:4087
	Newrole *RoleSpec // new owner - postgres/src/include/nodes/parsenodes.h:4088
}

// NewReassignOwnedStmt creates a new ReassignOwnedStmt node.
func NewReassignOwnedStmt(roles *NodeList, newrole *RoleSpec) *ReassignOwnedStmt {
	_ = "STUB: not implemented"
	return nil
}

func (r *ReassignOwnedStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (r *ReassignOwnedStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of ReassignOwnedStmt
func (r *ReassignOwnedStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add role list

// ==============================================================================
// FOREIGN SCHEMA STATEMENTS
// ==============================================================================

// ImportForeignSchemaType represents import qualification types for IMPORT FOREIGN SCHEMA
// Ported from postgres/src/include/nodes/parsenodes.h:4094-4100
type ImportForeignSchemaType int

const (
	FDW_IMPORT_SCHEMA_ALL      ImportForeignSchemaType = iota // all relations wanted
	FDW_IMPORT_SCHEMA_LIMIT_TO                                // include only listed tables in import
	FDW_IMPORT_SCHEMA_EXCEPT                                  // exclude listed tables from import
)

// String returns string representation of ImportForeignSchemaType
func (t ImportForeignSchemaType) String() string { _ = "STUB: not implemented"; return "" }

// ImportForeignSchemaStmt represents an IMPORT FOREIGN SCHEMA statement
// Ported from postgres/src/include/nodes/parsenodes.h:4105-4115
type ImportForeignSchemaStmt struct {
	BaseNode
	ServerName   *String                 // FDW server name
	RemoteSchema *String                 // remote schema name to query
	LocalSchema  *String                 // local schema to create objects in
	ListType     ImportForeignSchemaType // type of table list
	TableList    *NodeList               // List of RangeVar
	Options      *NodeList               // list of options to pass to FDW
}

// NewImportForeignSchemaStmt creates a new ImportForeignSchemaStmt node
func NewImportForeignSchemaStmt(serverName, remoteSchema, localSchema *String,
	listType ImportForeignSchemaType, tableList, options *NodeList,
) *ImportForeignSchemaStmt {
	_ = "STUB: not implemented"
	return nil
}

func (i *ImportForeignSchemaStmt) StatementType() string { _ = "STUB: not implemented"; return "" }

func (i *ImportForeignSchemaStmt) String() string { _ = "STUB: not implemented"; return "" }

// SqlString returns the SQL representation of ImportForeignSchemaStmt
func (i *ImportForeignSchemaStmt) SqlString() string { _ = "STUB: not implemented"; return "" }

// Add import qualification

// Add options

// For foreign schema import, use "name 'value'" format instead of "name = 'value'"
