// Code generated by goyacc -p replYy -o grammar.go grammar.y. DO NOT EDIT.

//line grammar.y:2
// PostgreSQL Database Management System
// (also known as Postgres, formerly known as Postgres95)
//
//  Portions Copyright (c) 2026, Supabase, Inc
//
//  Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//
//  Portions Copyright (c) 1994, The Regents of the University of California
//
// Permission to use, copy, modify, and distribute this software and its
// documentation for any purpose, without fee, and without a written agreement
// is hereby granted, provided that the above copyright notice and this
// paragraph and the following two paragraphs appear in all copies.
//
// IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
// DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
// LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
// DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
// ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
// PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
//
// Ported from postgres/src/backend/replication/repl_gram.y (PG 17.6),
// dropping physical-replication commands (BASE_BACKUP, TIMELINE_HISTORY,
// UPLOAD_MANIFEST, physical START_REPLICATION, K_PHYSICAL, opt_physical,
// opt_timeline, opt_slot).

package replparser

import (
	"github.com/multigres/multigres/go/common/parser/ast"
)

//line grammar.y:33

const (
	SCONST                    = 57346
	IDENT                     = 57347
	UCONST                    = 57348
	RECPTR                    = 57349
	K_IDENTIFY_SYSTEM         = 57350
	K_READ_REPLICATION_SLOT   = 57351
	K_SHOW                    = 57352
	K_START_REPLICATION       = 57353
	K_CREATE_REPLICATION_SLOT = 57354
	K_DROP_REPLICATION_SLOT   = 57355
	K_ALTER_REPLICATION_SLOT  = 57356
	K_WAIT                    = 57357
	K_TIMELINE                = 57358
	K_LOGICAL                 = 57359
	K_SLOT                    = 57360
	K_RESERVE_WAL             = 57361
	K_TEMPORARY               = 57362
	K_TWO_PHASE               = 57363
	K_EXPORT_SNAPSHOT         = 57364
	K_NOEXPORT_SNAPSHOT       = 57365
	K_USE_SNAPSHOT            = 57366
)

var replYyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SCONST",
	"IDENT",
	"UCONST",
	"RECPTR",
	"K_IDENTIFY_SYSTEM",
	"K_READ_REPLICATION_SLOT",
	"K_SHOW",
	"K_START_REPLICATION",
	"K_CREATE_REPLICATION_SLOT",
	"K_DROP_REPLICATION_SLOT",
	"K_ALTER_REPLICATION_SLOT",
	"K_WAIT",
	"K_TIMELINE",
	"K_LOGICAL",
	"K_SLOT",
	"K_RESERVE_WAL",
	"K_TEMPORARY",
	"K_TWO_PHASE",
	"K_EXPORT_SNAPSHOT",
	"K_NOEXPORT_SNAPSHOT",
	"K_USE_SNAPSHOT",
	"';'",
	"'.'",
	"'('",
	"')'",
	"','",
}

var replYyStatenames = [...]string{}

const (
	replYyEofCode          = 1
	replYyErrCode          = 2
	replYyInitialStackSize = 16
)

//line grammar.y:313

//line yacctab:1
var replYyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const replYyPrivate = 57344

const replYyLast = 84

var replYyAct = [...]int{
	69, 34, 35, 37, 82, 58, 38, 65, 39, 40,
	41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
	51, 52, 53, 78, 79, 57, 58, 76, 63, 77,
	73, 74, 75, 30, 28, 31, 18, 10, 15, 16,
	11, 12, 13, 14, 19, 33, 23, 32, 29, 60,
	59, 61, 70, 55, 56, 54, 26, 24, 22, 21,
	20, 67, 81, 25, 17, 1, 72, 71, 66, 64,
	27, 36, 80, 68, 62, 9, 8, 3, 7, 6,
	83, 5, 4, 2,
}

var replYyPact = [...]int{
	29, -1000, 11, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 26, 55, 54, 53, 52, 52, -1000, -1000, 51,
	14, 33, 6, 9, -1000, 9, 30, 28, -1000, -1000,
	-2, 50, 46, 49, -3, -1000, 45, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 1, -20, -1000, -2, -1000,
	-1000, -1000, -1000, 47, -1000, -2, 8, -1000, -5, -1000,
	58, -24, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 47,
	-1000, -1000, -1000, -1000,
}

var replYyPgo = [...]int{
	0, 83, 82, 81, 79, 78, 77, 76, 75, 1,
	2, 74, 73, 0, 72, 46, 71, 70, 69, 68,
	66, 65, 64,
}

//line grammar.y:313
type replYySymType struct {
	union any
	yys   int
}

func (st *replYySymType) boolvalUnion() bool { _ = "STUB: not implemented"; return false }

func (st *replYySymType) defeltUnion() *ast.DefElem { _ = "STUB: not implemented"; return nil }

func (st *replYySymType) listUnion() []*ast.DefElem { _ = "STUB: not implemented"; return nil }

func (st *replYySymType) nodeUnion() ast.Node { _ = "STUB: not implemented"; return *new(ast.Node) }

func (st *replYySymType) recptrUnion() ast.XLogRecPtr {
	_ = "STUB: not implemented"
	return *new(ast.XLogRecPtr)
}

func (st *replYySymType) strUnion() string { _ = "STUB: not implemented"; return "" }

func (st *replYySymType) uintvalUnion() uint32 { _ = "STUB: not implemented"; return 0 }

var replYyR1 = [...]int{
	0, 21, 22, 22, 1, 1, 1, 1, 1, 1,
	1, 6, 7, 8, 15, 15, 3, 18, 18, 19,
	19, 20, 20, 20, 20, 20, 4, 4, 5, 2,
	17, 17, 11, 11, 12, 12, 13, 14, 14, 9,
	9, 10, 10, 10, 10, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16,
}

var replYyR2 = [...]int{
	0, 2, 1, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 2, 1, 3, 6, 3, 1, 2,
	0, 1, 1, 1, 1, 1, 2, 3, 5, 6,
	1, 0, 3, 0, 1, 3, 2, 1, 0, 3,
	1, 1, 2, 2, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1,
}

var replYyChk = [...]int{
	-1000, -21, -1, -6, -2, -3, -4, -5, -7, -8,
	8, 11, 12, 13, 14, 9, 10, -22, 25, 18,
	5, 5, 5, -15, 5, -15, 5, -17, 20, 15,
	27, 26, 17, 17, -9, -10, -16, 5, 8, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
	21, 22, 23, 24, 5, 7, 5, 28, 29, 5,
	4, 6, -11, 27, -18, 27, -19, -10, -12, -13,
	5, -9, -20, 22, 23, 24, 19, 21, 28, 29,
	-14, 4, 28, -13,
}

var replYyDef = [...]int{
	0, -2, 3, 4, 5, 6, 7, 8, 9, 10,
	11, 0, 0, 0, 0, 0, 0, 1, 2, 0,
	31, 26, 0, 12, 14, 13, 0, 0, 30, 27,
	0, 0, 0, 0, 0, 40, 41, 45, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 15, 33, 20, 28, 0, 42,
	43, 44, 29, 0, 16, 0, 18, 39, 0, 34,
	38, 0, 19, 21, 22, 23, 24, 25, 32, 0,
	36, 37, 17, 35,
}

var replYyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	27, 28, 3, 3, 29, 3, 26, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 25,
}

var replYyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24,
}

var replYyTok3 = [...]int{
	0,
}

var replYyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	replYyDebug        = 0
	replYyErrorVerbose = false
)

type replYyLexer interface {
	Lex(lval *replYySymType) int
	Error(s string)
}

type replYyParser interface {
	Parse(replYyLexer) int
	Lookahead() int
}

type replYyParserImpl struct {
	lval  replYySymType
	stack [replYyInitialStackSize]replYySymType
	char  int
}

func (p *replYyParserImpl) Lookahead() int { _ = "STUB: not implemented"; return 0 }

func replYyNewParser() replYyParser { _ = "STUB: not implemented"; return *new(replYyParser) }

const replYyFlag = -1000

func replYyTokname(c int) string { _ = "STUB: not implemented"; return "" }

func replYyStatname(s int) string { _ = "STUB: not implemented"; return "" }

func replYyErrorMessage(state, lookAhead int) string { _ = "STUB: not implemented"; return "" }

// To match Bison, suggest at most four expected tokens.

// Look for shiftable tokens.

// Look for tokens that we accept or reduce.

// If the default action is to accept or reduce, give up.

func replYylex1(lex replYyLexer, lval *replYySymType) (char, token int) {
	_ = "STUB: not implemented"
	return 0, 0
}

/* unknown char */

func replYyParse(replYylex replYyLexer) int { _ = "STUB: not implemented"; return 0 }

func (replYyrcvr *replYyParserImpl) Parse(replYylex replYyLexer) int {
	_ = "STUB: not implemented"
	return 0
}

// silence set and not used

/* number of errors */
/* error recovery flag */

// replYyrcvr.char translated into internal numbering

// Make sure we report no lookahead when not parsing.

/* put a state and value onto the stack */

/* simple state */

/* valid shift */

/* default state action */

/* look through exception table */

/* error ... attempt to resume parsing */

/* brand new error */

/* incompletely recovered error ... try again */

/* find a state where "error" is a legal shift action */

/* simulate a shift of "error" */

/* the current p has no shift on "error", pop stack */

/* there is no state on the stack with an error shift ... abort */

/* no shift yet; clobber input char */

/* try again in the same state */

/* reduction by production replYyn */

// guard against "declared and not used"

// replYyp is now the index of $0. Perform the default action. Iff the
// reduced production is ε, $1 is possibly out of range.

/* consult goto table to find next state */

// dummy call; replaced with literal code

//line grammar.y:96

//line grammar.y:124

//line grammar.y:132

//line grammar.y:140

//line grammar.y:145

//line grammar.y:147

//line grammar.y:153

//line grammar.y:162

//line grammar.y:163

//line grammar.y:169

//line grammar.y:171

//line grammar.y:177

//line grammar.y:181

//line grammar.y:185

//line grammar.y:189

//line grammar.y:193

//line grammar.y:201

//line grammar.y:205

//line grammar.y:213

//line grammar.y:221

//line grammar.y:228

//line grammar.y:229

//line grammar.y:234

//line grammar.y:235

//line grammar.y:241

//line grammar.y:245

//line grammar.y:253

//line grammar.y:260

//line grammar.y:261

//line grammar.y:267

//line grammar.y:269

//line grammar.y:275

//line grammar.y:279

//line grammar.y:283

//line grammar.y:287

//line grammar.y:294

//line grammar.y:295

//line grammar.y:296

//line grammar.y:297

//line grammar.y:298

//line grammar.y:299

//line grammar.y:300

//line grammar.y:301

//line grammar.y:302

//line grammar.y:303

//line grammar.y:304

//line grammar.y:305

//line grammar.y:306

//line grammar.y:307

//line grammar.y:308

//line grammar.y:309

//line grammar.y:310

/* stack new state and value */
