// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package manager

import (
	"context"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	"github.com/multigres/multigres/go/common/backup"
	"github.com/multigres/multigres/go/common/servenv"
	"github.com/multigres/multigres/go/common/sqltypes"
	"github.com/multigres/multigres/go/common/topoclient"
	"github.com/multigres/multigres/go/services/multipooler/connpoolmanager"
	"github.com/multigres/multigres/go/services/multipooler/executor"
	"github.com/multigres/multigres/go/services/multipooler/heartbeat"
	"github.com/multigres/multigres/go/services/multipooler/poolerserver"
	"github.com/multigres/multigres/go/services/multipooler/pubsub"
	"github.com/multigres/multigres/go/tools/executil"
	"github.com/multigres/multigres/go/tools/timer"

	clustermetadatapb "github.com/multigres/multigres/go/pb/clustermetadata"
	multipoolermanagerdatapb "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	pgctldpb "github.com/multigres/multigres/go/pb/pgctldservice"
)

// ManagerState represents the state of the MultiPoolerManager
type ManagerState string

const (
	// ManagerStateStarting indicates the manager is starting and loading the multipooler record
	ManagerStateStarting ManagerState = "starting"
	// ManagerStateReady indicates the manager has successfully loaded the multipooler record
	ManagerStateReady ManagerState = "ready"
	// ManagerStateError indicates the manager failed to load the multipooler record
	ManagerStateError ManagerState = "error"
)

// MultiPoolerManager manages the pooler lifecycle and PostgreSQL operations
type MultiPoolerManager struct {
	logger     *slog.Logger
	config     *Config
	topoClient topoclient.Store
	// Deprecated: use servicePoolerID instead.
	serviceID       *clustermetadatapb.ID
	servicePoolerID poolerID
	replTracker     *heartbeat.ReplTracker
	pubsubListener  *pubsub.Listener
	pgctldClient    pgctldpb.PgCtldClient

	// connPoolMgr manages all connection pools (admin, regular, reserved)
	connPoolMgr connpoolmanager.PoolManager

	// qsc is the query service controller
	// This controller handles query serving while the manager orchestrates lifecycle,
	// topology, consensus, and replication operations.
	qsc poolerserver.PoolerController

	// actionLock is there to run only one action at a time.
	// This lock can be held for long periods of time (hours),
	// like in the case of a restore. This lock must be obtained
	// first before other mutexes.
	actionLock *ActionLock

	// Multipooler record from topology and startup state

	// mu is the mutex for the manager's state. It must be held for the
	// following:
	// - Reading state
	// - Changing state. This can cause the lock to be held for long periods
	//   of time, particularly when updating external systems (e.g. the topo)
	//   to match the manager's state.
	mu sync.Mutex

	isOpen bool
	// all fields other than Type and ServingStatus never change after initialization.
	// They can be accessed without holding the lock.
	// Type and ServingStatus are exclusively written by the StateManager.
	multipooler    *clustermetadatapb.MultiPooler
	state          ManagerState
	stateError     error
	consensusState *ConsensusState
	topoLoaded     bool
	rules          ruleStorer
	ctx            context.Context
	cancel         context.CancelFunc
	loadTimeout    time.Duration

	// shutdownCtx is cancelled at the end of GracefulShutdown to signal
	// long-lived subscribers (currently the health-stream gRPC handlers via
	// SubscribeHealth) that they should disconnect immediately rather than
	// wait for their own context to be cancelled. This unblocks
	// grpcServer.GracefulStop, which would otherwise wait for the stream
	// handlers to return on their own.
	shutdownCtx    context.Context
	shutdownCancel context.CancelFunc

	// readyChan is closed when state becomes Ready or Error, to broadcast to all waiters.
	// Unbuffered is safe here because we only close() the channel (which never blocks
	// and broadcasts to all receivers) rather than sending to it.
	readyChan chan struct{}

	// Cached backup config from the database topology record.
	// This is loaded once during startup and cached for fast access.
	backupConfig *backup.Config

	// pgBackRestConfigPath is the path to the pgbackrest.conf client config file
	// generated by multipooler during startup. Set once in loadMultiPoolerFromTopo.
	pgBackRestConfigPath string

	// pgpassPath is the path to the libpq password file written at startup.
	// Passed via PGPASSFILE to pgbackrest commands so the password is not
	// exposed in the process environment.
	pgpassPath string

	// pgMonitorRetryInterval is the interval between auto-restore retry attempts.
	// Defaults to 1 second. Can be set to a shorter duration for testing.
	pgMonitorRetryInterval time.Duration

	// initialized tracks whether this pooler has been fully initialized.
	// Once true, stays true for the lifetime of the manager.
	initialized bool

	// resignedLeaderAtTerm is set when this node voluntarily resigns as primary
	// (via EmergencyDemote or graceful shutdown). The value is the consensus
	// term at which the primary resigned. A non-zero value signals the
	// coordinator to trigger an immediate election. Protected by mu. Cleared
	// when this node is elected primary again.
	resignedLeaderAtTerm int64

	// cohortEligibility is this node's self-reported willingness to be a member
	// of the consensus cohort. Defaults to ELIGIBLE; published in every health
	// snapshot via AvailabilityStatus.CohortEligibilityStatus. Protected by mu.
	cohortEligibility clustermetadatapb.CohortEligibilitySignal

	// pgMonitor manages the PostgreSQL monitoring loop.
	pgMonitor *timer.PeriodicRunner

	// rewindPending suppresses the postgres monitor after emergency demotion until a
	// rewind completes successfully. Set by emergencyDemoteLocked, cleared by RewindToSource.
	rewindPending atomic.Bool

	// promotionInProgress is set while pg_promote() has been called but postgres has not yet
	// transitioned to primary mode. Cleared when promotion completes (success or failure).
	// Reported in the health status so multiorch can suppress spurious PrimaryIsDead detection.
	promotionInProgress atomic.Bool

	// postgresRestartsDisabled suppresses auto-restart of a stopped PostgreSQL instance.
	// When set, the monitor continues to run and detect problems but skips the start action.
	// False by default (restarts enabled); tests and demos set it during controlled failovers.
	postgresRestartsDisabled atomic.Bool

	// walReceiverManuallyStopped is set by StopReplication when it clears
	// primary_conninfo (RECEIVER_ONLY / REPLAY_AND_RECEIVER modes). It tells
	// the postgres monitor not to "self-heal" the cleared conninfo back to
	// the recorded primary — the admin/test explicitly asked replication to
	// stop. While set, this pooler publishes COHORT_ELIGIBILITY_INELIGIBLE
	// in its status so the coordinator does not try to include it in the
	// cohort. Cleared by SetTermPrimary, SetPrimaryConnInfo, and
	// demoteStalePrimaryLocked — anything that re-establishes a primary
	// link is interpreted as the admin signal expiring. Not persisted; a
	// process restart implicitly clears it.
	walReceiverManuallyStopped atomic.Bool

	// pgMonitorLastLoggedReason tracks the last logged reason in the monitor to avoid duplicate logs.
	pgMonitorLastLoggedReason string

	// servingState coordinates serving state transitions across components
	// (query service, heartbeat tracker) and updates the multipooler record.
	servingState *StateManager

	// metrics holds OTel gauges for pgBackRest server health.
	metrics *Metrics

	// healthStreamer streams health state to subscribers.
	// Owns all health-related state and provides typed update methods.
	healthStreamer *healthStreamer

	// topoPublisher asynchronously reflects in-memory state to etcd.
	topoPublisher *topoPublisher
}

// promotionState tracks which parts of the promotion are complete
type promotionState struct {
	isPrimaryInPostgres    bool
	isPrimaryInTopology    bool
	syncReplicationMatches bool
	currentLSN             string
}

// demotionState tracks which parts of the demotion are complete
type demotionState struct {
	isNotServing        bool   // PoolerServingStatus == NOT_SERVING (includes heartbeat stopped)
	isReplicaInTopology bool   // PoolerType == REPLICA
	isReadOnly          bool   // default_transaction_read_only = on
	finalLSN            string // Captured LSN before demotion
}

// NewMultiPoolerManager creates a new MultiPoolerManager instance
func NewMultiPoolerManager(logger *slog.Logger, multiPooler *clustermetadatapb.MultiPooler, config *Config) (*MultiPoolerManager, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewMultiPoolerManagerWithTimeout creates a new MultiPoolerManager instance with a custom load timeout
func NewMultiPoolerManagerWithTimeout(logger *slog.Logger, multiPooler *clustermetadatapb.MultiPooler, config *Config, loadTimeout time.Duration) (*MultiPoolerManager, error) {
	_ = "STUB: not implemented"
	// Validate required multiPooler fields
	return nil, nil
}

// MVP validation: fail fast if tablegroup/shard are not the MVP defaults

// Create pgctld gRPC client

// Continue without client - operations that need it will fail gracefully

// Create connection pool manager from config

// We create a dummy context because some unit tests need them.
// These will be overwritten when Open gets called.

// shutdownCtx is independent of ctx: ctx is recreated on every Open(),
// while shutdownCtx exists for the lifetime of the manager and is
// cancelled exactly once, by GracefulShutdown. Background root is
// intentional: this ctx must outlive any Open()/Close() cycle so
// long-lived stream subscribers can keep watching it.

// Load consensus state from disk. Missing file means term=0 (new node), which is fine.
// Only actual read/parse errors fail the constructor.

// Create the query service controller with the pool manager.
// Get the drain grace period from connpool config (0 means use default).

// The health streamer must wait for the query server to update its type before
// broadcasting SERVING transitions, so the gateway doesn't discover the new
// primary before the pooler is ready to accept requests for that type.

// Create the serving state manager with the query service and health streamer as initial components.
// The ReplTracker is registered later when heartbeat is started.

// Register pgBackRest health metrics.

// internalQueryService returns the InternalQueryService for executing queries via the connection pool.
func (pm *MultiPoolerManager) internalQueryService() executor.InternalQueryService {
	_ = "STUB: not implemented"
	return *new(executor.InternalQueryService)
}

// query executes a query using the internal query service and returns the result.
// This is a convenience method for internal manager operations.
func (pm *MultiPoolerManager) query(ctx context.Context, sql string) (*sqltypes.Result, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// exec executes a command that doesn't return rows.
// This is a convenience method for internal manager operations.
func (pm *MultiPoolerManager) exec(ctx context.Context, sql string) error {
	_ = "STUB: not implemented"
	return nil
}

// queryArgs executes a parameterized query using the internal query service and returns the result.
// This is a convenience method for internal manager operations that helps prevent SQL injection.
func (pm *MultiPoolerManager) queryArgs(ctx context.Context, sql string, args ...any) (*sqltypes.Result, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// execArgs executes a parameterized command that doesn't return rows.
// This is a convenience method for internal manager operations that helps prevent SQL injection.
func (pm *MultiPoolerManager) execArgs(ctx context.Context, sql string, args ...any) error {
	_ = "STUB: not implemented"
	return nil
}

// Open opens the database connections and starts background operations.
// This operation is infallible - if connection pools fail to open, queries will fail
// gracefully at query time rather than preventing the manager from opening.
// Open is idempotent and safe to call multiple times.
func (pm *MultiPoolerManager) Open() { _ = "STUB: not implemented"; return }

// Start background PostgreSQL monitoring and auto-recovery. prevState
// persists between ticks so that broadcastHealth fires only on transitions
// in postgres running state, not every tick.

// Broadcast postgres health transitions so orchestrators learn
// about changes immediately without waiting for the next 30-second
// heartbeat. This is especially important for:
//   - postgres going down: allows PrimaryIsDeadAnalyzer to detect failure promptly
//   - postgres coming back up: allows FixReplication to see IsInitialized=true quickly

// Start topology publisher goroutine to eventually-consistently sync state to etcd.

// Start health heartbeat goroutine and transition to SERVING.
// SetState notifies all components (query service, heartbeat, health streamer).

// Pause temporarily closes the manager for maintenance operations that require
// exclusive database access (e.g., pg_rewind). Returns a resume function that
// MUST be called to reopen the manager.
//
// The resume function is safe to call multiple times (idempotent). This allows
// using both defer and explicit calls:
//
//	resume := pm.Pause()
//	defer resume()  // Guarantees cleanup
//	// ... perform maintenance ...
//	resume()  // Explicit resume at the right time
//	// defer will call resume() again safely
//
// Note: Pause() cancels the manager's context, but Open() creates a fresh one.
func (pm *MultiPoolerManager) Pause() (resume func()) { _ = "STUB: not implemented"; return nil }

// Shutdown permanently closes the database connection and stops background operations.
// Use this for final cleanup when the manager will no longer be used.
// Unlike Pause(), Shutdown does not return a resume function, signaling permanent closure.
// Safe to call multiple times and safe to call even if never opened.
func (pm *MultiPoolerManager) Shutdown() { _ = "STUB: not implemented"; return }

// closeLocked performs the actual close operation.
// Returns true if the manager was open and is now closed, false if it was already closed.
// Caller should NOT hold pm.mu - this function acquires it.
// Always cancels the context - Open() will create a fresh one if reopened.
func (pm *MultiPoolerManager) closeLocked(logMessage string) bool {
	_ = "STUB: not implemented"
	return false
}

// Transition to NOT_SERVING before closing resources. This notifies all
// components: query service rejects queries, heartbeat stops, health
// streamer broadcasts NOT_SERVING to subscribers.

// startHeartbeat starts the replication tracker and syncs it to the current serving state.
// The heartbeat writer/reader mode is determined by the multipooler record (the source of truth),
// not by querying the database directly. If the type later changes (e.g., via promotion or
// topology load), StateManager.SetState will notify the replTracker.
func (pm *MultiPoolerManager) startHeartbeat(ctx context.Context, shardID []byte, poolerID string) error {
	_ = "STUB: not implemented"
	// Create the replication tracker using the executor's InternalQueryService
	return nil
}

// Register with StateManager and sync to current state. This ensures the
// heartbeat writer starts for PRIMARY or the reader starts for REPLICA,
// based on whatever state the StateManager currently holds.

// startPubSubListener creates the shared LISTEN/NOTIFY listener and registers
// it with the state manager. The listener runs only when PRIMARY+SERVING.
func (pm *MultiPoolerManager) startPubSubListener(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// QueryServiceControl returns the query service controller.
// This follows the TabletManager pattern of exposing the controller.
func (pm *MultiPoolerManager) QueryServiceControl() poolerserver.PoolerController {
	_ = "STUB: not implemented"

	// openConnectionsLocked opens database connections and initializes connection-related components.
	// This operation is infallible - connection pool failures are handled gracefully at query time.
	// Caller must hold pm.mu.
	// This is symmetric to closeConnectionsLocked and used by both Open() and reopenConnections().
	return *new(poolerserver.PoolerController)
}

func (pm *MultiPoolerManager) openConnectionsLocked() {
	_ = "STUB: not implemented"
	// Open connection pool manager
	return
}

// Open connection pool manager

// When no Unix socket is configured, fall back to a TCP dial against
// the multipooler's own hostname. Postgres is colocated with pgctld on
// the same host, so the multipooler's hostname always points at it.

// Apply libpq-style TLS settings on the multipooler → postgres leg.
// TLS is honored only on TCP dials; Unix-socket connections always run
// plaintext, matching libpq behavior.
//
// Both ParseSSLMode and BuildTLSConfig already ran successfully during
// startup validation (multipooler.Init → ConnPoolConfig.ValidatePGSSL),
// so any error here would indicate the cert files were tampered with
// after startup. Treat that as fatal-by-strict: keep the requested
// sslMode but leave TLSConfig nil, which makes every dial fail
// explicitly at negotiateSSL with "TLS config is nil but sslmode
// requested SSL" rather than silently downgrading to plaintext.

// strict sentinel; any TCP dial errors out

// Create sidecar schema and start heartbeat before opening query service controller
// This ensures the schema exists before queries can be served

// TODO: populate shard ID
// default shard ID

// Use the multipooler name from serviceID as the pooler ID

// Schema creation is now handled by multiorch during bootstrap initialization
// Do not auto-create schema when connecting to postgres

// Don't fail the connection if heartbeat fails

// Start PubSub listener for LISTEN/NOTIFY support.

// closeConnectionsLocked closes the connection pool manager and query service controller
// without canceling the main context. Caller must hold pm.mu.
// This is used by reopenConnections() during auto-restore to avoid canceling
// the startup context that WaitUntilReady is waiting on.
func (pm *MultiPoolerManager) closeConnectionsLocked() {
	_ = "STUB: not implemented"
	// Close resources (safe to call even if nil/never opened)
	return
}

// Close connection pool manager

// reopenConnections closes and reopens database connections without canceling
// the manager's context. This is used to refresh stale connection pool file
// descriptors after PostgreSQL has been restarted, without disrupting contexts
// derived from pm.ctx (e.g., during auto-restore at startup).
func (pm *MultiPoolerManager) reopenConnections(_ context.Context) {
	_ = "STUB: not implemented"
	return
}

// GetState returns the current state of the manager
func (pm *MultiPoolerManager) GetState() ManagerState {
	_ = "STUB: not implemented"
	return *new(ManagerState)
}

// GetStateAndError returns the current manager state and error (used for testing)
func (pm *MultiPoolerManager) GetStateAndError() (ManagerState, error) {
	_ = "STUB: not implemented"
	return *new(ManagerState), nil
}

// stanzaName returns the pgbackrest stanza name
func (pm *MultiPoolerManager) stanzaName() string {
	_ = "STUB: not implemented"

	// pgbackrestCmd builds a pgbackrest executil.Cmd with PGPASSFILE set so
	// pgbackrest can authenticate against the local PostgreSQL instance without
	// exposing the password in the process environment.
	return ""
}

func (pm *MultiPoolerManager) pgbackrestCmd(ctx context.Context, args ...string) *executil.Cmd {
	_ = "STUB: not implemented"
	return nil
}

// getPgCtldClient returns the pgctld gRPC client
func (pm *MultiPoolerManager) getPgCtldClient() pgctldpb.PgCtldClient {
	_ = "STUB: not implemented"
	return *

	// getPoolerType returns the pooler type from the multipooler record
	new(pgctldpb.PgCtldClient)
}

func (pm *MultiPoolerManager) getPoolerType() clustermetadatapb.PoolerType {
	_ = "STUB: not implemented"
	return *new(clustermetadatapb.PoolerType)
}

// shardKey returns a ShardKey identifying this pooler's shard.
func (pm *MultiPoolerManager) shardKey() *clustermetadatapb.ShardKey {
	_ = "STUB: not implemented"
	return nil
}

// checkReady returns an error if the manager is not in Ready state
func (pm *MultiPoolerManager) checkReady() error { _ = "STUB: not implemented"; return nil }

// checkPoolerType verifies that the pooler matches the expected type
func (pm *MultiPoolerManager) checkPoolerType(expectedType clustermetadatapb.PoolerType, operationName string) error {
	_ = "STUB: not implemented"
	return nil
}

// getCurrentTermNumber returns the current consensus term number.
func (pm *MultiPoolerManager) getCurrentTermNumber(ctx context.Context) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// checkReplicaGuardrails verifies that the pooler is a REPLICA and PostgreSQL is in recovery mode
// This is a common guardrail for replication-related operations on standby servers
func (pm *MultiPoolerManager) checkReplicaGuardrails(ctx context.Context) error {
	_ = "STUB: not implemented"
	// Guardrail: Check pooler type - only REPLICA poolers can perform replication operations
	return nil
}

// Guardrail: Check if the PostgreSQL instance is in recovery (standby mode)

// checkPrimaryGuardrails verifies that PostgreSQL is not in recovery mode.
// This is the canonical guardrail for primary-only operations.
func (pm *MultiPoolerManager) checkPrimaryGuardrails(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// setStateError sets the manager state to error with the given error message
// Must be called without holding the mutex
func (pm *MultiPoolerManager) setStateError(err error) { _ = "STUB: not implemented"; return }

// Signal that we've reached a terminal state

// Already closed

// checkAndSetReady checks if all required resources are loaded and sets state to ready if so
// Must be called without holding the mutex
func (pm *MultiPoolerManager) checkAndSetReady() { _ = "STUB: not implemented"; return }

// Signal that we've reached ready state

// Already closed

// Set initial leader observation from the highest known rule.
// commonconsensus.LeaderTerm returns 0 unless the rule names us as the
// leader, so publishing serviceID here is safe.

// loadMultiPoolerFromTopo loads the multipooler record from topology asynchronously
// TODO(sougou): Simplify: We actually just have to verify that we were able to write the record
// to the topo.
func (pm *MultiPoolerManager) loadMultiPoolerFromTopo() {
	_ = "STUB: not implemented"
	// Validate ServiceID is not nil
	return
}

// Set timeout for the entire loading process

// Will retry with backoff

// Successfully loaded multipooler record
// Now load the backup location from the database topology

// Validate and parse backup configuration

// Verify we can compute the full backup path

// Generate pgbackrest client config now that we have backup location.
// pgctld already validates the pgbackrest version at startup; we don't
// need to repeat the check here, since pgctld and multipooler are
// co-located and share the same pgbackrest binary.

// PgPassword() returns the password resolved at startup (file →
// env) and an ok flag. !ok means ResolvePgPassword never ran
// successfully — surface that via setStateError so the manager
// goroutine bails out cleanly instead of writing an empty pgpass
// file that fails auth later.

// Write a pgpass file so pgbackrest can authenticate against PostgreSQL
// without exposing the password via PGPASSWORD in the process
// environment. The pgbackrest/ directory is guaranteed to exist after
// WriteClientConfig. A pgpass file is required for pgbackrest to work
// with password authentication, and we cannot use a ephemeral file in a
// temp directory because pgbackrest needs to be able to read it after
// we exec (and the temp file would be cleaned up when closed).

// Notify all components of the pooler type loaded from topology.

// Note: restoring from backup (for replicas) happens in a separate goroutine

// validateAndUpdateTerm validates the request term against the current term following Consensus rules.
// Returns an error if the request term is stale (less than current term).
// If the request term is higher, it updates the term in pgctld and the cache.
// If force is true, validation is skipped.
func (pm *MultiPoolerManager) validateAndUpdateTerm(ctx context.Context, requestTerm int64, force bool) error {
	_ = "STUB: not implemented"
	return nil

	// Skip validation if force is set
}

// If request term == current term: ACCEPT (same term, execute)
// If request term < current term: REJECT (stale request)
// If request term > current term: UPDATE term and ACCEPT (new term discovered)

// Request has stale term, reject

// Request has newer term, update our term

// Update term atomically (resets accepted leader)

// If requestTerm == currentCachedTerm, just continue (same term is OK)

// validateTerm validates that the request term is not stale (>= current term).
// Unlike validateAndUpdateTerm, this does NOT update the term.
// This is used when we want to defer the term update until after an operation succeeds.
// If force is true, validation is skipped.
func (pm *MultiPoolerManager) validateTerm(ctx context.Context, requestTerm int64, force bool) error {
	_ = "STUB: not implemented"
	return nil

	// Skip validation if force is set
}

// Check if consensus term has been initialized (term 0 means uninitialized)

// Reject stale requests

// Accept equal or newer terms

// updateTermIfNewer updates the consensus term if the provided term is newer than current.
// This is used to decouple term validation from term update, allowing updates to occur
// only after an operation succeeds.
func (pm *MultiPoolerManager) updateTermIfNewer(ctx context.Context, requestTerm int64) error {
	_ = "STUB: not implemented"
	return nil
}

// Already at or past this term

// validateTermExactMatch validates that the request term exactly matches the current term.
// Unlike validateAndUpdateTerm, this does NOT update the term automatically.
// This is used for Promote to ensure the node was properly recruited before promotion.
func (pm *MultiPoolerManager) validateTermExactMatch(ctx context.Context, requestTerm int64, force bool) error {
	_ = "STUB: not implemented"
	return nil

	// Skip validation if force is set
}

// Check if consensus term has been initialized

// Require exact match - do not update term automatically

// checkDemotionState checks the current state to determine what steps remain
func (pm *MultiPoolerManager) checkDemotionState(ctx context.Context) (*demotionState, error) {
	_ = "STUB: not implemented"
	return nil,

		// Check topology state
		nil
}

// Check if PostgreSQL is in recovery mode (canonical way to check if read-only)

// Capture current LSN

// setNotServing transitions the pooler to NOT_SERVING status during demotion.
// This uses the StateManager to coordinate:
//   - Query service rejects all queries
//   - Heartbeat writer is stopped
//   - Multipooler record is updated
//
// After this, topology is synced to persist the state change.
func (pm *MultiPoolerManager) setNotServing(ctx context.Context, state *demotionState) error {
	_ = "STUB: not implemented"
	return nil
}

// Use the serving state manager to transition components.
// This updates query service, heartbeat, and the multipooler record.

// Notify the topology publisher of the new state. The write to etcd happens
// asynchronously so that a temporarily unreachable etcd does not block demotion.

// restartPostgresAsStandby restarts PostgreSQL as a standby server
// This creates standby.signal and restarts PostgreSQL via pgctld
//
// TODO: require callers to declare whether this restart is a "clean" or
// "unexpected" demote. A clean demote (graceful failover handoff, known
// consistent WAL) should leave rewindPending=false. An unexpected demote
// (crash, external pg_demote, monitor-driven restart after an unknown
// shutdown) should set rewindPending=true so that the next standby-side
// operation (SetTermPrimary's standby branch, remedialActionFixPrimaryConnInfo,
// or self-rewind detection) routes through pg_rewind dry-run before
// trusting local WAL. Today the only setter is emergencyDemoteLocked,
// which leaves several transition paths under-defended.
func (pm *MultiPoolerManager) restartPostgresAsStandby(ctx context.Context, state *demotionState) error {
	_ = "STUB: not implemented"
	return nil
}

// Use default timeout
// Use default port

// Create standby.signal before restart

// Reopen connections after restart

// Wait for database connection to be ready after restart

// Verify server is in recovery mode (standby)

// getActiveWriteConnections returns connections that are performing write operations
func (pm *MultiPoolerManager) getActiveWriteConnections(ctx context.Context) ([]int32, error) {
	_ = "STUB: not implemented"
	// Query for connections doing write operations
	// Note: this is temporary, we can refactor this once we
	// have the query pool. Thinking that we should have a
	// specific user for the write pool and we can kill all connections
	// associated with that user.
	return nil, nil
}

// terminateWriteConnections terminates connections performing write operations
func (pm *MultiPoolerManager) terminateWriteConnections(ctx context.Context) (int32, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Terminate each write connection

// drainWriteActivity monitors for write activity during emergency demotion.
// During the drain, it monitors for write activity every 100ms.
// If 2 consecutive checks show no writes, exits early.
func (pm *MultiPoolerManager) drainWriteActivity(ctx context.Context, drainTimeout time.Duration) error {
	_ = "STUB: not implemented"
	// Monitor for write activity during drain
	return nil
}

// Check for write activity

// Reset on error

// Reset counter

// No writes detected

// checkPromotionState checks the current state to determine what steps remain
func (pm *MultiPoolerManager) checkPromotionState(ctx context.Context, syncReplicationConfig *multipoolermanagerdatapb.ConfigureSynchronousReplicationRequest) (*promotionState, error) {
	_ = "STUB: not implemented"
	return nil,

		// Check PostgreSQL promotion state
		nil
}

// Get current primary LSN

// Check topology state

// Default: if no sync config requested, consider it as matching (no requirements to check)

// Check sync replication state if config was provided

// Node is a standby being promoted - it doesn't have sync replication configured yet

// promoteStandbyToPrimary calls pg_promote() and waits for promotion to complete
func (pm *MultiPoolerManager) promoteStandbyToPrimary(ctx context.Context, state *promotionState) error {
	_ = "STUB: not implemented"
	// Return early if already promoted
	return nil
}

// Call pg_promote() to promote standby to primary

// Broadcast immediately so subscribers (multiorch) see PROMOTING server
// status before the periodic health stream interval fires. Without this,
// the flag may be set and cleared within a single interval, making it
// invisible to subscribers. We reset the promotionInProgress flag and
// broadcast again after promotion completes to ensure the full window is
// visible.

// TODO: this defer fires before configureReplicationAfterPromotion and
// rules.updateRule in the caller, so multiorch sees PRIMARY status while sync
// replication is not yet configured and rule history has not been written. If
// we want the PROMOTING window to cover the full Promote RPC (including the
// sync standby ack gate), the defer should move to the caller instead.

// Wait for promotion to complete: pg_is_in_recovery()=false AND postgres_ready=true.
// Keeping promotionInProgress set until postgres_ready ensures multiorch suppresses
// PrimaryIsDead for the full window — including the gap between pg_is_in_recovery()=false
// and postgres actually accepting connections.

// Clear primary_conninfo after promotion to prevent accidental replication on restart

// Log but don't fail - promotion already succeeded

// waitForPromotionComplete polls until the node has left recovery mode AND postgres
// is accepting connections. Both conditions are required: pg_is_in_recovery()=false
// confirms the WAL-level promotion, and postgres_ready=true confirms clients can
// connect. Clearing promotionInProgress only when both are true ensures multiorch's
// PrimaryIsDeadAnalyzer suppression window matches the full visibility gap.
func (pm *MultiPoolerManager) waitForPromotionComplete(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// updateTopologyAfterPromotion updates the pooler type in topology from REPLICA to PRIMARY
func (pm *MultiPoolerManager) updateTopologyAfterPromotion(ctx context.Context, state *promotionState) error {
	_ = "STUB: not implemented"
	// Return early if already updated
	return nil
}

// Use the serving state manager to transition components (query service, heartbeat, health streamer)
// and update the multipooler record. The serving status stays SERVING during promotion.

// Notify the topology publisher of the new state. The write to etcd happens
// asynchronously so that a temporarily unreachable etcd does not block promotion.

// configureReplicationAfterPromotion applies synchronous replication configuration
func (pm *MultiPoolerManager) configureReplicationAfterPromotion(ctx context.Context, state *promotionState, syncReplicationConfig *multipoolermanagerdatapb.ConfigureSynchronousReplicationRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// No configuration requested

// Return early if already configured

// Use the locked version since we're already holding the action lock from Promote

// ReplicationLag returns the current replication lag from the heartbeat reader
func (pm *MultiPoolerManager) ReplicationLag(ctx context.Context) (time.Duration, error) {
	_ = "STUB: not implemented"
	return *new(time.Duration), nil
}

// Start initializes the MultiPoolerManager
func (pm *MultiPoolerManager) Start(senv *servenv.ServEnv) {
	_ = "STUB: not implemented"
	// Open the database connections, connection pool manager, and start background operations
	// TODO: This should be managed by a proper state manager (like tm_state.go)
	return
}

// Register the SIGTERM-driven graceful shutdown sequence. Runs as an
// OnTermSync hook so it is bounded by the lameduck window and completes
// before OnClose hooks (topology unregister) fire.

// Start loading multipooler record from topology asynchronously

// Block until manager is ready or error before registering gRPC services
// Use load timeout from manager configuration

// Register manager gRPC services

// WaitUntilReady blocks until the manager reaches Ready or Error state, or
// the context is cancelled. Returns nil if Ready, or an error if Error state
// or context cancelled. This should be called after Start() to ensure
// initialization is complete before accepting RPC requests.
//
// Thread-safety: This method waits on a channel that is closed when the state
// changes to Ready or Error, allowing efficient notification without polling.
func (pm *MultiPoolerManager) WaitUntilReady(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// State has changed to Ready or Error, check which one

// This shouldn't happen - channel was closed but state isn't terminal

// postgresState represents the state of PostgreSQL for monitoring
type postgresState struct {
	pgctldAvailable          bool
	dirInitialized           bool
	postgresRunning          bool
	backupsAvailable         bool
	isPrimary                bool
	bootstrapSentinelPresent bool
	// primaryTerm is the coordinator term at which this pooler is the primary
	// per the highest known rule. 0 if we are not the primary for that rule.
	primaryTerm int64
}

// postgresStateEqual reports whether two postgresState values are identical.
func postgresStateEqual(a, b postgresState) bool { _ = "STUB: not implemented"; return false }

// remedialAction represents actions the postgres monitor can take
type remedialAction int

const (
	remedialActionNone remedialAction = iota
	remedialActionStartPostgres
	remedialActionRestoreFromBackup
	remedialActionAdjustTypeToPrimary
	remedialActionAdjustTypeToReplica
	remedialActionCreateFirstBackup
	remedialActionReconcileGUC
	// remedialActionFixPrimaryConnInfo means postgres is in recovery and the
	// topology says REPLICA, but primary_conninfo doesn't match the primary
	// recorded in ConsensusState.ReplicationPrimary (the most recent
	// SetTermPrimary/Propose). Reconciles the GUC so this replica points at the right
	// primary regardless of how it got out of sync (failed SetTermPrimary apply,
	// hand edit, snapshot restore, etc.).
	remedialActionFixPrimaryConnInfo
)

// monitorPostgresIteration performs one iteration of PostgreSQL monitoring.
// Returns the discovered postgres state on success, or an error if the state
// could not be determined. The caller is responsible for transition detection
// and broadcasting health updates.
func (pm *MultiPoolerManager) monitorPostgresIteration(ctx context.Context) (postgresState, error) {
	_ = "STUB: not implemented"
	return *new(postgresState), nil
}

// Wait for manager to be ready

// Skip all action while awaiting a rewind after emergency demotion.

// Discover current state

// Log and skip this tick; the next iteration will retry. A persistent
// failure keeps the error loud rather than silently triggering the wrong
// remediation. pgctld unavailability gets its dedicated reason code so
// the monitor's log-dedup path behaves as before.

// Determine what remediation is needed

// No action needed - just log status

// Acquire action lock before taking remedial action

// Re-check rewindPending after acquiring the lock: EmergencyDemote sets this flag
// while holding the lock, so we may have been waiting while it demoted the node.

// Re-verify state after acquiring lock (conditions may have changed)

// Re-determine action based on current state

// Take remedial action with lock held

// discoverPostgresState discovers the current state of PostgreSQL. Returns an
// error only when a probe fails in a way that leaves the state genuinely
// ambiguous (e.g. a sentinel stat failing for reasons other than NotExist);
// callers must refuse to take remedial action in that case. pgctld being
// unavailable is not such a case — it is represented as pgctldAvailable=false.
func (pm *MultiPoolerManager) discoverPostgresState(ctx context.Context) (postgresState, error) {
	_ = "STUB: not implemented"
	return *

	// Check if pgctld client is available
	new(postgresState), nil
}

// All fields remain false

// Get status from pgctld. On failure return both the state (with
// pgctldAvailable=false) and the error so the caller can log the
// underlying cause while still reading the unavailability flag.

// Check if directory is initialized

// Check if Postgres is running

// Lock-free first pass from the monitor: use the inconsistent read,
// which falls back to the cached rule when postgres is unreachable.

// Check if backups are available (only if directory not initialized)

// We can't tell whether a stale sentinel needs handling. Surface as an
// error so the monitor skips this tick; the operator should investigate.

// primaryTermLocked returns the coordinator term of the pooler's current
// committed rule if this pooler is the primary per that rule. Uses a
// consistent consensus status read and therefore requires the action lock.
// Returns (0, nil) when the rule does not name this pooler as primary.
// Returns (0, err) only when the consensus status cannot be read at all —
// callers that need to distinguish "confirmed not primary" from "unknown"
// must inspect the error.
//
// Callers that cannot hold the action lock should read
// getInconsistentConsensusStatus themselves and pass the result to
// consensus.LeaderTerm.
func (pm *MultiPoolerManager) primaryTermLocked(ctx context.Context) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// setMonitorReason sets the current monitor state reason and logs on state changes.
// This avoids log spam during repeated monitor iterations with the same state.
func (pm *MultiPoolerManager) setMonitorReason(ctx context.Context, reason, message string) {
	_ = "STUB: not implemented"
	return
}

// primaryConnInfoDiffersFromRecorded returns true when this pooler has been
// informed about a primary (via SetTermPrimary or Propose) and the live primary_conninfo
// in postgres doesn't match the recorded primary's contact info. Returns false
// when there's nothing to compare against, when we couldn't read the GUC, or
// when the recorded primary names this pooler itself.
//
// Returns false when the recorded primary's rule is revoked by our recorded
// revocation: a Recruit that's already advanced revoked_below_term has
// deliberately cleared primary_conninfo, and the cached "recorded primary" is
// stale until the next SetTermPrimary/Propose updates it. Without this gate, the
// monitor would race the Recruit/Propose flow by restoring conninfo to the
// just-revoked primary, which then causes Propose to refuse with
// "primary_conninfo is set".
//
// Used by the postgres monitor to decide whether to trigger
// remedialActionFixPrimaryConnInfo on each tick.
func (pm *MultiPoolerManager) primaryConnInfoDiffersFromRecorded(_ postgresState) bool {
	_ = "STUB: not implemented"
	// Don't detect drift we can't fix: when StopReplication has set the
	// manual-stop flag, setPrimaryConnInfoLocked refuses every conninfo
	// rewrite until StartReplication clears it. Detecting drift anyway would
	// fire the reconciliation action on every tick and log a noisy
	// FAILED_PRECONDITION error each time.
	return false
}

// Skip if the recorded rule names this pooler as the leader — that's the
// primary-side case, out of scope for replica-conninfo reconciliation.

// Skip if the recorded rule is revoked. The cached primary is from before
// the current revocation took effect; restoring conninfo to it would race
// the Recruit/Propose flow that's mid-flight (see function doc).

// Use a short deadline so a slow query never blocks the monitor tick.

// Conservative: don't trigger reconciliation we can't verify.

// Unparsable conninfo is itself drift worth fixing.

// determineRemedialAction decides what action to take based on discovered state.
// This is pure decision logic with no side effects.
func (pm *MultiPoolerManager) determineRemedialAction(ctx context.Context, currentState postgresState) remedialAction {
	_ = "STUB: not implemented"
	// Pgctld unavailable: No action possible
	return *new(remedialAction)
}

// Postgres is running: Check if pooler type needs adjustment

// Postgres is standby and type is already REPLICA, but check if the resignation
// signal needs to be (re-)published. This handles the case where the signal was
// lost after a process restart following EmergencyDemote.

// Drift check: replica is otherwise healthy but its primary_conninfo
// may not match what we've been told via SetTermPrimary/Propose. Reconcile
// to the recorded ReplicationPrimary if there's a mismatch.

// TODO: self-rewind detection. A replica may need pg_rewind even
// when it was never primary — phantom transactions can leak in
// (e.g. via a brief sync-replication ack that got rolled back on
// the primary). The old consensus flow let orch re-issue an
// explicit rewind whenever it suspected one; the new flow's
// SetTermPrimary is idempotent and won't repeat work, so the monitor
// needs to self-detect stuck replication. Check
// pg_stat_wal_receiver.status: if not "streaming" for
// >stuckThreshold AND we have a recorded primary, treat as
// suspected divergence — set rewindPending=true so the next
// remedialActionFixPrimaryConnInfo iteration runs
// pg_rewind dry-run before re-establishing replication. Cheap
// when no divergence, conclusive when there is.

// Pooler type already matches; check for a stale GUC that needs re-applying.
// Only reconcile the GUC when actually running as primary: synchronous_standby_names
// has no effect on a standby, and setting it there leaks state.

// A sentinel from a prior first-backup attempt means bootstrap crashed
// mid-flight. Any on-disk pg_data is stale — force the create-first-backup
// path so createFirstBackupAndInitializeLocked can clean up and retry.

// Postgres not running: Try to start or restore

// Directory not initialized and no backups: try to create the first backup

// takeRemedialAction executes the specified remedial action.
// Caller must hold the action lock.
func (pm *MultiPoolerManager) takeRemedialAction(ctx context.Context, action remedialAction, state postgresState) {
	_ = "STUB: not implemented"
	// Assert that the action lock is held
	return
}

// No action to take

// Signal voluntary resignation so the coordinator can trigger an immediate
// election. Use the primary_term (the term at which we were elected) since
// the coordinator uses this to decide whether the signal is still active.

// TODO: when rewindPending=true (an unexpected demotion happened
// without a follow-up pg_rewind), just setting primary_conninfo is
// not enough — the WAL receiver will fail to start due to timeline
// divergence. Route through demoteStalePrimaryLocked instead, which
// runs pg_rewind dry-run (cheap when there's no divergence) before
// re-establishing replication. This would let the monitor self-heal
// a stuck-replica scenario without waiting for orch's
// FixReplicationAction to issue a RewindToSource RPC.

/* stopReplicationBefore */ /* startReplicationAfter */

// Honour the in-memory flag set by tests and demos to suppress auto-restart
// during controlled failovers.

// Another pooler created the backup just before we acquired the lease.
// Restore immediately rather than waiting for the next monitor iteration.

// hasCompleteBackups checks if there are any complete backups available
func (pm *MultiPoolerManager) hasCompleteBackups(ctx context.Context) bool {
	_ = "STUB: not implemented"
	// Get list of backups
	return false
}

// Filter to only complete backups

// startPostgres starts PostgreSQL via pgctld
//
// TODO: preemptive-rewind safety. A monitor-driven restart can't know what
// happened between the previous run and now — postgres may have crashed
// mid-write as primary, or may have been killed externally. The safe default
// is to come back as a standby with rewindPending=true so that the next
// SetTermPrimary/Propose/standby-conninfo path routes through demoteStalePrimaryLocked
// (which runs pg_rewind dry-run; cheap when there's no divergence) before
// trusting local WAL. This bears on the broader self-rewind plan:
//   - replicas with phantom transactions: orch sends an explicit
//     RewindToSource RPC today; a future change should let the local monitor
//     detect stuck replication and self-heal without needing orch in the loop.
//   - primaries demoted unexpectedly (crash, SIGKILL, external pg_demote):
//     the restart-as-standby helper should require callers to declare
//     "clean" vs "unexpected" so an unexpected transition can set
//     rewindPending up front, increasing the odds of fast convergence once
//     a new leader is announced.
func (pm *MultiPoolerManager) startPostgres(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Reopen connections after postgres restart to replace stale socket FDs.
// Only when connection pool is initialized (the manager may not have
// connection infrastructure in unit tests with minimal setup).

// Wait for database connection to be ready

// restoreAndStartPostgres restores from backup and starts PostgreSQL.
// This is used by MonitorPostgres for auto-restore functionality.
// Caller must hold the action lock.
func (pm *MultiPoolerManager) restoreAndStartPostgres(ctx context.Context) error {
	_ = "STUB: not implemented"
	// Re-check status to ensure conditions haven't changed
	// (e.g., another process may have initialized or started postgres while we waited for lock)
	return nil
}

// If directory is now initialized, skip restore

// If status check fails, continue with restore attempt

// Get the latest complete backup

// Filter to only complete backups

// Use the latest complete backup (last in the list)

// Perform the restore
