// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package manager

import (
	"context"

	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	"github.com/multigres/multigres/go/tools/executil"
)

// pgBackRestConfig returns the path to the pgbackrest.conf generated by multipooler
// during startup. The config is generated in loadMultiPoolerFromTopo when backup
// location is loaded from topology.
func (pm *MultiPoolerManager) pgBackRestConfig() (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Backup performs a backup
func (pm *MultiPoolerManager) Backup(ctx context.Context, forcePrimary bool, backupType string, jobID string, overrides map[string]string) (string, error) {
	_ = "STUB: not implemented"
	// We can't proceed without the topo, which is loaded asynchronously at startup
	return "", nil
}

// Acquire the local action lock first to prevent deadlock with the distributed lease.

// Acquire the distributed backup lease via steal protocol.
// If another pooler holds the lease, revoke it and acquire a new one.
// This ensures the most recent backup request always wins.

// backupLocked performs a backup. Caller must hold the action lock and backup lease.
func (pm *MultiPoolerManager) backupLocked(ctx context.Context, forcePrimary bool, backupType string, jobID string, overrides map[string]string) (retBackupID string, retErr error) {
	_ = "STUB: not implemented"
	return "", nil
}

// backupLockedInner performs the backup steps inside the parent "backup" span.
// Caller must hold both the action lock and the backup lease.
func (pm *MultiPoolerManager) backupLockedInner(ctx context.Context, forcePrimary bool, backupType string, jobID string, overrides map[string]string) (retBackupID string, retErr error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Check if backup is allowed on primary

// Get path to pgbackrest.conf generated by pgctld

// Use provided job_id or generate one (same format as multiadmin)

// Validate parameters and get pgbackrest type

// Emit Started now that we have a correlation ID and parameters are valid.
// BackupName uses effectiveJobID since the actual pgbackrest label isn't assigned yet.

// retBackupID is set to the actual pgbackrest label by the success return.

// Execute pgbackrest backup command

// Get pg2 args for replica backups (empty for primary).
// For TLS mode, we need the PRIMARY's pgBackRest port, not the local one.
// Pass forcePrimary through so that a freshly-initialised node (type=UNKNOWN)
// that is acting as a primary can still do a local backup without pg2 args.

// Reject backups with empty table_group or shard to prevent corrupt metadata.
// Backups missing these annotations would be silently skipped by replicas
// during restore, causing them to fall back to older backups.

// Add multipooler_id, pooler_type, and job_id annotations for unique identification

// Execute backup with progress logging

// Find the backup ID by querying pgbackrest info with our unique annotations

// Verify the backup to ensure it's valid

// Execute verify with progress logging

// TODO: use `pgbackrest info` to verify that the database pages from the backed up
// Postgres cluster pass checksum validation.

// RestoreFromBackup restores from a backup to a standby without a data directory.
//
// Requirements:
// - The pooler must be a standby (not a primary)
// - PGDATA must not exist (caller's responsibility to stop PostgreSQL and remove it)
//
// This function will:
// 1. Execute pgbackrest restore to recreate PGDATA
// 2. Start PostgreSQL in standby mode using Restart (which handles the not-running case)
// 3. Reopen the pooler manager to establish fresh connections
func (pm *MultiPoolerManager) RestoreFromBackup(ctx context.Context, backupID string) error {
	_ = "STUB: not implemented"
	return nil
}

// We can't proceed without the topo, which is loaded asynchronously at startup

// Acquire the action lock to ensure only one mutation runs at a time

// restoreFromBackupLocked performs the restore. Caller must hold the action lock.
func (pm *MultiPoolerManager) restoreFromBackupLocked(ctx context.Context, backupID string) (retErr error) {
	_ = "STUB: not implemented"
	return nil
}

// Check that this is a standby, not a primary

// Check that PGDATA doesn't exist (caller must remove it before restore)

// Restore the backup

// Reconfigure archive_command to use this pooler's local pgbackrest.conf
// After restore, postgresql.auto.conf contains archive_command pointing to the
// primary's pgbackrest.conf path. Each pooler needs its own config path.

// Clear the in-memory leader observation. The restored PGDATA may have been
// from a different point in time, so the previously observed leader may no
// longer be accurate. The term revocation is intentionally preserved: it is
// monotonically increasing and the restore does not change who is allowed to
// lead — only a coordinator with a term >= the revocation term may configure
// this node, which is exactly the right safety property.

// Mark as initialized after successful restore

// Push an immediate health snapshot so the orchestrator learns about
// IsInitialized=true without waiting for the next 30-second heartbeat.

func (pm *MultiPoolerManager) executePgBackrestRestore(ctx context.Context, backupID string) error {
	_ = "STUB: not implemented"
	return nil
}

func (pm *MultiPoolerManager) startPostgreSQLAfterRestore(ctx context.Context, backupID string) error {
	_ = "STUB: not implemented"
	return nil
}

func (pm *MultiPoolerManager) reopenPoolerManager(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Use reopenConnections instead of Pause/Open to avoid canceling pm.ctx.
// This is important during auto-restore at startup where the startup flow
// is waiting on contexts derived from pm.ctx.

// GetBackups retrieves backup information
func (pm *MultiPoolerManager) GetBackups(ctx context.Context, limit uint32) ([]*multipoolermanagerdata.BackupMetadata, error) {
	_ = "STUB: not implemented"
	// We can't proceed without the topo, which is loaded asynchronously at startup
	return nil, nil
}

// Acquire the action lock to ensure only one operation runs at a time

// getBackupsLocked retrieves backup information. Caller must hold the action lock.
func (pm *MultiPoolerManager) getBackupsLocked(ctx context.Context, limit uint32) ([]*multipoolermanagerdata.BackupMetadata, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Apply limit if specified

// listBackups retrieves backup metadata from pgbackrest.
// Caller must hold the action lock.
// pm.mu is NOT required because this function only reads config fields
// (which are immutable after construction) and backupLocation (which is
// set once during startup and never modified).
func (pm *MultiPoolerManager) listBackups(ctx context.Context) ([]*multipoolermanagerdata.BackupMetadata, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Execute pgbackrest info command with JSON output

// Override console logging to prevent contaminating JSON output

// Handle case where stanza doesn't exist yet or config file is missing - return empty list

// Parse JSON output

// Get current pooler's table_group and shard for filtering

// Extract backups from the first stanza (should be the only one)

// Extract table_group, shard, job_id, multipooler_id, and pooler_type from annotations

// Defense-in-depth: skip backups that don't match this pooler's shard.
// This check is not strictly necessary since stanzas are shard-scoped,
// but provides an extra layer of safety.

// Extract final LSN (stop LSN) from backup

// Extract backup size if available

// pgBackRestInfo represents the structure of pgbackrest info JSON output
type pgBackRestInfo struct {
	Name   string             `json:"name"`
	Backup []pgBackRestBackup `json:"backup"`
}

// pgBackRestBackup represents a single backup in the info output
type pgBackRestBackup struct {
	Label      string              `json:"label"`
	Type       string              `json:"type"`
	Error      bool                `json:"error"`
	Timestamp  pgBackRestTimestamp `json:"timestamp"`
	Annotation map[string]string   `json:"annotation,omitempty"`
	LSN        *pgBackRestLSN      `json:"lsn,omitempty"` // LSN range for this backup
	Info       *pgBackRestSizeInfo `json:"info,omitempty"`
}

// pgBackRestSizeInfo represents size information for a backup
type pgBackRestSizeInfo struct {
	Size       uint64                    `json:"size"`       // Original database size in bytes
	Repository *pgBackRestRepositorySize `json:"repository"` // Compressed size in repository
}

// pgBackRestRepositorySize represents repository size info
type pgBackRestRepositorySize struct {
	Size uint64 `json:"size"` // Compressed size in repository in bytes
}

// pgBackRestTimestamp represents backup timestamps
type pgBackRestTimestamp struct {
	Start int64 `json:"start"`
	Stop  int64 `json:"stop"`
}

// pgBackRestLSN represents LSN start/stop positions for a backup
type pgBackRestLSN struct {
	Start string `json:"start"` // e.g., "0/21000028"
	Stop  string `json:"stop"`  // e.g., "0/21000100"
}

// allowBackupOnPrimary checks if a backup operation is allowed on a primary pooler
func (pm *MultiPoolerManager) allowBackupOnPrimary(ctx context.Context, forcePrimary bool) error {
	_ = "STUB: not implemented"
	return nil
}

// validateBackupParams validates the backup type and returns the pgbackrest type mapping
func (pm *MultiPoolerManager) validateBackupParams(backupType, configPath string) (pgBackRestType string, err error) {
	_ = "STUB: not implemented"
	// Validate backup type is provided
	return "", nil
}

// Map to pgbackrest types: full, diff, incr

// Validate required backup configuration

// safeCombinedOutput executes a command and streams its output to avoid blocking.
// This prevents deadlocks when commands produce large amounts of output that
// would fill the internal pipe buffers. Returns combined stdout and stderr.
func safeCombinedOutput(cmd *executil.Cmd) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// scanErr captures a scanner error (e.g. bufio.ErrTooLong for lines
// exceeding the default 64 KiB buffer) so silent truncation surfaces
// to the caller instead of looking like clean EOF. Writes happen
// before the corresponding Done channel closes; the close()-then-
// channel-receive ordering through stdoutDone/stderrDone → lines →
// the consumer loop establishes the happens-before edge that lets
// the caller read these without a separate lock.

// cmd.Wait's exit code is the operational signal, so it takes
// precedence. If the process exited cleanly but a scanner failed
// (e.g. ErrTooLong), surface that so a silently-truncated output
// doesn't look successful.

// findBackupByJobID finds a backup by matching the job_id annotation
//
// This function has to scan the entire backup history to find the backup, but the worst case
// should be manageable, because production deployments should have retention policies that
// trigger pgBackRest to delete older backups.
func (pm *MultiPoolerManager) findBackupByJobID(
	ctx context.Context,
	jobID string,
) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Execute pgbackrest info command with JSON output

// Parse JSON output

// Search for backup with matching annotations

// GetBackupByJobId searches for a backup with the given job_id annotation.
// Returns nil Backup if not found.
func (pm *MultiPoolerManager) GetBackupByJobId(ctx context.Context, jobID string) (*multipoolermanagerdata.BackupMetadata, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// We can't proceed without the topo, which is loaded asynchronously at startup

// Acquire the action lock to ensure only one operation runs at a time

// Get all backups and search for matching job_id
// 0 = no limit

// GetPrimaryAsPg2Args returns pgbackrest CLI arguments for pg2 (primary) configuration.
//
// When backing up from PRIMARY: Returns empty slice - pgBackRest does local backup from pg1.
// When backing up from REPLICA with TLS certs: Returns TLS connection parameters and pg2-path
// (resolved from topology or overrides) to the primary's pgBackRest server.
// When backing up from REPLICA without TLS certs: Returns direct postgres connection parameters (test mode).
//
// Returns error if this is a replica pooler without primary information.
func (pm *MultiPoolerManager) GetPrimaryAsPg2Args(
	ctx context.Context,
	overrides map[string]string,
	forcePrimary bool,
) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Primary poolers (or forced-primary nodes, e.g. during first-backup creation)
// backup locally from pg1 — no pg2 needed.

// Replica poolers MUST have primary info to backup from primary. The
// canonical source is consensusState.ReplicationPrimary, populated by
// every RPC that informs this pooler of a primary (SetTermPrimary, the
// legacy SetPrimaryConnInfo / DemoteStalePrimary, and Propose's leader
// path for the rare self-as-primary case).

// Check if TLS certs are configured to determine mode

// TLS mode: need to get the PRIMARY's pgBackRest port and data dir from topology

// pg2-path is required by pgBackRest even in TLS mode.
// Use the override if provided, otherwise read from topology.

// Local mode: pg2_path override is REQUIRED

// Apply any additional overrides

// runLongCommand executes a long-running command with periodic progress logging.
// Logs progress every 10 seconds. The cmd should be created with exec.CommandContext(ctx, ...)
// to ensure proper cleanup on context cancellation.
func (pm *MultiPoolerManager) runLongCommand(ctx context.Context, cmd *executil.Cmd, operationName string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Create a context for the logging goroutine

// Log progress periodically in background

// Log completion
