// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: multipoolermanagerservice.proto

/*
Package multipoolermanager is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package multipoolermanager

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_MultiPoolerManager_WaitForLSN_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_WaitForLSN_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_StartReplication_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_StartReplication_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_StopReplication_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_StopReplication_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_Status_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_Status_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_Backup_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_Backup_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_RestoreFromBackup_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_RestoreFromBackup_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_GetBackups_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_GetBackups_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_GetBackupByJobId_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_GetBackupByJobId_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_ExpireBackups_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_ExpireBackups_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_SetPostgresRestartsEnabled_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_MultiPoolerManager_SetPostgresRestartsEnabled_0(ctx context.Context, marshaler runtime.Marshaler, server MultiPoolerManagerServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_MultiPoolerManager_ManagerHealthStream_0(ctx context.Context, marshaler runtime.Marshaler, client MultiPoolerManagerClient, req *http.Request, pathParams map[string]string) (MultiPoolerManager_ManagerHealthStreamClient, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(MultiPoolerManager_ManagerHealthStreamClient), *new(runtime.ServerMetadata), nil
}

// RegisterMultiPoolerManagerHandlerServer registers the http handlers for service MultiPoolerManager to "mux".
// UnaryRPC     :call MultiPoolerManagerServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMultiPoolerManagerHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterMultiPoolerManagerHandlerServer(ctx context.Context, mux *runtime.ServeMux, server MultiPoolerManagerServer) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiPoolerManagerHandlerFromEndpoint is same as RegisterMultiPoolerManagerHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMultiPoolerManagerHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiPoolerManagerHandler registers the http handlers for service MultiPoolerManager to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMultiPoolerManagerHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterMultiPoolerManagerHandlerClient registers the http handlers for service MultiPoolerManager
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MultiPoolerManagerClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MultiPoolerManagerClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MultiPoolerManagerClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterMultiPoolerManagerHandlerClient(ctx context.Context, mux *runtime.ServeMux, client MultiPoolerManagerClient) error {
	_ = "STUB: not implemented"
	return nil
}

var (
	pattern_MultiPoolerManager_WaitForLSN_0                 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "WaitForLSN"}, ""))
	pattern_MultiPoolerManager_StartReplication_0           = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "StartReplication"}, ""))
	pattern_MultiPoolerManager_StopReplication_0            = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "StopReplication"}, ""))
	pattern_MultiPoolerManager_Status_0                     = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "Status"}, ""))
	pattern_MultiPoolerManager_Backup_0                     = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "Backup"}, ""))
	pattern_MultiPoolerManager_RestoreFromBackup_0          = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "RestoreFromBackup"}, ""))
	pattern_MultiPoolerManager_GetBackups_0                 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "GetBackups"}, ""))
	pattern_MultiPoolerManager_GetBackupByJobId_0           = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "GetBackupByJobId"}, ""))
	pattern_MultiPoolerManager_ExpireBackups_0              = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "ExpireBackups"}, ""))
	pattern_MultiPoolerManager_SetPostgresRestartsEnabled_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "SetPostgresRestartsEnabled"}, ""))
	pattern_MultiPoolerManager_ManagerHealthStream_0        = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"multipoolermanager.MultiPoolerManager", "ManagerHealthStream"}, ""))
)

var (
	forward_MultiPoolerManager_WaitForLSN_0                 = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_StartReplication_0           = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_StopReplication_0            = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_Status_0                     = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_Backup_0                     = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_RestoreFromBackup_0          = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_GetBackups_0                 = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_GetBackupByJobId_0           = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_ExpireBackups_0              = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_SetPostgresRestartsEnabled_0 = runtime.ForwardResponseMessage
	forward_MultiPoolerManager_ManagerHealthStream_0        = runtime.ForwardResponseStream
)
