// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multipoolermanagerservice.proto

package multipoolermanager

import (
	context "context"

	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiPoolerManager_WaitForLSN_FullMethodName                 = "/multipoolermanager.MultiPoolerManager/WaitForLSN"
	MultiPoolerManager_StartReplication_FullMethodName           = "/multipoolermanager.MultiPoolerManager/StartReplication"
	MultiPoolerManager_StopReplication_FullMethodName            = "/multipoolermanager.MultiPoolerManager/StopReplication"
	MultiPoolerManager_Status_FullMethodName                     = "/multipoolermanager.MultiPoolerManager/Status"
	MultiPoolerManager_Backup_FullMethodName                     = "/multipoolermanager.MultiPoolerManager/Backup"
	MultiPoolerManager_RestoreFromBackup_FullMethodName          = "/multipoolermanager.MultiPoolerManager/RestoreFromBackup"
	MultiPoolerManager_GetBackups_FullMethodName                 = "/multipoolermanager.MultiPoolerManager/GetBackups"
	MultiPoolerManager_GetBackupByJobId_FullMethodName           = "/multipoolermanager.MultiPoolerManager/GetBackupByJobId"
	MultiPoolerManager_ExpireBackups_FullMethodName              = "/multipoolermanager.MultiPoolerManager/ExpireBackups"
	MultiPoolerManager_SetPostgresRestartsEnabled_FullMethodName = "/multipoolermanager.MultiPoolerManager/SetPostgresRestartsEnabled"
	MultiPoolerManager_ManagerHealthStream_FullMethodName        = "/multipoolermanager.MultiPoolerManager/ManagerHealthStream"
)

// MultiPoolerManagerClient is the client API for MultiPoolerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiPoolerManager provides management APIs for PostgreSQL connection poolers
type MultiPoolerManagerClient interface {
	// WaitForLSN waits for PostgreSQL server to reach a specific LSN position
	WaitForLSN(ctx context.Context, in *multipoolermanagerdata.WaitForLSNRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.WaitForLSNResponse, error)
	// StartReplication starts WAL replay on standby (calls pg_wal_replay_resume)
	StartReplication(ctx context.Context, in *multipoolermanagerdata.StartReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StartReplicationResponse, error)
	// StopReplication stops WAL replay on standby (calls pg_wal_replay_pause)
	StopReplication(ctx context.Context, in *multipoolermanagerdata.StopReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StopReplicationResponse, error)
	// Status gets unified status that works for both PRIMARY and REPLICA poolers
	// The multipooler returns information based on what type it believes itself to be,
	// avoiding disparity between what MultiOrch thinks versus actual state
	Status(ctx context.Context, in *multipoolermanagerdata.StatusRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StatusResponse, error)
	// Backup performs a backup
	Backup(ctx context.Context, in *multipoolermanagerdata.BackupRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.BackupResponse, error)
	// RestoreFromBackup restores from a backup
	RestoreFromBackup(ctx context.Context, in *multipoolermanagerdata.RestoreFromBackupRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.RestoreFromBackupResponse, error)
	// GetBackups retrieves backup information
	GetBackups(ctx context.Context, in *multipoolermanagerdata.GetBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupsResponse, error)
	// GetBackupByJobId queries a backup by its job_id annotation.
	// Returns the backup metadata if found, or nil backup if not.
	GetBackupByJobId(ctx context.Context, in *multipoolermanagerdata.GetBackupByJobIdRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupByJobIdResponse, error)
	// ExpireBackups removes backups that exceed the configured retention policy.
	ExpireBackups(ctx context.Context, in *multipoolermanagerdata.ExpireBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ExpireBackupsResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts.
	// When disabled, the monitor continues to run but will not auto-restart a stopped
	// PostgreSQL instance. Used by tests and demos to prevent premature restarts during
	// controlled failovers.
	SetPostgresRestartsEnabled(ctx context.Context, in *multipoolermanagerdata.SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error)
	// ManagerHealthStream is a bidirectional health stream between orchestrator
	// and pooler.
	//
	// The orchestrator sends a start message (ManagerHealthStreamClientMessage
	// with the start field set) to open the stream, then may send poll requests
	// at any time to trigger an immediate snapshot.
	//
	// The pooler sends a full health snapshot on connection, on every state
	// change, in response to poll requests, and periodically as a heartbeat.
	// Every message is a complete snapshot — there are no incremental updates.
	//
	// The orchestrator MUST implement a staleness timeout. The recommended
	// timeout is provided in the timeout field of each snapshot. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	ManagerHealthStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse], error)
}

type multiPoolerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiPoolerManagerClient(cc grpc.ClientConnInterface) MultiPoolerManagerClient {
	_ = "STUB: not implemented"
	return *new(MultiPoolerManagerClient)
}

func (c *multiPoolerManagerClient) WaitForLSN(ctx context.Context, in *multipoolermanagerdata.WaitForLSNRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.WaitForLSNResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) StartReplication(ctx context.Context, in *multipoolermanagerdata.StartReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StartReplicationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) StopReplication(ctx context.Context, in *multipoolermanagerdata.StopReplicationRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StopReplicationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) Status(ctx context.Context, in *multipoolermanagerdata.StatusRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.StatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) Backup(ctx context.Context, in *multipoolermanagerdata.BackupRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.BackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) RestoreFromBackup(ctx context.Context, in *multipoolermanagerdata.RestoreFromBackupRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.RestoreFromBackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) GetBackups(ctx context.Context, in *multipoolermanagerdata.GetBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) GetBackupByJobId(ctx context.Context, in *multipoolermanagerdata.GetBackupByJobIdRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.GetBackupByJobIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) ExpireBackups(ctx context.Context, in *multipoolermanagerdata.ExpireBackupsRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.ExpireBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) SetPostgresRestartsEnabled(ctx context.Context, in *multipoolermanagerdata.SetPostgresRestartsEnabledRequest, opts ...grpc.CallOption) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *multiPoolerManagerClient) ManagerHealthStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse], error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerManager_ManagerHealthStreamClient = grpc.BidiStreamingClient[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]

// MultiPoolerManagerServer is the server API for MultiPoolerManager service.
// All implementations must embed UnimplementedMultiPoolerManagerServer
// for forward compatibility.
//
// MultiPoolerManager provides management APIs for PostgreSQL connection poolers
type MultiPoolerManagerServer interface {
	// WaitForLSN waits for PostgreSQL server to reach a specific LSN position
	WaitForLSN(context.Context, *multipoolermanagerdata.WaitForLSNRequest) (*multipoolermanagerdata.WaitForLSNResponse, error)
	// StartReplication starts WAL replay on standby (calls pg_wal_replay_resume)
	StartReplication(context.Context, *multipoolermanagerdata.StartReplicationRequest) (*multipoolermanagerdata.StartReplicationResponse, error)
	// StopReplication stops WAL replay on standby (calls pg_wal_replay_pause)
	StopReplication(context.Context, *multipoolermanagerdata.StopReplicationRequest) (*multipoolermanagerdata.StopReplicationResponse, error)
	// Status gets unified status that works for both PRIMARY and REPLICA poolers
	// The multipooler returns information based on what type it believes itself to be,
	// avoiding disparity between what MultiOrch thinks versus actual state
	Status(context.Context, *multipoolermanagerdata.StatusRequest) (*multipoolermanagerdata.StatusResponse, error)
	// Backup performs a backup
	Backup(context.Context, *multipoolermanagerdata.BackupRequest) (*multipoolermanagerdata.BackupResponse, error)
	// RestoreFromBackup restores from a backup
	RestoreFromBackup(context.Context, *multipoolermanagerdata.RestoreFromBackupRequest) (*multipoolermanagerdata.RestoreFromBackupResponse, error)
	// GetBackups retrieves backup information
	GetBackups(context.Context, *multipoolermanagerdata.GetBackupsRequest) (*multipoolermanagerdata.GetBackupsResponse, error)
	// GetBackupByJobId queries a backup by its job_id annotation.
	// Returns the backup metadata if found, or nil backup if not.
	GetBackupByJobId(context.Context, *multipoolermanagerdata.GetBackupByJobIdRequest) (*multipoolermanagerdata.GetBackupByJobIdResponse, error)
	// ExpireBackups removes backups that exceed the configured retention policy.
	ExpireBackups(context.Context, *multipoolermanagerdata.ExpireBackupsRequest) (*multipoolermanagerdata.ExpireBackupsResponse, error)
	// SetPostgresRestartsEnabled enables or disables automatic PostgreSQL restarts.
	// When disabled, the monitor continues to run but will not auto-restart a stopped
	// PostgreSQL instance. Used by tests and demos to prevent premature restarts during
	// controlled failovers.
	SetPostgresRestartsEnabled(context.Context, *multipoolermanagerdata.SetPostgresRestartsEnabledRequest) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error)
	// ManagerHealthStream is a bidirectional health stream between orchestrator
	// and pooler.
	//
	// The orchestrator sends a start message (ManagerHealthStreamClientMessage
	// with the start field set) to open the stream, then may send poll requests
	// at any time to trigger an immediate snapshot.
	//
	// The pooler sends a full health snapshot on connection, on every state
	// change, in response to poll requests, and periodically as a heartbeat.
	// Every message is a complete snapshot — there are no incremental updates.
	//
	// The orchestrator MUST implement a staleness timeout. The recommended
	// timeout is provided in the timeout field of each snapshot. If no message is
	// received within this timeout, the pooler should be marked unhealthy.
	ManagerHealthStream(grpc.BidiStreamingServer[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]) error
	mustEmbedUnimplementedMultiPoolerManagerServer()
}

// UnimplementedMultiPoolerManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiPoolerManagerServer struct{}

func (UnimplementedMultiPoolerManagerServer) WaitForLSN(context.Context, *multipoolermanagerdata.WaitForLSNRequest) (*multipoolermanagerdata.WaitForLSNResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) StartReplication(context.Context, *multipoolermanagerdata.StartReplicationRequest) (*multipoolermanagerdata.StartReplicationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) StopReplication(context.Context, *multipoolermanagerdata.StopReplicationRequest) (*multipoolermanagerdata.StopReplicationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) Status(context.Context, *multipoolermanagerdata.StatusRequest) (*multipoolermanagerdata.StatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) Backup(context.Context, *multipoolermanagerdata.BackupRequest) (*multipoolermanagerdata.BackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) RestoreFromBackup(context.Context, *multipoolermanagerdata.RestoreFromBackupRequest) (*multipoolermanagerdata.RestoreFromBackupResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) GetBackups(context.Context, *multipoolermanagerdata.GetBackupsRequest) (*multipoolermanagerdata.GetBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) GetBackupByJobId(context.Context, *multipoolermanagerdata.GetBackupByJobIdRequest) (*multipoolermanagerdata.GetBackupByJobIdResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) ExpireBackups(context.Context, *multipoolermanagerdata.ExpireBackupsRequest) (*multipoolermanagerdata.ExpireBackupsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) SetPostgresRestartsEnabled(context.Context, *multipoolermanagerdata.SetPostgresRestartsEnabledRequest) (*multipoolermanagerdata.SetPostgresRestartsEnabledResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedMultiPoolerManagerServer) ManagerHealthStream(grpc.BidiStreamingServer[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedMultiPoolerManagerServer) mustEmbedUnimplementedMultiPoolerManagerServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedMultiPoolerManagerServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"
	return
}

// UnsafeMultiPoolerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiPoolerManagerServer will
// result in compilation errors.
type UnsafeMultiPoolerManagerServer interface {
	mustEmbedUnimplementedMultiPoolerManagerServer()
}

func RegisterMultiPoolerManagerServer(s grpc.ServiceRegistrar, srv MultiPoolerManagerServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedMultiPoolerManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _MultiPoolerManager_WaitForLSN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_StartReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_StopReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_RestoreFromBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_GetBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_GetBackupByJobId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_ExpireBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_SetPostgresRestartsEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _MultiPoolerManager_ManagerHealthStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerManager_ManagerHealthStreamServer = grpc.BidiStreamingServer[multipoolermanagerdata.ManagerHealthStreamClientMessage, multipoolermanagerdata.ManagerHealthStreamResponse]

// MultiPoolerManager_ServiceDesc is the grpc.ServiceDesc for MultiPoolerManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiPoolerManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multipoolermanager.MultiPoolerManager",
	HandlerType: (*MultiPoolerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WaitForLSN",
			Handler:    _MultiPoolerManager_WaitForLSN_Handler,
		},
		{
			MethodName: "StartReplication",
			Handler:    _MultiPoolerManager_StartReplication_Handler,
		},
		{
			MethodName: "StopReplication",
			Handler:    _MultiPoolerManager_StopReplication_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _MultiPoolerManager_Status_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _MultiPoolerManager_Backup_Handler,
		},
		{
			MethodName: "RestoreFromBackup",
			Handler:    _MultiPoolerManager_RestoreFromBackup_Handler,
		},
		{
			MethodName: "GetBackups",
			Handler:    _MultiPoolerManager_GetBackups_Handler,
		},
		{
			MethodName: "GetBackupByJobId",
			Handler:    _MultiPoolerManager_GetBackupByJobId_Handler,
		},
		{
			MethodName: "ExpireBackups",
			Handler:    _MultiPoolerManager_ExpireBackups_Handler,
		},
		{
			MethodName: "SetPostgresRestartsEnabled",
			Handler:    _MultiPoolerManager_SetPostgresRestartsEnabled_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ManagerHealthStream",
			Handler:       _MultiPoolerManager_ManagerHealthStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "multipoolermanagerservice.proto",
}
