// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: serviceinfoservice.proto

/*
Package serviceinfo is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package serviceinfo

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_ServiceInfo_GetBuildInfo_0(ctx context.Context, marshaler runtime.Marshaler, client ServiceInfoClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_ServiceInfo_GetBuildInfo_0(ctx context.Context, marshaler runtime.Marshaler, server ServiceInfoServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

// RegisterServiceInfoHandlerServer registers the http handlers for service ServiceInfo to "mux".
// UnaryRPC     :call ServiceInfoServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterServiceInfoHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterServiceInfoHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ServiceInfoServer) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterServiceInfoHandlerFromEndpoint is same as RegisterServiceInfoHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterServiceInfoHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// RegisterServiceInfoHandler registers the http handlers for service ServiceInfo to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterServiceInfoHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterServiceInfoHandlerClient registers the http handlers for service ServiceInfo
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ServiceInfoClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ServiceInfoClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ServiceInfoClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterServiceInfoHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ServiceInfoClient) error {
	_ = "STUB: not implemented"
	return nil
}

var (
	pattern_ServiceInfo_GetBuildInfo_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"serviceinfo.ServiceInfo", "GetBuildInfo"}, ""))
)

var (
	forward_ServiceInfo_GetBuildInfo_0 = runtime.ForwardResponseMessage
)
