// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusdata.proto

package consensusdata

import (
	sync "sync"

	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action type for BeginTerm operations
// Indicates what action to execute in addition to term acceptance
type BeginTermAction int32

const (
	// Default/unknown action
	BeginTermAction_BEGIN_TERM_ACTION_UNSPECIFIED BeginTermAction = 0
	// No additional action - only accept the term
	BeginTermAction_BEGIN_TERM_ACTION_NO_ACTION BeginTermAction = 1
	// Revoke the current term by demoting primary or pausing standby replication
	// This is used during failover to ensure the old primary stops accepting writes
	BeginTermAction_BEGIN_TERM_ACTION_REVOKE BeginTermAction = 2
)

// Enum value maps for BeginTermAction.
var (
	BeginTermAction_name = map[int32]string{
		0: "BEGIN_TERM_ACTION_UNSPECIFIED",
		1: "BEGIN_TERM_ACTION_NO_ACTION",
		2: "BEGIN_TERM_ACTION_REVOKE",
	}
	BeginTermAction_value = map[string]int32{
		"BEGIN_TERM_ACTION_UNSPECIFIED": 0,
		"BEGIN_TERM_ACTION_NO_ACTION":   1,
		"BEGIN_TERM_ACTION_REVOKE":      2,
	}
)

func (x BeginTermAction) Enum() *BeginTermAction { _ = "STUB: not implemented"; return nil }

func (x BeginTermAction) String() string { _ = "STUB: not implemented"; return "" }

func (BeginTermAction) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (BeginTermAction) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x BeginTermAction) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use BeginTermAction.Descriptor instead.
func (BeginTermAction) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// WAL position for tracking replication state
type WALPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For primary: current write position from pg_current_wal_lsn()
	// For standby: empty (use last_receive_lsn and last_replay_lsn instead)
	CurrentLsn string `protobuf:"bytes,1,opt,name=current_lsn,json=currentLsn,proto3" json:"current_lsn,omitempty"`
	// For standby: last WAL position received from pg_last_wal_receive_lsn()
	// For primary: empty
	LastReceiveLsn string `protobuf:"bytes,2,opt,name=last_receive_lsn,json=lastReceiveLsn,proto3" json:"last_receive_lsn,omitempty"`
	// For standby: last WAL position replayed from pg_last_wal_replay_lsn()
	// For primary: empty
	LastReplayLsn string `protobuf:"bytes,3,opt,name=last_replay_lsn,json=lastReplayLsn,proto3" json:"last_replay_lsn,omitempty"`
	// Timestamp when this position was recorded
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// PostgreSQL timeline ID from pg_control_checkpoint().
	// Retained for observability and as a secondary safety check during candidate
	// selection (see leadership_term).
	TimelineId int64 `protobuf:"varint,5,opt,name=timeline_id,json=timelineId,proto3" json:"timeline_id,omitempty"`
	// Term number from the most recent multigres.leadership_history record, read
	// after WAL replay stabilizes during revoke. Used as the primary criterion for
	// candidate selection: a node that has replicated a higher consensus term has
	// applied more of the agreed WAL history, regardless of LSN.
	// LSN is used as a tiebreaker only when both term and timeline are equal.
	// 0 if the leadership_history table is empty (e.g. pre-bootstrap).
	LeadershipTerm int64 `protobuf:"varint,6,opt,name=leadership_term,json=leadershipTerm,proto3" json:"leadership_term,omitempty"`
	// Cohort members from the most recent multigres.leadership_history record
	// (application-name strings, same encoding as the table's cohort_members JSONB
	// column). Empty if the table is empty. Allows the coordinator to see which
	// cohort was active on each standby at the time of its last leadership event.
	CohortMembers []string `protobuf:"bytes,7,rep,name=cohort_members,json=cohortMembers,proto3" json:"cohort_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALPosition) Reset() { _ = "STUB: not implemented"; return }

func (x *WALPosition) String() string { _ = "STUB: not implemented"; return "" }

func (*WALPosition) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WALPosition) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WALPosition.ProtoReflect.Descriptor instead.
func (*WALPosition) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WALPosition) GetCurrentLsn() string { _ = "STUB: not implemented"; return "" }

func (x *WALPosition) GetLastReceiveLsn() string { _ = "STUB: not implemented"; return "" }

func (x *WALPosition) GetLastReplayLsn() string { _ = "STUB: not implemented"; return "" }

func (x *WALPosition) GetTimestamp() *timestamppb.Timestamp { _ = "STUB: not implemented"; return nil }

func (x *WALPosition) GetTimelineId() int64 { _ = "STUB: not implemented"; return 0 }

func (x *WALPosition) GetLeadershipTerm() int64 { _ = "STUB: not implemented"; return 0 }

func (x *WALPosition) GetCohortMembers() []string { _ = "STUB: not implemented"; return nil }

// BeginTerm is sent by coordinators during leader appointments
type BeginTermRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term of the candidate
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// ID of the candidate for appointment
	CandidateId *clustermetadata.ID `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Shard ID for this appointment
	ShardId string `protobuf:"bytes,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Version of the durability policy
	PolicyVersion int64 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Action type for this BeginTerm operation
	// Indicates what scenario triggered this term change
	Action        BeginTermAction `protobuf:"varint,5,opt,name=action,proto3,enum=consensusdata.BeginTermAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTermRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *BeginTermRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*BeginTermRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *BeginTermRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use BeginTermRequest.ProtoReflect.Descriptor instead.
func (*BeginTermRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *BeginTermRequest) GetTerm() int64 { _ = "STUB: not implemented"; return 0 }

func (x *BeginTermRequest) GetCandidateId() *clustermetadata.ID {
	_ = "STUB: not implemented"
	return nil
}

func (x *BeginTermRequest) GetShardId() string { _ = "STUB: not implemented"; return "" }

func (x *BeginTermRequest) GetPolicyVersion() int64 { _ = "STUB: not implemented"; return 0 }

func (x *BeginTermRequest) GetAction() BeginTermAction {
	_ = "STUB: not implemented"
	return *new(BeginTermAction)
}

type BeginTermResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current term, for candidate to update itself
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// True if the term was accepted
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// ID of the responding pooler
	PoolerId string `protobuf:"bytes,3,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// WAL position for candidate selection
	WalPosition *WALPosition `protobuf:"bytes,4,opt,name=wal_position,json=walPosition,proto3" json:"wal_position,omitempty"`
	// The pooler's consensus status at the time of the response.
	// For REVOKE actions, captured after WAL positions are frozen (post-revoke snapshot).
	// May be nil if postgres is unreachable.
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,5,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BeginTermResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *BeginTermResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*BeginTermResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *BeginTermResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use BeginTermResponse.ProtoReflect.Descriptor instead.
func (*BeginTermResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *BeginTermResponse) GetTerm() int64 { _ = "STUB: not implemented"; return 0 }

func (x *BeginTermResponse) GetAccepted() bool { _ = "STUB: not implemented"; return false }

func (x *BeginTermResponse) GetPoolerId() string { _ = "STUB: not implemented"; return "" }

func (x *BeginTermResponse) GetWalPosition() *WALPosition { _ = "STUB: not implemented"; return nil }

func (x *BeginTermResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	_ = "STUB: not implemented"
	return nil
}

// Status returns the current status of a node
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional term to include in response
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Shard ID to query status for
	ShardId       string `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *StatusRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*StatusRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StatusRequest) GetTerm() int64 { _ = "STUB: not implemented"; return 0 }

func (x *StatusRequest) GetShardId() string { _ = "STUB: not implemented"; return "" }

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the responding node. Always set, even when postgres is
	// unavailable and consensus_status cannot be constructed.
	Id *clustermetadata.ID `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// The pooler's current consensus status: its term revocation, committed
	// rule position, and highest known rule. Authoritative view of where this
	// pooler stands in the distributed system. Nil when postgres is unavailable.
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,11,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	// Best-effort operational fitness signals for this node. These signals are
	// in-memory and may be absent after a process restart. Coordinators treat
	// absence as "unknown," not "unfit."
	AvailabilityStatus *clustermetadata.AvailabilityStatus `protobuf:"bytes,12,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *StatusResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*StatusResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StatusResponse) GetId() *clustermetadata.ID { _ = "STUB: not implemented"; return nil }

func (x *StatusResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	_ = "STUB: not implemented"
	return nil
}

func (x *StatusResponse) GetAvailabilityStatus() *clustermetadata.AvailabilityStatus {
	_ = "STUB: not implemented"
	return nil
}

// CoordinatorProposal is a coordinator-assisted rule proposal. It either reflects
// a rule that's not yet in WAL that the coordinator wants to write, or it could
// reflect a rule discovered in WAL that hasn't been propagated to the point of
// becoming a decision.
type CoordinatorProposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authority under which this proposal is made. Coordinators must revoke
	// previous agents before making a proposal.
	TermRevocation *clustermetadata.TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	// The node that should become primary to facilitate this proposal.
	ProposalLeader *clustermetadata.PoolerAddress `protobuf:"bytes,2,opt,name=proposal_leader,json=proposalLeader,proto3" json:"proposal_leader,omitempty"`
	// The full proposed rule. This can either be an entirely new rule or an
	// existing rule that hasn't yet finished propagating to durability.
	ProposedRule *clustermetadata.ShardRule `protobuf:"bytes,3,opt,name=proposed_rule,json=proposedRule,proto3" json:"proposed_rule,omitempty"`
	// When true, the leader must apply the incoming cohort GUC directly without
	// first satisfying the outgoing cohort quorum. Only valid for externally-
	// certified proposals (bootstrap, etc.).
	SkipOutgoingQuorum bool `protobuf:"varint,4,opt,name=skip_outgoing_quorum,json=skipOutgoingQuorum,proto3" json:"skip_outgoing_quorum,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CoordinatorProposal) Reset() { _ = "STUB: not implemented"; return }

func (x *CoordinatorProposal) String() string { _ = "STUB: not implemented"; return "" }

func (*CoordinatorProposal) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *CoordinatorProposal) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use CoordinatorProposal.ProtoReflect.Descriptor instead.
func (*CoordinatorProposal) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *CoordinatorProposal) GetTermRevocation() *clustermetadata.TermRevocation {
	_ = "STUB: not implemented"
	return nil
}

func (x *CoordinatorProposal) GetProposalLeader() *clustermetadata.PoolerAddress {
	_ = "STUB: not implemented"
	return nil
}

func (x *CoordinatorProposal) GetProposedRule() *clustermetadata.ShardRule {
	_ = "STUB: not implemented"
	return nil
}

func (x *CoordinatorProposal) GetSkipOutgoingQuorum() bool { _ = "STUB: not implemented"; return false }

// RecruitRequest asks a pooler to revoke all terms below the one in the
// enclosed term_revocation and record the coordinator's exclusive right to
// propose at this term.
type RecruitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The revocation to accept. The pooler persists this to disk and responds
	// with its current ConsensusStatus (which includes the updated revocation).
	TermRevocation *clustermetadata.TermRevocation `protobuf:"bytes,1,opt,name=term_revocation,json=termRevocation,proto3" json:"term_revocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecruitRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *RecruitRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*RecruitRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RecruitRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RecruitRequest.ProtoReflect.Descriptor instead.
func (*RecruitRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RecruitRequest) GetTermRevocation() *clustermetadata.TermRevocation {
	_ = "STUB: not implemented"
	return nil
}

// RecruitResponse carries the pooler's authoritative state after processing
// a RecruitRequest. The coordinator uses current_position to select the best
// promotion candidate.
type RecruitResponse struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecruitResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *RecruitResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*RecruitResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *RecruitResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use RecruitResponse.ProtoReflect.Descriptor instead.
func (*RecruitResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *RecruitResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	_ = "STUB: not implemented"
	return nil
}

// ProposeRequest carries the coordinator's complete proposal for a new shard
// state. Every cohort member receives this: the designated leader promotes
// itself; all others configure replication toward the new primary.
type ProposeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Proposal *CoordinatorProposal   `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	// Human-readable reason for this proposal (e.g. "dead_primary", "bootstrap").
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// IDs of cohort members that accepted the term revocation during recruitment.
	// Used to record which nodes acknowledged the proposal in the rule history.
	AcceptedNodeIds []*clustermetadata.ID `protobuf:"bytes,3,rep,name=accepted_node_ids,json=acceptedNodeIds,proto3" json:"accepted_node_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposeRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ProposeRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ProposeRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ProposeRequest) GetProposal() *CoordinatorProposal { _ = "STUB: not implemented"; return nil }

func (x *ProposeRequest) GetReason() string { _ = "STUB: not implemented"; return "" }

func (x *ProposeRequest) GetAcceptedNodeIds() []*clustermetadata.ID {
	_ = "STUB: not implemented"
	return nil
}

// ProposeResponse carries the pooler's state after applying a ProposeRequest.
type ProposeResponse struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposeResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *ProposeResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*ProposeResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ProposeResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ProposeResponse.ProtoReflect.Descriptor instead.
func (*ProposeResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ProposeResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	_ = "STUB: not implemented"
	return nil
}

// SetTermPrimaryRequest tells a pooler about the current leader and the rule
// the caller knows the cluster is at. The pooler compares the supplied rule
// against its own; if the supplied rule is strictly higher it applies the
// change (standby: update primary_conninfo; stale primary: demote), otherwise
// it returns success without changes. Idempotent under retries and safe
// against out-of-order delivery from stale recovery rounds.
//
// The pooler also validates that leader.id matches rule.leader_id — the
// rule's identity is authoritative; the leader field is just the contact
// information needed to act on that identity.
type SetTermPrimaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contact info for the leader named in rule.leader_id. The pooler uses
	// leader.host and leader.postgres_port when it rewrites primary_conninfo.
	// leader.id must match rule.leader_id.
	Leader *clustermetadata.PoolerAddress `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	// The rule the caller is informing about. The pooler compares this against
	// its own observed rule (by RuleNumber) and only applies the change when
	// the supplied rule is strictly higher.
	Rule          *clustermetadata.ShardRule `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTermPrimaryRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *SetTermPrimaryRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*SetTermPrimaryRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SetTermPrimaryRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SetTermPrimaryRequest.ProtoReflect.Descriptor instead.
func (*SetTermPrimaryRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *SetTermPrimaryRequest) GetLeader() *clustermetadata.PoolerAddress {
	_ = "STUB: not implemented"
	return nil
}

func (x *SetTermPrimaryRequest) GetRule() *clustermetadata.ShardRule {
	_ = "STUB: not implemented"
	return nil
}

// SetTermPrimaryResponse carries the pooler's state after processing a
// SetTermPrimaryRequest.
type SetTermPrimaryResponse struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,1,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetTermPrimaryResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *SetTermPrimaryResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*SetTermPrimaryResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SetTermPrimaryResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SetTermPrimaryResponse.ProtoReflect.Descriptor instead.
func (*SetTermPrimaryResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *SetTermPrimaryResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	_ = "STUB: not implemented"
	return nil
}

var File_consensusdata_proto protoreflect.FileDescriptor

const file_consensusdata_proto_rawDesc = "" +
	"\n" +
	"\x13consensusdata.proto\x12\rconsensusdata\x1a\x15clustermetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x02\n" +
	"\vWALPosition\x12\x1f\n" +
	"\vcurrent_lsn\x18\x01 \x01(\tR\n" +
	"currentLsn\x12(\n" +
	"\x10last_receive_lsn\x18\x02 \x01(\tR\x0elastReceiveLsn\x12&\n" +
	"\x0flast_replay_lsn\x18\x03 \x01(\tR\rlastReplayLsn\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vtimeline_id\x18\x05 \x01(\x03R\n" +
	"timelineId\x12'\n" +
	"\x0fleadership_term\x18\x06 \x01(\x03R\x0eleadershipTerm\x12%\n" +
	"\x0ecohort_members\x18\a \x03(\tR\rcohortMembers\"\xd8\x01\n" +
	"\x10BeginTermRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x126\n" +
	"\fcandidate_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\vcandidateId\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\tR\ashardId\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x03R\rpolicyVersion\x126\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1e.consensusdata.BeginTermActionR\x06action\"\xec\x01\n" +
	"\x11BeginTermResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1b\n" +
	"\tpooler_id\x18\x03 \x01(\tR\bpoolerId\x12=\n" +
	"\fwal_position\x18\x04 \x01(\v2\x1a.consensusdata.WALPositionR\vwalPosition\x12K\n" +
	"\x10consensus_status\x18\x05 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\">\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\"\xd8\x01\n" +
	"\x0eStatusResponse\x12#\n" +
	"\x02id\x18\x04 \x01(\v2\x13.clustermetadata.IDR\x02id\x12K\n" +
	"\x10consensus_status\x18\v \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\x12T\n" +
	"\x13availability_status\x18\f \x01(\v2#.clustermetadata.AvailabilityStatusR\x12availabilityStatus\"\x9b\x02\n" +
	"\x13CoordinatorProposal\x12H\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1f.clustermetadata.TermRevocationR\x0etermRevocation\x12G\n" +
	"\x0fproposal_leader\x18\x02 \x01(\v2\x1e.clustermetadata.PoolerAddressR\x0eproposalLeader\x12?\n" +
	"\rproposed_rule\x18\x03 \x01(\v2\x1a.clustermetadata.ShardRuleR\fproposedRule\x120\n" +
	"\x14skip_outgoing_quorum\x18\x04 \x01(\bR\x12skipOutgoingQuorum\"Z\n" +
	"\x0eRecruitRequest\x12H\n" +
	"\x0fterm_revocation\x18\x01 \x01(\v2\x1f.clustermetadata.TermRevocationR\x0etermRevocation\"^\n" +
	"\x0fRecruitResponse\x12K\n" +
	"\x10consensus_status\x18\x01 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\"\xa9\x01\n" +
	"\x0eProposeRequest\x12>\n" +
	"\bproposal\x18\x01 \x01(\v2\".consensusdata.CoordinatorProposalR\bproposal\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12?\n" +
	"\x11accepted_node_ids\x18\x03 \x03(\v2\x13.clustermetadata.IDR\x0facceptedNodeIds\"^\n" +
	"\x0fProposeResponse\x12K\n" +
	"\x10consensus_status\x18\x01 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\"\x7f\n" +
	"\x15SetTermPrimaryRequest\x126\n" +
	"\x06leader\x18\x01 \x01(\v2\x1e.clustermetadata.PoolerAddressR\x06leader\x12.\n" +
	"\x04rule\x18\x02 \x01(\v2\x1a.clustermetadata.ShardRuleR\x04rule\"e\n" +
	"\x16SetTermPrimaryResponse\x12K\n" +
	"\x10consensus_status\x18\x01 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus*s\n" +
	"\x0fBeginTermAction\x12!\n" +
	"\x1dBEGIN_TERM_ACTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBEGIN_TERM_ACTION_NO_ACTION\x10\x01\x12\x1c\n" +
	"\x18BEGIN_TERM_ACTION_REVOKE\x10\x02B4Z2github.com/multigres/multigres/go/pb/consensusdatab\x06proto3"

var (
	file_consensusdata_proto_rawDescOnce sync.Once
	file_consensusdata_proto_rawDescData []byte
)

func file_consensusdata_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_consensusdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_consensusdata_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_consensusdata_proto_goTypes = []any{
	(BeginTermAction)(0),                       // 0: consensusdata.BeginTermAction
	(*WALPosition)(nil),                        // 1: consensusdata.WALPosition
	(*BeginTermRequest)(nil),                   // 2: consensusdata.BeginTermRequest
	(*BeginTermResponse)(nil),                  // 3: consensusdata.BeginTermResponse
	(*StatusRequest)(nil),                      // 4: consensusdata.StatusRequest
	(*StatusResponse)(nil),                     // 5: consensusdata.StatusResponse
	(*CoordinatorProposal)(nil),                // 6: consensusdata.CoordinatorProposal
	(*RecruitRequest)(nil),                     // 7: consensusdata.RecruitRequest
	(*RecruitResponse)(nil),                    // 8: consensusdata.RecruitResponse
	(*ProposeRequest)(nil),                     // 9: consensusdata.ProposeRequest
	(*ProposeResponse)(nil),                    // 10: consensusdata.ProposeResponse
	(*SetTermPrimaryRequest)(nil),              // 11: consensusdata.SetTermPrimaryRequest
	(*SetTermPrimaryResponse)(nil),             // 12: consensusdata.SetTermPrimaryResponse
	(*timestamppb.Timestamp)(nil),              // 13: google.protobuf.Timestamp
	(*clustermetadata.ID)(nil),                 // 14: clustermetadata.ID
	(*clustermetadata.ConsensusStatus)(nil),    // 15: clustermetadata.ConsensusStatus
	(*clustermetadata.AvailabilityStatus)(nil), // 16: clustermetadata.AvailabilityStatus
	(*clustermetadata.TermRevocation)(nil),     // 17: clustermetadata.TermRevocation
	(*clustermetadata.PoolerAddress)(nil),      // 18: clustermetadata.PoolerAddress
	(*clustermetadata.ShardRule)(nil),          // 19: clustermetadata.ShardRule
}
var file_consensusdata_proto_depIdxs = []int32{
	13, // 0: consensusdata.WALPosition.timestamp:type_name -> google.protobuf.Timestamp
	14, // 1: consensusdata.BeginTermRequest.candidate_id:type_name -> clustermetadata.ID
	0,  // 2: consensusdata.BeginTermRequest.action:type_name -> consensusdata.BeginTermAction
	1,  // 3: consensusdata.BeginTermResponse.wal_position:type_name -> consensusdata.WALPosition
	15, // 4: consensusdata.BeginTermResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	14, // 5: consensusdata.StatusResponse.id:type_name -> clustermetadata.ID
	15, // 6: consensusdata.StatusResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	16, // 7: consensusdata.StatusResponse.availability_status:type_name -> clustermetadata.AvailabilityStatus
	17, // 8: consensusdata.CoordinatorProposal.term_revocation:type_name -> clustermetadata.TermRevocation
	18, // 9: consensusdata.CoordinatorProposal.proposal_leader:type_name -> clustermetadata.PoolerAddress
	19, // 10: consensusdata.CoordinatorProposal.proposed_rule:type_name -> clustermetadata.ShardRule
	17, // 11: consensusdata.RecruitRequest.term_revocation:type_name -> clustermetadata.TermRevocation
	15, // 12: consensusdata.RecruitResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	6,  // 13: consensusdata.ProposeRequest.proposal:type_name -> consensusdata.CoordinatorProposal
	14, // 14: consensusdata.ProposeRequest.accepted_node_ids:type_name -> clustermetadata.ID
	15, // 15: consensusdata.ProposeResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	18, // 16: consensusdata.SetTermPrimaryRequest.leader:type_name -> clustermetadata.PoolerAddress
	19, // 17: consensusdata.SetTermPrimaryRequest.rule:type_name -> clustermetadata.ShardRule
	15, // 18: consensusdata.SetTermPrimaryResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init()                          { file_consensusdata_proto_init() }
func file_consensusdata_proto_init() { _ = "STUB: not implemented"; return }
